// Generated by purs version 0.15.15
import * as Control_Alt from "../Control.Alt/index.js";
import * as Control_Alternative from "../Control.Alternative/index.js";
import * as Control_Applicative from "../Control.Applicative/index.js";
import * as Control_Apply from "../Control.Apply/index.js";
import * as Control_Bind from "../Control.Bind/index.js";
import * as Control_Category from "../Control.Category/index.js";
import * as Control_Semigroupoid from "../Control.Semigroupoid/index.js";
import * as Data_Array from "../Data.Array/index.js";
import * as Data_Array_NonEmpty from "../Data.Array.NonEmpty/index.js";
import * as Data_Bifunctor from "../Data.Bifunctor/index.js";
import * as Data_Either from "../Data.Either/index.js";
import * as Data_Eq from "../Data.Eq/index.js";
import * as Data_Foldable from "../Data.Foldable/index.js";
import * as Data_Function from "../Data.Function/index.js";
import * as Data_Functor from "../Data.Functor/index.js";
import * as Data_Int from "../Data.Int/index.js";
import * as Data_List from "../Data.List/index.js";
import * as Data_List_NonEmpty from "../Data.List.NonEmpty/index.js";
import * as Data_List_Types from "../Data.List.Types/index.js";
import * as Data_Maybe from "../Data.Maybe/index.js";
import * as Data_Monoid from "../Data.Monoid/index.js";
import * as Data_Newtype from "../Data.Newtype/index.js";
import * as Data_Number from "../Data.Number/index.js";
import * as Data_Ord from "../Data.Ord/index.js";
import * as Data_Ordering from "../Data.Ordering/index.js";
import * as Data_Ring from "../Data.Ring/index.js";
import * as Data_Semigroup from "../Data.Semigroup/index.js";
import * as Data_Semigroup_Foldable from "../Data.Semigroup.Foldable/index.js";
import * as Data_String_CodePoints from "../Data.String.CodePoints/index.js";
import * as Data_String_CodeUnits from "../Data.String.CodeUnits/index.js";
import * as Data_String_Common from "../Data.String.Common/index.js";
import * as Data_String_Pattern from "../Data.String.Pattern/index.js";
import * as Data_Tuple from "../Data.Tuple/index.js";
import * as Data_Unfoldable1 from "../Data.Unfoldable1/index.js";
import * as Data_Unit from "../Data.Unit/index.js";
import * as Record from "../Record/index.js";
import * as Record_Builder from "../Record.Builder/index.js";
import * as Type_Proxy from "../Type.Proxy/index.js";
var bind = /* #__PURE__ */ Control_Bind.bind(Data_Either.bindEither);
var lmap = /* #__PURE__ */ Data_Bifunctor.lmap(Data_Bifunctor.bifunctorEither);
var append = /* #__PURE__ */ Data_Semigroup.append(Data_Semigroup.semigroupString);
var unwrap = /* #__PURE__ */ Data_Newtype.unwrap();
var append1 = /* #__PURE__ */ Data_Semigroup.append(Data_Semigroup.semigroupArray);
var intercalate = /* #__PURE__ */ Data_Array.intercalate(Data_Monoid.monoidString);
var bindFlipped = /* #__PURE__ */ Control_Bind.bindFlipped(Control_Bind.bindArray);
var pure = /* #__PURE__ */ Control_Applicative.pure(Data_List_Types.applicativeList);
var power = /* #__PURE__ */ Data_Monoid.power(Data_Monoid.monoidString);
var abs = /* #__PURE__ */ Data_Ord.abs(Data_Ord.ordInt)(Data_Ring.ringInt);
var join = /* #__PURE__ */ Control_Bind.join(Control_Bind.bindArray);
var map = /* #__PURE__ */ Data_Functor.map(Data_Functor.functorArray);
var foldr = /* #__PURE__ */ Data_Foldable.foldr(Data_Foldable.foldableArray);
var max = /* #__PURE__ */ Data_Ord.max(Data_Ord.ordInt);
var bind1 = /* #__PURE__ */ Control_Bind.bind(Control_Bind.bindArray);
var bindFlipped1 = /* #__PURE__ */ Control_Bind.bindFlipped(Data_Either.bindEither);
var map1 = /* #__PURE__ */ Data_Functor.map(Data_Functor.functorFn);
var map2 = /* #__PURE__ */ Data_Functor.map(Data_Either.functorEither);
var elem = /* #__PURE__ */ Data_Array.elem(Data_Eq.eqString);
var fold = /* #__PURE__ */ Data_Foldable.fold(Data_List_Types.foldableList);
var fold1 = /* #__PURE__ */ Data_Semigroup_Foldable.fold1(Data_List_Types.foldable1NonEmptyList);
var eq = /* #__PURE__ */ Data_Eq.eq(/* #__PURE__ */ Data_Eq.eqArray(Data_Eq.eqString));
var compare = /* #__PURE__ */ Data_Ord.compare(/* #__PURE__ */ Data_Ord.ordArray(Data_Ord.ordString));
var compare1 = /* #__PURE__ */ Data_Ord.compare(Data_Ord.ordString);
var intercalate1 = /* #__PURE__ */ Data_Array.intercalate(Data_Monoid.monoidArray);
var alt = /* #__PURE__ */ Control_Alt.alt(Data_Maybe.altMaybe);
var intercalate2 = /* #__PURE__ */ Data_Foldable.intercalate(Data_List_Types.foldableList)(Data_Monoid.monoidString);
var map3 = /* #__PURE__ */ Data_Functor.map(Data_List_Types.functorList);
var foldr1 = /* #__PURE__ */ Data_Foldable.foldr(Data_List_Types.foldableList);
var fromFoldable = /* #__PURE__ */ Data_List.fromFoldable(Data_Foldable.foldableArray);
var apply = /* #__PURE__ */ Control_Apply.apply(Data_Either.applyEither);
var composeFlipped1 = /* #__PURE__ */ Control_Semigroupoid.composeFlipped(Record_Builder.semigroupoidBuilder);
var insert = /* #__PURE__ */ Record_Builder.insert()();
var identity = /* #__PURE__ */ Control_Category.identity(Record_Builder.categoryBuilder);
var voidLeft = /* #__PURE__ */ Data_Functor.voidLeft(Data_Maybe.functorMaybe);
var guard = /* #__PURE__ */ Control_Alternative.guard(Data_Maybe.alternativeMaybe);
var Paras = /* #__PURE__ */ (function () {
    function Paras(value0) {
        this.value0 = value0;
    };
    Paras.create = function (value0) {
        return new Paras(value0);
    };
    return Paras;
})();
var Lines = /* #__PURE__ */ (function () {
    function Lines(value0) {
        this.value0 = value0;
    };
    Lines.create = function (value0) {
        return new Lines(value0);
    };
    return Lines;
})();
var Table = /* #__PURE__ */ (function () {
    function Table(value0) {
        this.value0 = value0;
    };
    Table.create = function (value0) {
        return new Table(value0);
    };
    return Table;
})();
var Indent = /* #__PURE__ */ (function () {
    function Indent(value0) {
        this.value0 = value0;
    };
    Indent.create = function (value0) {
        return new Indent(value0);
    };
    return Indent;
})();
var Text = /* #__PURE__ */ (function () {
    function Text(value0) {
        this.value0 = value0;
    };
    Text.create = function (value0) {
        return new Text(value0);
    };
    return Text;
})();
var IsFlag = /* #__PURE__ */ (function () {
    function IsFlag(value0) {
        this.value0 = value0;
    };
    IsFlag.create = function (value0) {
        return new IsFlag(value0);
    };
    return IsFlag;
})();
var IsAny = /* #__PURE__ */ (function () {
    function IsAny(value0) {
        this.value0 = value0;
    };
    IsAny.create = function (value0) {
        return new IsAny(value0);
    };
    return IsAny;
})();
var IsCommand = /* #__PURE__ */ (function () {
    function IsCommand(value0) {
        this.value0 = value0;
    };
    IsCommand.create = function (value0) {
        return new IsCommand(value0);
    };
    return IsCommand;
})();
var HelpFlag = /* #__PURE__ */ (function () {
    function HelpFlag(value0, value1) {
        this.value0 = value0;
        this.value1 = value1;
    };
    HelpFlag.create = function (value0) {
        return function (value1) {
            return new HelpFlag(value0, value1);
        };
    };
    return HelpFlag;
})();
var HelpAny = /* #__PURE__ */ (function () {
    function HelpAny(value0) {
        this.value0 = value0;
    };
    HelpAny.create = function (value0) {
        return new HelpAny(value0);
    };
    return HelpAny;
})();
var HelpFormat = /* #__PURE__ */ (function () {
    function HelpFormat(value0, value1) {
        this.value0 = value0;
        this.value1 = value1;
    };
    HelpFormat.create = function (value0) {
        return function (value1) {
            return new HelpFormat(value0, value1);
        };
    };
    return HelpFormat;
})();
var HelpArgs = /* #__PURE__ */ (function () {
    function HelpArgs(value0) {
        this.value0 = value0;
    };
    HelpArgs.create = function (value0) {
        return new HelpArgs(value0);
    };
    return HelpArgs;
})();
var HelpChoose = /* #__PURE__ */ (function () {
    function HelpChoose(value0, value1) {
        this.value0 = value0;
        this.value1 = value1;
    };
    HelpChoose.create = function (value0) {
        return function (value1) {
            return new HelpChoose(value0, value1);
        };
    };
    return HelpChoose;
})();
var HelpCommand = /* #__PURE__ */ (function () {
    function HelpCommand(value0, value1, value2) {
        this.value0 = value0;
        this.value1 = value1;
        this.value2 = value2;
    };
    HelpCommand.create = function (value0) {
        return function (value1) {
            return function (value2) {
                return new HelpCommand(value0, value1, value2);
            };
        };
    };
    return HelpCommand;
})();
var HelpRest = /* #__PURE__ */ (function () {
    function HelpRest(value0) {
        this.value0 = value0;
    };
    HelpRest.create = function (value0) {
        return new HelpRest(value0);
    };
    return HelpRest;
})();
var ExpectedFlag = /* #__PURE__ */ (function () {
    function ExpectedFlag() {

    };
    ExpectedFlag.value = new ExpectedFlag();
    return ExpectedFlag;
})();
var ExpectedArgValue = /* #__PURE__ */ (function () {
    function ExpectedArgValue() {

    };
    ExpectedArgValue.value = new ExpectedArgValue();
    return ExpectedArgValue;
})();
var ExpectedRest = /* #__PURE__ */ (function () {
    function ExpectedRest() {

    };
    ExpectedRest.value = new ExpectedRest();
    return ExpectedRest;
})();
var ExpectedArg = /* #__PURE__ */ (function () {
    function ExpectedArg() {

    };
    ExpectedArg.value = new ExpectedArg();
    return ExpectedArg;
})();
var DuplicateArg = /* #__PURE__ */ (function () {
    function DuplicateArg() {

    };
    DuplicateArg.value = new DuplicateArg();
    return DuplicateArg;
})();
var UnformatFailed = /* #__PURE__ */ (function () {
    function UnformatFailed(value0) {
        this.value0 = value0;
    };
    UnformatFailed.create = function (value0) {
        return new UnformatFailed(value0);
    };
    return UnformatFailed;
})();
var UnknownArg = /* #__PURE__ */ (function () {
    function UnknownArg(value0) {
        this.value0 = value0;
    };
    UnknownArg.create = function (value0) {
        return new UnknownArg(value0);
    };
    return UnknownArg;
})();
var ShowHelp = /* #__PURE__ */ (function () {
    function ShowHelp() {

    };
    ShowHelp.value = new ShowHelp();
    return ShowHelp;
})();
var ShowInfo = /* #__PURE__ */ (function () {
    function ShowInfo(value0) {
        this.value0 = value0;
    };
    ShowInfo.create = function (value0) {
        return new ShowInfo(value0);
    };
    return ShowInfo;
})();
var ArgError = /* #__PURE__ */ (function () {
    function ArgError(value0, value1) {
        this.value0 = value0;
        this.value1 = value1;
    };
    ArgError.create = function (value0) {
        return function (value1) {
            return new ArgError(value0, value1);
        };
    };
    return ArgError;
})();
var ArgHalt = /* #__PURE__ */ (function () {
    function ArgHalt(value0) {
        this.value0 = value0;
    };
    ArgHalt.create = function (value0) {
        return new ArgHalt(value0);
    };
    return ArgHalt;
})();
var ArgMatch = /* #__PURE__ */ (function () {
    function ArgMatch(value0, value1) {
        this.value0 = value0;
        this.value1 = value1;
    };
    ArgMatch.create = function (value0) {
        return function (value1) {
            return new ArgMatch(value0, value1);
        };
    };
    return ArgMatch;
})();
var ArgFail = /* #__PURE__ */ (function () {
    function ArgFail() {

    };
    ArgFail.value = new ArgFail();
    return ArgFail;
})();
var ArgFold = function (x) {
    return x;
};
var ArgParser = /* #__PURE__ */ (function () {
    function ArgParser(value0, value1) {
        this.value0 = value0;
        this.value1 = value1;
    };
    ArgParser.create = function (value0) {
        return function (value1) {
            return new ArgParser(value0, value1);
        };
    };
    return ArgParser;
})();
var unformat = function (doc) {
    return function (unf) {
        return function (v) {
            var help = new HelpFormat(doc, v.value0);
            var go = function (v1) {
                var step = function (stk) {
                    return function (args) {
                        var v2 = v1.step(stk)(args);
                        if (v2 instanceof ArgHalt && v2.value0.value0 instanceof Data_List_Types.Cons) {
                            return new ArgHalt(new ArgError(new Data_List_Types.Cons(help, v2.value0.value0.value1), v2.value0.value1));
                        };
                        if (v2 instanceof ArgHalt) {
                            return new ArgHalt(v2.value0);
                        };
                        if (v2 instanceof ArgMatch) {
                            return new ArgMatch(go(v2.value0), v2.value1);
                        };
                        if (v2 instanceof ArgFail) {
                            return ArgFail.value;
                        };
                        throw new Error("Failed pattern match at ArgParse.Basic (line 266, column 7 - line 271, column 27): " + [ v2.constructor.name ]);
                    };
                };
                var done = function (stk) {
                    return bind(v1.done(new Data_List_Types.Cons(help, stk)))(function (value) {
                        return lmap((function () {
                            var $457 = ArgError.create(new Data_List_Types.Cons(help, stk));
                            return function ($458) {
                                return $457(UnformatFailed.create($458));
                            };
                        })())(unf(value));
                    });
                };
                return {
                    step: step,
                    done: done,
                    saturated: v1.saturated
                };
            };
            return new ArgParser(help, go(v.value1));
        };
    };
};
var separated = function (doc) {
    return function (pat) {
        return unformat("[" + (doc + (unwrap(pat) + "...]")))((function () {
            var $459 = Data_String_Common.split(pat);
            return function ($460) {
                return Data_Either.Right.create($459($460));
            };
        })());
    };
};
var semigroupHelp = {
    append: function (v) {
        return function (v1) {
            if (v instanceof HelpArgs && v1 instanceof HelpArgs) {
                return new HelpArgs(append1(v.value0)(v1.value0));
            };
            if (v instanceof HelpArgs) {
                return new HelpArgs(Data_Array.snoc(v.value0)(v1));
            };
            if (v1 instanceof HelpArgs) {
                return new HelpArgs(Data_Array.cons(v)(v1.value0));
            };
            return new HelpArgs([ v, v1 ]);
        };
    }
};
var append2 = /* #__PURE__ */ Data_Semigroup.append(semigroupHelp);
var printHelpTable$prime = function (stk) {
    return function (v) {
        if (v instanceof HelpFlag) {
            var names = intercalate(",")(v.value0);
            if (stk instanceof Data_List_Types.Cons && stk.value0 instanceof HelpFormat) {
                return [ new Data_Tuple.Tuple(new IsFlag(v.value0), [ new Text(names + (" " + stk.value0.value0)), new Text(v.value1) ]) ];
            };
            return [ new Data_Tuple.Tuple(new IsFlag(v.value0), [ new Text(names), new Text(v.value1) ]) ];
        };
        if (v instanceof HelpAny) {
            if (stk instanceof Data_List_Types.Cons && stk.value0 instanceof HelpFormat) {
                return [ new Data_Tuple.Tuple(new IsAny(stk.value0.value0), [ new Text(stk.value0.value0), new Text(v.value0) ]) ];
            };
            return [ new Data_Tuple.Tuple(new IsAny("ANY"), [ new Text("ANY"), new Text(v.value0) ]) ];
        };
        if (v instanceof HelpRest) {
            return [ new Data_Tuple.Tuple(new IsAny("--"), [ new Text("--"), new Text(v.value0) ]) ];
        };
        if (v instanceof HelpCommand) {
            return [ new Data_Tuple.Tuple(new IsCommand(v.value0), [ new Text(intercalate(",")(v.value0)), new Text(v.value1) ]) ];
        };
        if (v instanceof HelpFormat) {
            return printHelpTable$prime(new Data_List_Types.Cons(new HelpFormat(v.value0, v.value1), stk))(v.value1);
        };
        if (v instanceof HelpChoose) {
            return bindFlipped(printHelpTable$prime(stk))(v.value1);
        };
        if (v instanceof HelpArgs) {
            return bindFlipped(printHelpTable$prime(stk))(v.value0);
        };
        throw new Error("Failed pattern match at ArgParse.Basic (line 744, column 23 - line 767, column 33): " + [ v.constructor.name ]);
    };
};
var parserHelp = function (v) {
    return v.value0;
};
var parseArgs$prime = function ($copy_v) {
    return function ($copy_stk) {
        return function ($copy_args) {
            var $tco_var_v = $copy_v;
            var $tco_var_stk = $copy_stk;
            var $tco_done = false;
            var $tco_result;
            function $tco_loop(v, stk, args) {
                var v1 = v.step(stk)(args);
                if (v1 instanceof ArgHalt) {
                    $tco_done = true;
                    return new Data_Either.Left(v1.value0);
                };
                if (v1 instanceof ArgMatch) {
                    $tco_var_v = v1.value0;
                    $tco_var_stk = stk;
                    $copy_args = v1.value1;
                    return;
                };
                if (v1 instanceof ArgFail) {
                    if (args instanceof Data_List_Types.Nil) {
                        $tco_done = true;
                        return v.done(stk);
                    };
                    if (args instanceof Data_List_Types.Cons) {
                        $tco_done = true;
                        return new Data_Either.Left(new ArgError(stk, new UnknownArg(args.value0)));
                    };
                    throw new Error("Failed pattern match at ArgParse.Basic (line 623, column 7 - line 627, column 47): " + [ args.constructor.name ]);
                };
                throw new Error("Failed pattern match at ArgParse.Basic (line 617, column 3 - line 627, column 47): " + [ v1.constructor.name ]);
            };
            while (!$tco_done) {
                $tco_result = $tco_loop($tco_var_v, $tco_var_stk, $copy_args);
            };
            return $tco_result;
        };
    };
};
var parseArgs = function (dictFoldable) {
    var fromFoldable1 = Data_List.fromFoldable(dictFoldable);
    return function (cmd) {
        return function (doc) {
            return function (v) {
                var $461 = parseArgs$prime(v.value1)(pure(new HelpCommand([ cmd ], doc, v.value0)));
                return function ($462) {
                    return $461(fromFoldable1($462));
                };
            };
        };
    };
};
var number = /* #__PURE__ */ unformat("NUMBER")(/* #__PURE__ */ (function () {
    var $463 = Data_Either.note("Invalid number.");
    return function ($464) {
        return $463(Data_Number.fromString($464));
    };
})());
var joinColumns = function (width) {
    return function (sep) {
        return function (leftLines) {
            return function (rightLines) {
                var go = function (left) {
                    return function (right) {
                        var len = Data_String_CodePoints.length(left);
                        var $239 = len < width;
                        if ($239) {
                            return left + (power(" ")(width - len | 0) + (sep + right));
                        };
                        var $240 = len > width;
                        if ($240) {
                            return Data_String_CodePoints.take(width)(left) + (sep + right);
                        };
                        return left + (sep + right);
                    };
                };
                var diff = Data_Array.length(leftLines) - Data_Array.length(rightLines) | 0;
                var $241 = diff < 0;
                if ($241) {
                    return Data_Array.zipWith(go)(append1(leftLines)(Data_Array.replicate(abs(diff))("")))(rightLines);
                };
                return Data_Array.zipWith(go)(leftLines)(append1(rightLines)(Data_Array.replicate(diff)("")));
            };
        };
    };
};
var renderDocLines = function (ind) {
    return function (v) {
        if (v instanceof Paras) {
            return join(Data_Array.intersperse([ "" ])(Data_Array.filter(function ($465) {
                return !Data_Array["null"]($465);
            })(map(renderDocLines(ind))(v.value0))));
        };
        if (v instanceof Lines) {
            return bindFlipped(renderDocLines(ind))(v.value0);
        };
        if (v instanceof Text) {
            return map(append(ind))(Data_String_Common.split("\x0a")(v.value0));
        };
        if (v instanceof Indent) {
            return renderDocLines(ind + "    ")(v.value0);
        };
        if (v instanceof Table) {
            return printTableLines(ind)(v.value0);
        };
        throw new Error("Failed pattern match at ArgParse.Basic (line 780, column 22 - line 790, column 30): " + [ v.constructor.name ]);
    };
};
var printTableLines = function (ind) {
    return function (rows) {
        var rows$prime = map(map(renderDocLines("")))(rows);
        var numCols = foldr(function ($466) {
            return max(Data_Array.length($466));
        })(0)(rows);
        var ixs = Data_Array.range(0)(numCols - 1 | 0);
        var colWidths = map(function (ix) {
            return foldr((function () {
                var $467 = foldr(function ($471) {
                    return max(Data_String_CodePoints.length($471));
                })(0);
                var $468 = Data_Maybe.fromMaybe([  ]);
                var $469 = Data_Function.flip(Data_Array.index)(ix);
                return function ($470) {
                    return max($467($468($469($470))));
                };
            })())(0)(rows$prime);
        })(ixs);
        return bind1(rows$prime)(function (cols) {
            var v = Data_Array_NonEmpty.fromArray(Data_Array.zip(colWidths)(cols));
            if (v instanceof Data_Maybe.Nothing) {
                return [  ];
            };
            if (v instanceof Data_Maybe.Just) {
                return map(append(ind))(Data_Tuple.snd(Data_Array_NonEmpty.foldr1(function (v1) {
                    return function (v2) {
                        return new Data_Tuple.Tuple(v1.value0 + v2.value0 | 0, joinColumns(v1.value0)("    ")(v1.value1)(v2.value1));
                    };
                })(v.value0)));
            };
            throw new Error("Failed pattern match at ArgParse.Basic (line 828, column 3 - line 837, column 27): " + [ v.constructor.name ]);
        });
    };
};
var renderDoc = /* #__PURE__ */ (function () {
    var $472 = intercalate("\x0a");
    var $473 = renderDocLines("");
    return function ($474) {
        return $472($473($474));
    };
})();
var $$int = /* #__PURE__ */ unformat("INTEGER")(/* #__PURE__ */ (function () {
    var $475 = Data_Either.note("Invalid integer.");
    return function ($476) {
        return $475(Data_Int.fromString($476));
    };
})());
var functorArgResult = {
    map: function (f) {
        return function (m) {
            if (m instanceof ArgHalt) {
                return new ArgHalt(m.value0);
            };
            if (m instanceof ArgMatch) {
                return new ArgMatch(f(m.value0), m.value1);
            };
            if (m instanceof ArgFail) {
                return ArgFail.value;
            };
            throw new Error("Failed pattern match at ArgParse.Basic (line 0, column 0 - line 0, column 0): " + [ m.constructor.name ]);
        };
    }
};
var map4 = /* #__PURE__ */ Data_Functor.map(functorArgResult);
var partial = function (unf) {
    return function (v) {
        var go = function (v1) {
            var step = function (stk) {
                return function (args) {
                    return map4(go)(v1.step(stk)(args));
                };
            };
            var done = function (stk) {
                return bindFlipped1((function () {
                    var $477 = lmap(ArgError.create(new Data_List_Types.Cons(v.value0, stk)));
                    return function ($478) {
                        return $477(unf($478));
                    };
                })())(v1.done(stk));
            };
            return {
                step: step,
                done: done,
                saturated: false
            };
        };
        return new ArgParser(v.value0, go(v.value1));
    };
};
var functorArgFold = {
    map: function (f) {
        return function (m) {
            return {
                saturated: m.saturated,
                done: map1(map2(f))(m.done),
                step: map1(map1(map4(Data_Functor.map(functorArgFold)(f))))(m.step)
            };
        };
    }
};
var map5 = /* #__PURE__ */ Data_Functor.map(functorArgFold);
var functorArgParser = {
    map: function (f) {
        return function (m) {
            return new ArgParser(m.value0, map5(f)(m.value1));
        };
    }
};
var map6 = /* #__PURE__ */ Data_Functor.map(functorArgParser);
var voidRight = /* #__PURE__ */ Data_Functor.voidRight(functorArgParser);
var flag$prime = function (names) {
    var go = function (v) {
        if (v instanceof Data_List_Types.Cons && elem(v.value0)(names)) {
            return new ArgMatch(Data_Unit.unit, v.value1);
        };
        return ArgFail.value;
    };
    return go;
};
var flagHelp = /* #__PURE__ */ (function () {
    var name = [ "--help", "-h" ];
    var step = function (stk) {
        return function (args) {
            var v = flag$prime(name)(args);
            if (v instanceof ArgHalt) {
                return new ArgHalt(v.value0);
            };
            if (v instanceof ArgFail) {
                return ArgFail.value;
            };
            if (v instanceof ArgMatch) {
                return new ArgHalt(new ArgError(stk, ShowHelp.value));
            };
            throw new Error("Failed pattern match at ArgParse.Basic (line 462, column 5 - line 465, column 54): " + [ v.constructor.name ]);
        };
    };
    var help = new HelpFlag(name, "Show this help message.");
    var done = Data_Function["const"](new Data_Either.Right(Data_Unit.unit));
    return new ArgParser(help, {
        step: step,
        done: done,
        saturated: true
    });
})();
var flagInfo = function (name) {
    return function (doc) {
        return function (info) {
            var help = new HelpFlag(name, doc);
            var step = function (stk) {
                return function (args) {
                    var v = flag$prime(name)(args);
                    if (v instanceof ArgHalt) {
                        return new ArgHalt(v.value0);
                    };
                    if (v instanceof ArgFail) {
                        return ArgFail.value;
                    };
                    if (v instanceof ArgMatch) {
                        return new ArgHalt(new ArgError(new Data_List_Types.Cons(help, stk), new ShowInfo(info)));
                    };
                    throw new Error("Failed pattern match at ArgParse.Basic (line 483, column 5 - line 486, column 70): " + [ v.constructor.name ]);
                };
            };
            var done = Data_Function["const"](new Data_Either.Right(Data_Unit.unit));
            return new ArgParser(help, {
                step: step,
                done: done,
                saturated: true
            });
        };
    };
};
var failDup = function (help) {
    return function (errMsg) {
        return function (v) {
            var step = function (stk) {
                return function (args) {
                    var v1 = v.step(stk)(args);
                    if (v1 instanceof ArgHalt) {
                        return new ArgHalt(v1.value0);
                    };
                    if (v1 instanceof ArgFail) {
                        return ArgFail.value;
                    };
                    if (v1 instanceof ArgMatch) {
                        return new ArgHalt(new ArgError(new Data_List_Types.Cons(help, stk), errMsg));
                    };
                    throw new Error("Failed pattern match at ArgParse.Basic (line 195, column 5 - line 198, column 61): " + [ v1.constructor.name ]);
                };
            };
            return {
                step: step,
                done: v.done,
                saturated: true
            };
        };
    };
};
var flag = function (name) {
    return function (doc) {
        var help = new HelpFlag(name, doc);
        var step = function (v) {
            var $479 = map4(function (value) {
                return failDup(help)(DuplicateArg.value)({
                    step: step,
                    done: Data_Function["const"](new Data_Either.Right(value)),
                    saturated: true
                });
            });
            var $480 = flag$prime(name);
            return function ($481) {
                return $479($480($481));
            };
        };
        var done = function (stk) {
            return new Data_Either.Left(new ArgError(new Data_List_Types.Cons(help, stk), ExpectedFlag.value));
        };
        return new ArgParser(help, {
            step: step,
            done: done,
            saturated: false
        });
    };
};
var fail = function (err) {
    return {
        step: function (v) {
            return function (v1) {
                return new ArgHalt(err);
            };
        },
        done: Data_Function["const"](new Data_Either.Left(err)),
        saturated: true
    };
};
var many = function (v) {
    var go2 = function (acc) {
        return function (stk) {
            return function (v1) {
                if (v1.saturated) {
                    var v2 = v1.done(stk);
                    if (v2 instanceof Data_Either.Left) {
                        return fail(v2.value0);
                    };
                    if (v2 instanceof Data_Either.Right) {
                        return go1(new Data_List_Types.Cons(v2.value0, acc))(false)(v.value1);
                    };
                    throw new Error("Failed pattern match at ArgParse.Basic (line 343, column 7 - line 347, column 32): " + [ v2.constructor.name ]);
                };
                return go1(acc)(true)(v1);
            };
        };
    };
    var go1 = function (acc) {
        return function (parsing) {
            return function (v1) {
                return {
                    step: function (stk) {
                        var $482 = map4(go2(acc)(stk));
                        var $483 = v1.step(stk);
                        return function ($484) {
                            return $482($483($484));
                        };
                    },
                    done: function (stk) {
                        if (parsing) {
                            return bind(v1.done(stk))(function (next) {
                                return new Data_Either.Right(Data_List.reverse(new Data_List_Types.Cons(next, acc)));
                            });
                        };
                        return new Data_Either.Right(Data_List.reverse(acc));
                    },
                    saturated: false
                };
            };
        };
    };
    return new ArgParser(v.value0, go1(Data_List_Types.Nil.value)(false)(v.value1));
};
var folded = function (dictMonoid) {
    var $485 = map6(fold(dictMonoid));
    return function ($486) {
        return $485(many($486));
    };
};
var many1 = /* #__PURE__ */ (function () {
    var go = function (values) {
        var v = Data_List_NonEmpty.fromList(values);
        if (v instanceof Data_Maybe.Nothing) {
            return new Data_Either.Left(ExpectedArg.value);
        };
        if (v instanceof Data_Maybe.Just) {
            return new Data_Either.Right(v.value0);
        };
        throw new Error("Failed pattern match at ArgParse.Basic (line 357, column 5 - line 361, column 22): " + [ v.constructor.name ]);
    };
    var $487 = partial(go);
    return function ($488) {
        return $487(many($488));
    };
})();
var folded1 = function (dictSemigroup) {
    var $489 = map6(fold1(dictSemigroup));
    return function ($490) {
        return $489(many1($490));
    };
};
var unfolded1 = function (dictUnfoldable1) {
    var go = function (nel) {
        return new Data_Tuple.Tuple(Data_List_NonEmpty.head(nel), Data_List_NonEmpty.fromList(Data_List_NonEmpty.tail(nel)));
    };
    var $491 = map6(Data_Unfoldable1.unfoldr1(dictUnfoldable1)(go));
    return function ($492) {
        return $491(many1($492));
    };
};
var unfolded = function (dictUnfoldable) {
    var $493 = map6(Data_List.toUnfoldable(dictUnfoldable));
    return function ($494) {
        return $493(many($494));
    };
};
var eqHelpClass = {
    eq: function (x) {
        return function (y) {
            if (x instanceof IsFlag && y instanceof IsFlag) {
                return eq(x.value0)(y.value0);
            };
            if (x instanceof IsAny && y instanceof IsAny) {
                return x.value0 === y.value0;
            };
            if (x instanceof IsCommand && y instanceof IsCommand) {
                return eq(x.value0)(y.value0);
            };
            return false;
        };
    }
};
var ordHelpClass = {
    compare: function (x) {
        return function (y) {
            if (x instanceof IsFlag && y instanceof IsFlag) {
                return compare(x.value0)(y.value0);
            };
            if (x instanceof IsFlag) {
                return Data_Ordering.LT.value;
            };
            if (y instanceof IsFlag) {
                return Data_Ordering.GT.value;
            };
            if (x instanceof IsAny && y instanceof IsAny) {
                return compare1(x.value0)(y.value0);
            };
            if (x instanceof IsAny) {
                return Data_Ordering.LT.value;
            };
            if (y instanceof IsAny) {
                return Data_Ordering.GT.value;
            };
            if (x instanceof IsCommand && y instanceof IsCommand) {
                return compare(x.value0)(y.value0);
            };
            throw new Error("Failed pattern match at ArgParse.Basic (line 0, column 0 - line 0, column 0): " + [ x.constructor.name, y.constructor.name ]);
        };
    },
    Eq0: function () {
        return eqHelpClass;
    }
};
var comparing = /* #__PURE__ */ Data_Ord.comparing(ordHelpClass);
var printHelpTable = function (stk) {
    var groupFn = function (v) {
        return function (v1) {
            if (v instanceof IsFlag && v1 instanceof IsFlag) {
                return true;
            };
            if (v instanceof IsAny && v1 instanceof IsAny) {
                return true;
            };
            if (v instanceof IsCommand && v1 instanceof IsCommand) {
                return true;
            };
            return false;
        };
    };
    var $495 = intercalate1([ [ new Text("") ] ]);
    var $496 = map((function () {
        var $501 = map(Data_Tuple.snd);
        return function ($502) {
            return $501(Data_Array_NonEmpty.toArray($502));
        };
    })());
    var $497 = Data_Array.groupBy(Data_Function.on(groupFn)(Data_Tuple.fst));
    var $498 = Data_Array.sortBy(comparing(Data_Tuple.fst));
    var $499 = printHelpTable$prime(stk);
    return function ($500) {
        return $495($496($497($498($499($500)))));
    };
};
var printHelp$prime = function (stk) {
    return function (v) {
        if (v instanceof HelpFormat) {
            return printHelp$prime(new Data_List_Types.Cons(new HelpFormat(v.value0, v.value1), stk))(v.value1);
        };
        if (v instanceof HelpCommand) {
            return new Paras([ new Lines([ new Text(intercalate(",")(v.value0)), new Indent(new Text(v.value1)) ]), new Indent(printHelp$prime(stk)(v.value2)) ]);
        };
        return new Table(printHelpTable(stk)(v));
    };
};
var printArgError = function (v) {
    var getCmd = function ($copy_cmd) {
        return function ($copy_desc) {
            return function ($copy_help) {
                return function ($copy_v1) {
                    var $tco_var_cmd = $copy_cmd;
                    var $tco_var_desc = $copy_desc;
                    var $tco_var_help = $copy_help;
                    var $tco_done = false;
                    var $tco_result;
                    function $tco_loop(cmd, desc, help, v1) {
                        if (v1 instanceof Data_List_Types.Nil) {
                            $tco_done = true;
                            return {
                                cmd: cmd,
                                desc: desc,
                                help: help
                            };
                        };
                        if (v1 instanceof Data_List_Types.Cons && v1.value0 instanceof HelpCommand) {
                            $tco_var_cmd = new Data_List_Types.Cons(v1.value0.value0, cmd);
                            $tco_var_desc = alt(desc)(new Data_Maybe.Just(v1.value0.value1));
                            $tco_var_help = alt(help)(new Data_Maybe.Just(v1.value0.value2));
                            $copy_v1 = v1.value1;
                            return;
                        };
                        if (v1 instanceof Data_List_Types.Cons && v1.value0 instanceof HelpFlag) {
                            $tco_var_cmd = new Data_List_Types.Cons(v1.value0.value0, cmd);
                            $tco_var_desc = Data_Maybe.Nothing.value;
                            $tco_var_help = new Data_Maybe.Just(new HelpFlag(v1.value0.value0, v1.value0.value1));
                            $copy_v1 = v1.value1;
                            return;
                        };
                        if (v1 instanceof Data_List_Types.Cons && v1.value0 instanceof HelpAny) {
                            $tco_var_cmd = cmd;
                            $tco_var_desc = Data_Maybe.Nothing.value;
                            $tco_var_help = new Data_Maybe.Just(new HelpAny(v1.value0.value0));
                            $copy_v1 = v1.value1;
                            return;
                        };
                        if (v1 instanceof Data_List_Types.Cons && v1.value0 instanceof HelpFormat) {
                            $tco_var_cmd = cmd;
                            $tco_var_desc = desc;
                            $tco_var_help = help;
                            $copy_v1 = new Data_List_Types.Cons(v1.value0.value1, v1.value1);
                            return;
                        };
                        if (v1 instanceof Data_List_Types.Cons) {
                            $tco_var_cmd = cmd;
                            $tco_var_desc = desc;
                            $tco_var_help = help;
                            $copy_v1 = v1.value1;
                            return;
                        };
                        throw new Error("Failed pattern match at ArgParse.Basic (line 671, column 26 - line 682, column 30): " + [ v1.constructor.name ]);
                    };
                    while (!$tco_done) {
                        $tco_result = $tco_loop($tco_var_cmd, $tco_var_desc, $tco_var_help, $copy_v1);
                    };
                    return $tco_result;
                };
            };
        };
    };
    var printArgError$prime = function (err) {
        var v1 = getCmd(Data_List_Types.Nil.value)(Data_Maybe.Nothing.value)(Data_Maybe.Nothing.value)(v.value0);
        return new Lines([ new Text(intercalate2(" ")(map3(intercalate(","))(v1.cmd))), new Indent(new Paras([ err, Data_Maybe.maybe(new Lines([  ]))(Text.create)(v1.desc), Data_Maybe.maybe(new Lines([  ]))(printHelp$prime(v.value0))(v1.help) ])) ]);
    };
    return renderDoc((function () {
        if (v.value1 instanceof ExpectedFlag) {
            return printArgError$prime(new Text("Expected flag."));
        };
        if (v.value1 instanceof ExpectedArgValue) {
            if (v.value0 instanceof Data_List_Types.Cons && v.value0.value0 instanceof HelpFormat) {
                return printArgError$prime(new Text("Expected " + (v.value0.value0.value0 + ".")));
            };
            return printArgError$prime(new Text("Expected argument value."));
        };
        if (v.value1 instanceof ExpectedArg) {
            if (v.value0 instanceof Data_List_Types.Cons && v.value0.value0 instanceof HelpFormat) {
                return printArgError$prime(new Text("Expected " + (v.value0.value0.value0 + ".")));
            };
            if (v.value0 instanceof Data_List_Types.Cons && v.value0.value0 instanceof HelpChoose) {
                return printArgError$prime(new Text("Expected " + (v.value0.value0.value0 + ".")));
            };
            return printArgError$prime(new Text("Expected argument."));
        };
        if (v.value1 instanceof ExpectedRest) {
            return printArgError$prime(new Text("Expected rest arguments."));
        };
        if (v.value1 instanceof DuplicateArg) {
            if (v.value0 instanceof Data_List_Types.Cons && v.value0.value0 instanceof HelpChoose) {
                return printArgError$prime(new Text("Duplicate " + (v.value0.value0.value0 + ".")));
            };
            return printArgError$prime(new Text("Duplicate argument."));
        };
        if (v.value1 instanceof UnformatFailed) {
            return printArgError$prime(new Text(v.value1.value0));
        };
        if (v.value1 instanceof ShowHelp) {
            return printArgError$prime(new Lines([  ]));
        };
        if (v.value1 instanceof ShowInfo) {
            return new Text(v.value1.value0);
        };
        if (v.value1 instanceof UnknownArg) {
            return printArgError$prime(new Lines([ new Text("Unexpected argument:"), new Indent(new Text(v.value1.value0)) ]));
        };
        throw new Error("Failed pattern match at ArgParse.Basic (line 633, column 13 - line 668, column 10): " + [ v.value1.constructor.name ]);
    })());
};
var printHelp = /* #__PURE__ */ (function () {
    var $503 = printHelp$prime(Data_List_Types.Nil.value);
    return function ($504) {
        return renderDoc($503($504));
    };
})();
var $$default = function (value) {
    return function (v) {
        return new ArgParser(v.value0, {
            step: v.value1.step,
            done: (function () {
                var $505 = Data_Either.either(Data_Function["const"](new Data_Either.Right(value)))(Data_Either.Right.create);
                return function ($506) {
                    return $505(v.value1.done($506));
                };
            })(),
            saturated: true
        });
    };
};
var optional = /* #__PURE__ */ (function () {
    var $507 = $$default(Data_Maybe.Nothing.value);
    var $508 = map6(Data_Maybe.Just.create);
    return function ($509) {
        return $507($508($509));
    };
})();
var choose = function (name) {
    return function (parsers) {
        var help = new HelpChoose(name, map(parserHelp)(parsers));
        var go2 = function (stk) {
            return function (args) {
                return function (acc) {
                    return function (v) {
                        if (v instanceof Data_List_Types.Cons) {
                            var v1 = v.value0.step(stk)(args);
                            if (v1 instanceof ArgHalt) {
                                return new ArgHalt(v1.value0);
                            };
                            if (v1 instanceof ArgFail) {
                                return go2(stk)(args)(new Data_List_Types.Cons(v.value0, acc))(v.value1);
                            };
                            if (v1 instanceof ArgMatch) {
                                if (v1.value0.saturated) {
                                    return new ArgMatch(failDup(help)(DuplicateArg.value)({
                                        step: go1(foldr1(Data_List_Types.Cons.create)(new Data_List_Types.Cons(v1.value0, v.value1))(acc)),
                                        done: v1.value0.done,
                                        saturated: true
                                    }), v1.value1);
                                };
                                return new ArgMatch({
                                    step: function (stk$prime) {
                                        return function (args$prime$prime) {
                                            return go2(stk$prime)(args$prime$prime)(acc)(new Data_List_Types.Cons(v1.value0, v.value1));
                                        };
                                    },
                                    done: v1.value0.done,
                                    saturated: false
                                }, v1.value1);
                            };
                            throw new Error("Failed pattern match at ArgParse.Basic (line 421, column 7 - line 443, column 20): " + [ v1.constructor.name ]);
                        };
                        if (v instanceof Data_List_Types.Nil) {
                            return ArgFail.value;
                        };
                        throw new Error("Failed pattern match at ArgParse.Basic (line 419, column 22 - line 445, column 14): " + [ v.constructor.name ]);
                    };
                };
            };
        };
        var go1 = function (parsers$prime) {
            return function (stk) {
                return function (args) {
                    return go2(stk)(args)(Data_List_Types.Nil.value)(parsers$prime);
                };
            };
        };
        return new ArgParser(help, {
            step: go1(fromFoldable(map(function (v) {
                return v.value1;
            })(parsers))),
            done: function (stk) {
                return new Data_Either.Left(new ArgError(new Data_List_Types.Cons(help, stk), ExpectedArg.value));
            },
            saturated: false
        });
    };
};
var buildRecordArgs = function (dict) {
    return dict.buildRecordArgs;
};
var fromRecord = function () {
    return function (dictBuildRecordArgs) {
        var $510 = map6(Record_Builder.buildFromScratch);
        var $511 = buildRecordArgs(dictBuildRecordArgs)(Type_Proxy["Proxy"].value);
        return function ($512) {
            return $510($511($512));
        };
    };
};
var $$boolean = /* #__PURE__ */ (function () {
    var $513 = $$default(false);
    return function ($514) {
        return $513((function (v) {
            return voidRight(true)(v);
        })($514));
    };
})();
var argument$prime = function (stk) {
    return function (names) {
        var matchParam = function (arg) {
            return Data_Array.findMap((function () {
                var $515 = Data_Function.flip(Data_String_CodeUnits.stripPrefix)(arg);
                return function ($516) {
                    return $515(Data_String_Pattern.Pattern($516));
                };
            })())(names);
        };
        var go = function (v) {
            var v1 = function (v2) {
                return ArgFail.value;
            };
            if (v instanceof Data_List_Types.Cons) {
                var $410 = matchParam(v.value0);
                if ($410 instanceof Data_Maybe.Just) {
                    var $411 = Data_String_CodeUnits.take(1)($410.value0) === "=";
                    if ($411) {
                        return new ArgMatch(Data_String_CodeUnits.drop(1)($410.value0), v.value1);
                    };
                    var $412 = $410.value0 === "";
                    if ($412) {
                        if (v.value1 instanceof Data_List_Types.Cons) {
                            return new ArgMatch(v.value1.value0, v.value1.value1);
                        };
                        return new ArgHalt(new ArgError(stk, ExpectedArgValue.value));
                    };
                    return ArgFail.value;
                };
                return v1(true);
            };
            return v1(true);
        };
        return go;
    };
};
var argument = function (name) {
    return function (doc) {
        var help = new HelpFlag(name, doc);
        var step = function (stk) {
            var $517 = map4(function (value) {
                return failDup(help)(DuplicateArg.value)({
                    step: step,
                    done: Data_Function["const"](new Data_Either.Right(value)),
                    saturated: true
                });
            });
            var $518 = argument$prime(new Data_List_Types.Cons(help, stk))(name);
            return function ($519) {
                return $517($518($519));
            };
        };
        var done = function (stk) {
            return new Data_Either.Left(new ArgError(new Data_List_Types.Cons(help, stk), ExpectedArg.value));
        };
        return new ArgParser(help, {
            step: step,
            done: done,
            saturated: false
        });
    };
};
var applyArgFold = {
    apply: function (v) {
        return function (v1) {
            var step = function (stk) {
                return function (args) {
                    var v2 = v.step(stk)(args);
                    if (v2 instanceof ArgHalt) {
                        return new ArgHalt(v2.value0);
                    };
                    if (v2 instanceof ArgMatch) {
                        return new ArgMatch(Control_Apply.apply(applyArgFold)(v2.value0)(v1), v2.value1);
                    };
                    if (v2 instanceof ArgFail) {
                        var v3 = v1.step(stk)(args);
                        if (v3 instanceof ArgHalt) {
                            return new ArgHalt(v3.value0);
                        };
                        if (v3 instanceof ArgMatch) {
                            return new ArgMatch(Control_Apply.apply(applyArgFold)(v)(v3.value0), v3.value1);
                        };
                        if (v3 instanceof ArgFail) {
                            return ArgFail.value;
                        };
                        throw new Error("Failed pattern match at ArgParse.Basic (line 166, column 11 - line 172, column 22): " + [ v3.constructor.name ]);
                    };
                    throw new Error("Failed pattern match at ArgParse.Basic (line 161, column 7 - line 172, column 22): " + [ v2.constructor.name ]);
                };
            };
            var done = function (stk) {
                return apply(v.done(stk))(v1.done(stk));
            };
            return {
                step: step,
                done: done,
                saturated: v.saturated && v1.saturated
            };
        };
    },
    Functor0: function () {
        return functorArgFold;
    }
};
var apply1 = /* #__PURE__ */ Control_Apply.apply(applyArgFold);
var applyParser = {
    apply: function (v) {
        return function (v1) {
            return new ArgParser(append2(v.value0)(v1.value0), apply1(v.value1)(v1.value1));
        };
    },
    Functor0: function () {
        return functorArgParser;
    }
};
var apply2 = /* #__PURE__ */ Control_Apply.apply(applyParser);
var buildArgsCons = function (dictIsSymbol) {
    var insert1 = insert(dictIsSymbol);
    var get = Record.get(dictIsSymbol)();
    return function () {
        return function () {
            return function () {
                return function (dictBuildRecordArgs) {
                    var buildRecordArgs1 = buildRecordArgs(dictBuildRecordArgs);
                    return {
                        buildRecordArgs: function (v) {
                            return function (rs) {
                                return apply2(map6(function (a) {
                                    return function (b) {
                                        return composeFlipped1(insert1(Type_Proxy["Proxy"].value)(a))(b);
                                    };
                                })(get(Type_Proxy["Proxy"].value)(rs)))(buildRecordArgs1(Type_Proxy["Proxy"].value)(rs));
                            };
                        }
                    };
                };
            };
        };
    };
};
var applicativeArgFold = {
    pure: function (value) {
        return {
            step: function (v) {
                return function (v1) {
                    return ArgFail.value;
                };
            },
            done: Data_Function["const"](new Data_Either.Right(value)),
            saturated: true
        };
    },
    Apply0: function () {
        return applyArgFold;
    }
};
var pure1 = /* #__PURE__ */ Control_Applicative.pure(applicativeArgFold);
var buildRecordArgsNil = {
    buildRecordArgs: function (v) {
        return function (v1) {
            return new ArgParser(new HelpArgs([  ]), pure1(identity));
        };
    }
};
var command = function (name) {
    return function (doc) {
        return function (v) {
            var help = new HelpCommand(name, doc, v.value0);
            var go = function (v1) {
                var step = function (stk) {
                    return function (args) {
                        var v2 = flag$prime(name)(args);
                        if (v2 instanceof ArgHalt) {
                            return new ArgHalt(v2.value0);
                        };
                        if (v2 instanceof ArgFail) {
                            return ArgFail.value;
                        };
                        if (v2 instanceof ArgMatch) {
                            var v3 = parseArgs$prime(v1)(new Data_List_Types.Cons(help, stk))(v2.value1);
                            if (v3 instanceof Data_Either.Left) {
                                return new ArgHalt(v3.value0);
                            };
                            if (v3 instanceof Data_Either.Right) {
                                return new ArgMatch(pure1(v3.value0), Data_List_Types.Nil.value);
                            };
                            throw new Error("Failed pattern match at ArgParse.Basic (line 555, column 11 - line 559, column 40): " + [ v3.constructor.name ]);
                        };
                        throw new Error("Failed pattern match at ArgParse.Basic (line 551, column 7 - line 559, column 40): " + [ v2.constructor.name ]);
                    };
                };
                return {
                    step: step,
                    done: v1.done,
                    saturated: false
                };
            };
            return new ArgParser(help, go(v.value1));
        };
    };
};
var rest = function (dictUnfoldable) {
    var toUnfoldable = Data_List.toUnfoldable(dictUnfoldable);
    return function (doc) {
        var step = function (v) {
            return function (v1) {
                if (v1 instanceof Data_List_Types.Cons && v1.value0 === "--") {
                    return new ArgMatch(pure1(toUnfoldable(v1.value1)), Data_List_Types.Nil.value);
                };
                return ArgFail.value;
            };
        };
        var help = new HelpRest(doc);
        var done = function (stk) {
            return new Data_Either.Left(new ArgError(new Data_List_Types.Cons(help, stk), ExpectedRest.value));
        };
        return new ArgParser(help, {
            step: step,
            done: done,
            saturated: false
        });
    };
};
var any = function (name) {
    return function (doc) {
        return function (k) {
            var step = function (v) {
                return function (v1) {
                    var v2 = function (v3) {
                        return ArgFail.value;
                    };
                    if (v1 instanceof Data_List_Types.Cons) {
                        var $453 = k(v1.value0);
                        if ($453 instanceof Data_Maybe.Just) {
                            return new ArgMatch(pure1($453.value0), v1.value1);
                        };
                        return v2(true);
                    };
                    return v2(true);
                };
            };
            var help = new HelpFormat(name, new HelpAny(doc));
            var done = function (stk) {
                return new Data_Either.Left(new ArgError(new Data_List_Types.Cons(help, stk), ExpectedArg.value));
            };
            return new ArgParser(help, {
                step: step,
                done: done,
                saturated: false
            });
        };
    };
};
var anyNotFlag = function (name) {
    return function (doc) {
        return any(name)(doc)(function (str) {
            return voidLeft(guard(Data_String_CodePoints.take(1)(str) !== "-"))(str);
        });
    };
};
export {
    ArgError,
    ExpectedFlag,
    ExpectedArgValue,
    ExpectedRest,
    ExpectedArg,
    DuplicateArg,
    UnformatFailed,
    UnknownArg,
    ShowHelp,
    ShowInfo,
    HelpFlag,
    HelpAny,
    HelpFormat,
    HelpArgs,
    HelpChoose,
    HelpCommand,
    HelpRest,
    flag,
    flagHelp,
    flagInfo,
    argument,
    fromRecord,
    unformat,
    $$int as int,
    number,
    $$boolean as boolean,
    separated,
    many,
    many1,
    unfolded,
    unfolded1,
    folded,
    folded1,
    $$default as default,
    optional,
    choose,
    command,
    any,
    anyNotFlag,
    rest,
    parseArgs,
    printArgError,
    printHelp,
    parserHelp,
    buildRecordArgs,
    functorArgParser,
    applyParser,
    semigroupHelp,
    buildRecordArgsNil,
    buildArgsCons
};
