// Generated by purs version 0.15.15
import * as Control_Bind from "../Control.Bind/index.js";
import * as Data_Array from "../Data.Array/index.js";
import * as Data_Maybe from "../Data.Maybe/index.js";
import * as Data_Show from "../Data.Show/index.js";
import * as Effect_Aff from "../Effect.Aff/index.js";
import * as Effect_Class from "../Effect.Class/index.js";
import * as Effect_Console from "../Effect.Console/index.js";
import * as PureScript_Backend_Optimizer_App from "../PureScript.Backend.Optimizer.App/index.js";
var discard = /* #__PURE__ */ Control_Bind.discard(Control_Bind.discardUnit)(Effect_Aff.bindAff);
var liftEffect = /* #__PURE__ */ Effect_Class.liftEffect(Effect_Aff.monadEffectAff);
var bind = /* #__PURE__ */ Control_Bind.bind(Effect_Aff.bindAff);
var show = /* #__PURE__ */ Data_Show.show(Data_Show.showInt);
var main = /* #__PURE__ */ Effect_Aff.launchAff_(/* #__PURE__ */ discard(/* #__PURE__ */ liftEffect(/* #__PURE__ */ Effect_Console.log("=== D\xe9marrage du Sandbox: Parseur de tcorefn ===")))(function () {
    return bind(PureScript_Backend_Optimizer_App.readCoreFnModule("output/Data.Unit/corefn.json"))(function (mbMod) {
        if (mbMod instanceof Data_Maybe.Nothing) {
            return liftEffect(Effect_Console.log("\u274c Impossible de lire ou parser output/Data.Unit/corefn.json"));
        };
        if (mbMod instanceof Data_Maybe.Just) {
            return discard(liftEffect(Effect_Console.log("\u2705 Module lu et pars\xe9 avec succ\xe8s depuis le JSON !")))(function () {
                return discard(liftEffect(Effect_Console.log("\u2699\ufe0f  Nombre d'imports : " + show(Data_Array.length(mbMod.value0.imports)))))(function () {
                    return liftEffect(Effect_Console.log("\ud83d\udee0\ufe0f  Nombre de d\xe9finitions globales (decls) : " + show(Data_Array.length(mbMod.value0.decls))));
                });
            });
        };
        throw new Error("Failed pattern match at Test.TestConvert (line 18, column 3 - line 24, column 114): " + [ mbMod.constructor.name ]);
    });
}));
export {
    main
};
