// Generated by purs version 0.15.15
import * as Control_Bind from "../Control.Bind/index.js";
import * as Data_Array from "../Data.Array/index.js";
import * as Data_Foldable from "../Data.Foldable/index.js";
import * as Data_Function from "../Data.Function/index.js";
import * as Data_Functor from "../Data.Functor/index.js";
import * as Data_Map_Internal from "../Data.Map.Internal/index.js";
import * as Data_Maybe from "../Data.Maybe/index.js";
import * as Data_Newtype from "../Data.Newtype/index.js";
import * as Data_Ord from "../Data.Ord/index.js";
import * as Data_Semigroup from "../Data.Semigroup/index.js";
import * as Data_Set from "../Data.Set/index.js";
import * as Data_Show from "../Data.Show/index.js";
import * as Data_String_CodePoints from "../Data.String.CodePoints/index.js";
import * as Data_String_CodeUnits from "../Data.String.CodeUnits/index.js";
import * as Data_String_Common from "../Data.String.Common/index.js";
import * as Data_Tuple from "../Data.Tuple/index.js";
import * as Data_Unfoldable from "../Data.Unfoldable/index.js";
import * as Data_Unit from "../Data.Unit/index.js";
import * as Debug from "../Debug/index.js";
import * as PureScript_Backend_Optimizer_CoreFn from "../PureScript.Backend.Optimizer.CoreFn/index.js";
import * as PureScript_Backend_Optimizer_FfiSupport from "../PureScript.Backend.Optimizer.FfiSupport/index.js";
import * as PureScript_Backend_Optimizer_Substitute from "../PureScript.Backend.Optimizer.Substitute/index.js";
var map = /* #__PURE__ */ Data_Functor.map(Data_Functor.functorArray);
var map1 = /* #__PURE__ */ Data_Functor.map(PureScript_Backend_Optimizer_CoreFn.functorLiteral);
var map2 = /* #__PURE__ */ Data_Functor.map(Data_Maybe.functorMaybe);
var append1 = /* #__PURE__ */ Data_Semigroup.append(Data_Semigroup.semigroupArray);
var insert = /* #__PURE__ */ Data_Set.insert(PureScript_Backend_Optimizer_CoreFn.ordExprType);
var foldl = /* #__PURE__ */ Data_Foldable.foldl(PureScript_Backend_Optimizer_CoreFn.foldableLiteral);
var foldl1 = /* #__PURE__ */ Data_Foldable.foldl(Data_Foldable.foldableArray);
var lookup = /* #__PURE__ */ Data_Map_Internal.lookup(PureScript_Backend_Optimizer_CoreFn.ordIdent);
var bind = /* #__PURE__ */ Control_Bind.bind(Data_Maybe.bindMaybe);
var unwrap = /* #__PURE__ */ Data_Newtype.unwrap();
var lookup1 = /* #__PURE__ */ Data_Map_Internal.lookup(Data_Ord.ordString);
var insert1 = /* #__PURE__ */ Data_Map_Internal.insert(PureScript_Backend_Optimizer_CoreFn.ordIdent);
var insertWith = /* #__PURE__ */ Data_Map_Internal.insertWith(Data_Ord.ordString);
var unionWith = /* #__PURE__ */ Data_Map_Internal.unionWith(PureScript_Backend_Optimizer_CoreFn.ordExprType);
var union = /* #__PURE__ */ Data_Set.union(Data_Ord.ordString);
var union1 = /* #__PURE__ */ Data_Set.union(PureScript_Backend_Optimizer_CoreFn.ordIdent);
var insert2 = /* #__PURE__ */ Data_Set.insert(PureScript_Backend_Optimizer_CoreFn.ordIdent);
var difference = /* #__PURE__ */ Data_Set.difference(PureScript_Backend_Optimizer_CoreFn.ordIdent);
var $$delete = /* #__PURE__ */ Data_Set["delete"](PureScript_Backend_Optimizer_CoreFn.ordIdent);
var map3 = /* #__PURE__ */ Data_Functor.map(PureScript_Backend_Optimizer_CoreFn.functorBinder);
var delete1 = /* #__PURE__ */ Data_Map_Internal["delete"](PureScript_Backend_Optimizer_CoreFn.ordIdent);
var member = /* #__PURE__ */ Data_Set.member(PureScript_Backend_Optimizer_CoreFn.ordIdent);
var trace = /* #__PURE__ */ Debug.trace();
var show = /* #__PURE__ */ Data_Show.show(Data_Show.showInt);
var toUnfoldable = /* #__PURE__ */ Data_Map_Internal.toUnfoldable(Data_Unfoldable.unfoldableArray);
var member1 = /* #__PURE__ */ Data_Map_Internal.member(Data_Ord.ordString);
var toUnfoldable1 = /* #__PURE__ */ Data_Set.toUnfoldable(Data_Unfoldable.unfoldableArray);
var stripTypeVariables = function ($copy_v) {
    var $tco_done = false;
    var $tco_result;
    function $tco_loop(v) {
        if (v instanceof PureScript_Backend_Optimizer_CoreFn.ForAll) {
            $copy_v = v.value1;
            return;
        };
        if (v instanceof PureScript_Backend_Optimizer_CoreFn.ConstrainedType) {
            $copy_v = v.value1;
            return;
        };
        $tco_done = true;
        return v;
    };
    while (!$tco_done) {
        $tco_result = $tco_loop($copy_v);
    };
    return $tco_result;
};
var resolveGlobalsBinder = function (definerMod) {
    return function (v) {
        if (v instanceof PureScript_Backend_Optimizer_CoreFn.BinderConstructor) {
            var t$prime = (function () {
                if (v.value1.value0 instanceof Data_Maybe.Nothing) {
                    return new PureScript_Backend_Optimizer_CoreFn.Qualified(new Data_Maybe.Just(definerMod), v.value1.value1);
                };
                return v.value1;
            })();
            var c$prime = (function () {
                if (v.value2.value0 instanceof Data_Maybe.Nothing) {
                    return new PureScript_Backend_Optimizer_CoreFn.Qualified(new Data_Maybe.Just(definerMod), v.value2.value1);
                };
                return v.value2;
            })();
            return new PureScript_Backend_Optimizer_CoreFn.BinderConstructor(v.value0, t$prime, c$prime, map(resolveGlobalsBinder(definerMod))(v.value3));
        };
        if (v instanceof PureScript_Backend_Optimizer_CoreFn.BinderNamed) {
            return new PureScript_Backend_Optimizer_CoreFn.BinderNamed(v.value0, v.value1, resolveGlobalsBinder(definerMod)(v.value2));
        };
        if (v instanceof PureScript_Backend_Optimizer_CoreFn.BinderLit) {
            return new PureScript_Backend_Optimizer_CoreFn.BinderLit(v.value0, map1(resolveGlobalsBinder(definerMod))(v.value1));
        };
        return v;
    };
};
var rebuildApp = function (finalAnn) {
    return function (f) {
        return function (args) {
            var v = Data_Array.uncons(args);
            if (v instanceof Data_Maybe.Nothing) {
                return f;
            };
            if (v instanceof Data_Maybe.Just) {
                var firstApp = new PureScript_Backend_Optimizer_CoreFn.ExprApp(finalAnn, f, v.value0.head);
                return Data_Array.foldl(function (acc) {
                    return function (arg) {
                        return new PureScript_Backend_Optimizer_CoreFn.ExprApp(finalAnn, acc, arg);
                    };
                })(firstApp)(v.value0.tail);
            };
            throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 554, column 3 - line 558, column 74): " + [ v.constructor.name ]);
        };
    };
};
var partitionArgs = function ($copy_v) {
    return function ($copy_v1) {
        var $tco_var_v = $copy_v;
        var $tco_done = false;
        var $tco_result;
        function $tco_loop(v, v1) {
            if (v instanceof PureScript_Backend_Optimizer_CoreFn.ConstrainedType) {
                var numDicts = Data_Array.length(v.value0);
                var normalArgs = Data_Array.drop(numDicts)(v1);
                var dictArgs = Data_Array.take(numDicts)(v1);
                $tco_done = true;
                return {
                    dictArgs: dictArgs,
                    normalArgs: normalArgs
                };
            };
            if (v instanceof PureScript_Backend_Optimizer_CoreFn.ForAll) {
                $tco_var_v = v.value1;
                $copy_v1 = v1;
                return;
            };
            $tco_done = true;
            return {
                dictArgs: [  ],
                normalArgs: v1
            };
        };
        while (!$tco_done) {
            $tco_result = $tco_loop($tco_var_v, $copy_v1);
        };
        return $tco_result;
    };
};
var mapAnn = function (f) {
    return function (v) {
        return {
            span: v.span,
            meta: v.meta,
            type: map2(f)(v.type)
        };
    };
};
var mangleType = function (v) {
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.Int) {
        return "Int";
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn["Number"]) {
        return "Number";
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn["String"]) {
        return "String";
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.Char) {
        return "Char";
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn["Boolean"]) {
        return "Boolean";
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.Unit) {
        return "Unit";
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.Any) {
        return "Any";
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.TypeLevelString) {
        return "TypeLevelString_" + v.value0;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn["Array"]) {
        return "Array_" + mangleType(v.value0);
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.Func) {
        return "Func_" + (Data_String_Common.joinWith("_")(map(mangleType)(v.value0)) + ("_" + mangleType(v.value1)));
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.Record) {
        return "Record_" + mangleType(v.value0);
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.Row) {
        return "Row_" + (Data_String_Common.joinWith("_")(map(function (v1) {
            return v1.value0 + ("_" + mangleType(v1.value1));
        })(v.value0)) + ("_" + Data_Maybe.maybe("Empty")(mangleType)(v.value1)));
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.TypeApp) {
        return "TypeApp_" + (mangleType(v.value0) + ("_" + Data_String_Common.joinWith("_")(map(mangleType)(v.value1))));
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ForAll) {
        return "ForAll_" + (Data_String_Common.joinWith("_")(v.value0) + ("_" + mangleType(v.value1)));
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ConstrainedType) {
        return "ConstrainedType_" + (Data_String_Common.joinWith("_")(map(function (v1) {
            return Data_String_Common.joinWith("_")(v1.value0) + ("_" + Data_String_Common.joinWith("_")(map(mangleType)(v1.value1)));
        })(v.value0)) + ("_" + mangleType(v.value1)));
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ADT) {
        return "ADT_" + (Data_String_Common.joinWith("_")(v.value1) + (function () {
            var $210 = Data_Array.length(v.value2) === 0;
            if ($210) {
                return "";
            };
            return "_" + Data_String_Common.joinWith("_")(map(mangleType)(v.value2));
        })());
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.TypeVar) {
        return "Var_" + v.value0;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.Any) {
        return "Any";
    };
    throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 67, column 1 - line 67, column 33): " + [ v.constructor.name ]);
};
var isStatic = function (v) {
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprVar && v.value1.value0 instanceof Data_Maybe.Just) {
        return true;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprVar && v.value1.value0 instanceof Data_Maybe.Nothing) {
        return false;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprApp) {
        return isStatic(v.value1) && isStatic(v.value2);
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprAccessor) {
        return isStatic(v.value1);
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprLit) {
        return true;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprConstructor) {
        return true;
    };
    return false;
};
var stripStaticConstraints = function (dictArgs) {
    return function (v) {
        if (v instanceof PureScript_Backend_Optimizer_CoreFn.ConstrainedType) {
            var remainingConstraints = Data_Array.drop(Data_Array.length(dictArgs))(v.value0);
            var newConstraints = Data_Array.mapMaybe(function (v1) {
                var $239 = isStatic(v1.value0);
                if ($239) {
                    return Data_Maybe.Nothing.value;
                };
                return new Data_Maybe.Just(v1.value1);
            })(Data_Array.zip(dictArgs)(v.value0));
            var finalConstraints = append1(newConstraints)(remainingConstraints);
            var $242 = Data_Array.length(finalConstraints) === 0;
            if ($242) {
                return stripStaticConstraints(dictArgs)(v.value1);
            };
            return new PureScript_Backend_Optimizer_CoreFn.ConstrainedType(finalConstraints, stripStaticConstraints(dictArgs)(v.value1));
        };
        if (v instanceof PureScript_Backend_Optimizer_CoreFn.ForAll) {
            return new PureScript_Backend_Optimizer_CoreFn.ForAll(v.value0, stripStaticConstraints(dictArgs)(v.value1));
        };
        return v;
    };
};
var hasTypeVariables = function (v) {
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.TypeVar) {
        return Data_String_CodePoints.take(1)(v.value0) === Data_String_Common.toLower(Data_String_CodePoints.take(1)(v.value0)) && v.value0 !== "gopurs_runtime.Value";
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.Func) {
        return Data_Array.any(hasTypeVariables)(v.value0) || hasTypeVariables(v.value1);
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn["Array"]) {
        return hasTypeVariables(v.value0);
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.Record) {
        return hasTypeVariables(v.value0);
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.Row) {
        var tailHas = (function () {
            if (v.value1 instanceof Data_Maybe.Nothing) {
                return false;
            };
            if (v.value1 instanceof Data_Maybe.Just) {
                return hasTypeVariables(v.value1.value0);
            };
            throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 566, column 17 - line 568, column 37): " + [ v.value1.constructor.name ]);
        })();
        return Data_Array.any(function (v1) {
            return hasTypeVariables(v1.value1);
        })(v.value0) || tailHas;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.TypeApp) {
        return hasTypeVariables(v.value0) || Data_Array.any(hasTypeVariables)(v.value1);
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ForAll) {
        return hasTypeVariables(v.value1);
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ConstrainedType) {
        return Data_Array.any(function (v1) {
            return Data_Array.any(hasTypeVariables)(v1.value1);
        })(v.value0) || hasTypeVariables(v.value1);
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.Int) {
        return false;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn["String"]) {
        return false;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.Char) {
        return false;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn["Number"]) {
        return false;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn["Boolean"]) {
        return false;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.Unit) {
        return false;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.TypeLevelString) {
        return false;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ADT) {
        return Data_Array.any(hasTypeVariables)(v.value2);
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.Any) {
        return false;
    };
    throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 560, column 1 - line 560, column 40): " + [ v.constructor.name ]);
};
var getExprAnn = function (v) {
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprVar) {
        return v.value0;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprLit) {
        return v.value0;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprApp) {
        return v.value0;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprAbs) {
        return v.value0;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprLet) {
        return v.value0;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprCase) {
        return v.value0;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprConstructor) {
        return v.value0;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprAccessor) {
        return v.value0;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprUpdate) {
        return v.value0;
    };
    throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 100, column 14 - line 109, column 28): " + [ v.constructor.name ]);
};
var inferExprType = function (expr) {
    var v = getExprAnn(expr);
    return v.type;
};
var getBindIdents = /* #__PURE__ */ Data_Array.concatMap(function (v) {
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.NonRec) {
        return [ v.value0.value1 ];
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.Rec) {
        return map(function (v1) {
            return v1.value1;
        })(v.value0);
    };
    throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 351, column 33 - line 353, column 51): " + [ v.constructor.name ]);
});
var extractFuncType = function ($copy_v) {
    var $tco_done = false;
    var $tco_result;
    function $tco_loop(v) {
        if (v instanceof PureScript_Backend_Optimizer_CoreFn.Func) {
            $tco_done = true;
            return new Data_Maybe.Just({
                fArgs: v.value0,
                fRet: v.value1
            });
        };
        if (v instanceof PureScript_Backend_Optimizer_CoreFn.ForAll) {
            $copy_v = v.value1;
            return;
        };
        if (v instanceof PureScript_Backend_Optimizer_CoreFn.ConstrainedType) {
            $copy_v = v.value1;
            return;
        };
        $tco_done = true;
        return Data_Maybe.Nothing.value;
    };
    while (!$tco_done) {
        $tco_result = $tco_loop($copy_v);
    };
    return $tco_result;
};
var defaultToAny = function (v) {
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.TypeVar) {
        return PureScript_Backend_Optimizer_CoreFn.Any.value;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn["Array"]) {
        return new PureScript_Backend_Optimizer_CoreFn["Array"](defaultToAny(v.value0));
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.Func) {
        return new PureScript_Backend_Optimizer_CoreFn.Func(map(defaultToAny)(v.value0), defaultToAny(v.value1));
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.Record) {
        return new PureScript_Backend_Optimizer_CoreFn.Record(defaultToAny(v.value0));
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.Row) {
        return new PureScript_Backend_Optimizer_CoreFn.Row(map(function (v1) {
            return new Data_Tuple.Tuple(v1.value0, defaultToAny(v1.value1));
        })(v.value0), map2(defaultToAny)(v.value1));
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.TypeApp) {
        return new PureScript_Backend_Optimizer_CoreFn.TypeApp(defaultToAny(v.value0), map(defaultToAny)(v.value1));
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ForAll) {
        return new PureScript_Backend_Optimizer_CoreFn.ForAll(v.value0, defaultToAny(v.value1));
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ConstrainedType) {
        return new PureScript_Backend_Optimizer_CoreFn.ConstrainedType(map(function (v1) {
            return new Data_Tuple.Tuple(v1.value0, map(defaultToAny)(v1.value1));
        })(v.value0), defaultToAny(v.value1));
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ADT) {
        return new PureScript_Backend_Optimizer_CoreFn.ADT(v.value0, v.value1, map(defaultToAny)(v.value2));
    };
    return v;
};
var collectTypesFromExpr = function (expr) {
    return function (acc) {
        if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprVar) {
            return Data_Maybe.maybe(acc)(function (t) {
                return insert(t)(acc);
            })(expr.value0.type);
        };
        if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprLit) {
            return foldl(function (a) {
                return function (e) {
                    return collectTypesFromExpr(e)(a);
                };
            })(Data_Maybe.maybe(acc)(function (t) {
                return insert(t)(acc);
            })(expr.value0.type))(expr.value1);
        };
        if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprApp) {
            return collectTypesFromExpr(expr.value2)(collectTypesFromExpr(expr.value1)(Data_Maybe.maybe(acc)(function (t) {
                return insert(t)(acc);
            })(expr.value0.type)));
        };
        if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprAbs) {
            return collectTypesFromExpr(expr.value2)(Data_Maybe.maybe(acc)(function (t) {
                return insert(t)(acc);
            })(expr.value0.type));
        };
        if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprLet) {
            return foldl1(function (a) {
                return function (b) {
                    return collectTypesFromBind(b)(a);
                };
            })(collectTypesFromExpr(expr.value2)(Data_Maybe.maybe(acc)(function (t) {
                return insert(t)(acc);
            })(expr.value0.type)))(expr.value1);
        };
        if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprCase) {
            return foldl1(function (a) {
                return function (alt) {
                    return collectTypesFromAlt(alt)(a);
                };
            })(foldl1(Data_Function.flip(collectTypesFromExpr))(Data_Maybe.maybe(acc)(function (t) {
                return insert(t)(acc);
            })(expr.value0.type))(expr.value1))(expr.value2);
        };
        if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprConstructor) {
            return Data_Maybe.maybe(acc)(function (t) {
                return insert(t)(acc);
            })(expr.value0.type);
        };
        if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprAccessor) {
            return collectTypesFromExpr(expr.value1)(Data_Maybe.maybe(acc)(function (t) {
                return insert(t)(acc);
            })(expr.value0.type));
        };
        if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprUpdate) {
            return foldl1(function (a) {
                return function (v) {
                    return collectTypesFromExpr(v.value1)(a);
                };
            })(collectTypesFromExpr(expr.value1)(Data_Maybe.maybe(acc)(function (t) {
                return insert(t)(acc);
            })(expr.value0.type)))(expr.value2);
        };
        throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 219, column 33 - line 228, column 161): " + [ expr.constructor.name ]);
    };
};
var collectTypesFromBind = function (v) {
    return function (v1) {
        if (v instanceof PureScript_Backend_Optimizer_CoreFn.NonRec) {
            return collectTypesFromExpr(v.value0.value2)(v1);
        };
        if (v instanceof PureScript_Backend_Optimizer_CoreFn.Rec) {
            return foldl1(function (a) {
                return function (v2) {
                    return collectTypesFromExpr(v2.value2)(a);
                };
            })(v1)(v.value0);
        };
        throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 230, column 1 - line 230, column 65): " + [ v.constructor.name, v1.constructor.name ]);
    };
};
var collectTypesFromAlt = function (v) {
    return function (v1) {
        if (v.value1 instanceof PureScript_Backend_Optimizer_CoreFn.Unconditional) {
            return collectTypesFromExpr(v.value1.value0)(v1);
        };
        if (v.value1 instanceof PureScript_Backend_Optimizer_CoreFn.Guarded) {
            return foldl1(function (a) {
                return function (v2) {
                    return collectTypesFromExpr(v2.value1)(collectTypesFromExpr(v2.value0)(a));
                };
            })(v1)(v.value1.value0);
        };
        throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 234, column 1 - line 234, column 75): " + [ v.constructor.name, v1.constructor.name ]);
    };
};
var collectAppSpine = /* #__PURE__ */ (function () {
    var go = function ($copy_v) {
        return function ($copy_v1) {
            var $tco_var_v = $copy_v;
            var $tco_done = false;
            var $tco_result;
            function $tco_loop(v, v1) {
                if (v1 instanceof PureScript_Backend_Optimizer_CoreFn.ExprApp) {
                    $tco_var_v = Data_Array.cons(v1.value2)(v);
                    $copy_v1 = v1.value1;
                    return;
                };
                $tco_done = true;
                return {
                    f: v1,
                    args: v
                };
            };
            while (!$tco_done) {
                $tco_result = $tco_loop($tco_var_v, $copy_v1);
            };
            return $tco_result;
        };
    };
    return go([  ]);
})();
var monomorphizeProp = function (modName) {
    return function (instMap) {
        return function (localDicts) {
            return function (v) {
                return new PureScript_Backend_Optimizer_CoreFn.Prop(v.value0, monomorphizeExpr(modName)(instMap)(localDicts)(v.value1));
            };
        };
    };
};
var monomorphizeGuard = function (modName) {
    return function (instMap) {
        return function (localDicts) {
            return function (v) {
                return new PureScript_Backend_Optimizer_CoreFn.Guard(monomorphizeExpr(modName)(instMap)(localDicts)(v.value0), monomorphizeExpr(modName)(instMap)(localDicts)(v.value1));
            };
        };
    };
};
var monomorphizeExpr = function (modName) {
    return function (instMap) {
        return function (localDicts) {
            return function (expr) {
                if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprVar) {
                    if (expr.value1.value0 instanceof Data_Maybe.Nothing) {
                        var v = lookup(expr.value1.value1)(localDicts);
                        if (v instanceof Data_Maybe.Just) {
                            return v.value0;
                        };
                        if (v instanceof Data_Maybe.Nothing) {
                            return new PureScript_Backend_Optimizer_CoreFn.ExprVar(expr.value0, expr.value1);
                        };
                        throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 465, column 18 - line 467, column 37): " + [ v.constructor.name ]);
                    };
                    return new PureScript_Backend_Optimizer_CoreFn.ExprVar(expr.value0, expr.value1);
                };
                if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprApp) {
                    var v = collectAppSpine(expr);
                    var f$prime = monomorphizeExpr(modName)(instMap)(localDicts)(v.f);
                    var args$prime = map(monomorphizeExpr(modName)(instMap)(localDicts))(v.args);
                    if (f$prime instanceof PureScript_Backend_Optimizer_CoreFn.ExprVar) {
                        var v1 = bind(f$prime.value0.type)(extractFuncType);
                        if (v1 instanceof Data_Maybe.Just) {
                            var genericType = Data_Maybe.fromMaybe(PureScript_Backend_Optimizer_CoreFn.Any.value)(f$prime.value0.type);
                            var v2 = partitionArgs(genericType)(args$prime);
                            var qualName = (function () {
                                if (f$prime.value1.value0 instanceof Data_Maybe.Just) {
                                    return unwrap(f$prime.value1.value0.value0) + ("." + f$prime.value1.value1);
                                };
                                if (f$prime.value1.value0 instanceof Data_Maybe.Nothing) {
                                    return modName + ("." + f$prime.value1.value1);
                                };
                                throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 495, column 26 - line 497, column 50): " + [ f$prime.value1.value0.constructor.name ]);
                            })();
                            var isFullyApplied = Data_Array.length(v2.normalArgs) >= Data_Array.length(v1.value0.fArgs);
                            var filteredArgs = append1(Data_Array.filter(function (d) {
                                return !isStatic(d);
                            })(v2.dictArgs))(v2.normalArgs);
                            var argTypes = Data_Array.mapMaybe(inferExprType)(v2.normalArgs);
                            var substArgs = Data_Array.foldl(function (substAcc) {
                                return function (v3) {
                                    return PureScript_Backend_Optimizer_Substitute.unify(v3.value0)(v3.value1)(substAcc);
                                };
                            })(Data_Map_Internal.empty)(Data_Array.zip(v1.value0.fArgs)(argTypes));
                            var subst = (function () {
                                if (expr.value0.type instanceof Data_Maybe.Just) {
                                    var remainingType = (function () {
                                        var $428 = Data_Array.length(v2.normalArgs) < Data_Array.length(v1.value0.fArgs);
                                        if ($428) {
                                            return new PureScript_Backend_Optimizer_CoreFn.Func(Data_Array.drop(Data_Array.length(v2.normalArgs))(v1.value0.fArgs), v1.value0.fRet);
                                        };
                                        return v1.value0.fRet;
                                    })();
                                    return PureScript_Backend_Optimizer_Substitute.unify(remainingType)(expr.value0.type.value0)(substArgs);
                                };
                                if (expr.value0.type instanceof Data_Maybe.Nothing) {
                                    return substArgs;
                                };
                                throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 485, column 23 - line 491, column 37): " + [ expr.value0.type.constructor.name ]);
                            })();
                            var instType = PureScript_Backend_Optimizer_Substitute.substituteExprType(subst)(genericType);
                            var substFn = function (t) {
                                return stripStaticConstraints(v2.dictArgs)(PureScript_Backend_Optimizer_Substitute.substituteExprType(subst)(t));
                            };
                            var allDictsStatic = Data_Array.all(isStatic)(v2.dictArgs);
                            var $430 = Data_Map_Internal.isEmpty(subst) || hasTypeVariables(instType);
                            if ($430) {
                                return rebuildApp(expr.value0)(f$prime)(args$prime);
                            };
                            var specializedName = f$prime.value1.value1 + ("__" + PureScript_Backend_Optimizer_FfiSupport.hashString(mangleType(defaultToAny(instType))));
                            var v3 = lookup1(qualName)(instMap);
                            if (v3 instanceof Data_Maybe.Just) {
                                var newAnn = {
                                    meta: f$prime.value0.meta,
                                    span: f$prime.value0.span,
                                    type: map2(function (t) {
                                        return stripTypeVariables(substFn(t));
                                    })(f$prime.value0.type)
                                };
                                var definerMod = (function () {
                                    var v4 = Data_String_Common.split(".")(qualName);
                                    return Data_String_Common.joinWith(".")(Data_Maybe.fromMaybe([  ])(Data_Array.init(v4)));
                                })();
                                var resolvedMod = new Data_Maybe.Just(definerMod);
                                var specializedVar = new PureScript_Backend_Optimizer_CoreFn.ExprVar(newAnn, new PureScript_Backend_Optimizer_CoreFn.Qualified(resolvedMod, specializedName));
                                return rebuildApp(expr.value0)(specializedVar)(filteredArgs);
                            };
                            if (v3 instanceof Data_Maybe.Nothing) {
                                return rebuildApp(expr.value0)(f$prime)(args$prime);
                            };
                            throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 507, column 23 - line 516, column 48): " + [ v3.constructor.name ]);
                        };
                        return rebuildApp(expr.value0)(f$prime)(args$prime);
                    };
                    return rebuildApp(expr.value0)(f$prime)(args$prime);
                };
                if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprLit) {
                    return new PureScript_Backend_Optimizer_CoreFn.ExprLit(expr.value0, map1(monomorphizeExpr(modName)(instMap)(localDicts))(expr.value1));
                };
                if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprAbs) {
                    return new PureScript_Backend_Optimizer_CoreFn.ExprAbs(expr.value0, expr.value1, monomorphizeExpr(modName)(instMap)(localDicts)(expr.value2));
                };
                if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprLet) {
                    var newLocalDicts = Data_Array.foldl(function (acc) {
                        return function (b) {
                            if (b instanceof PureScript_Backend_Optimizer_CoreFn.NonRec && isStatic(b.value0.value2)) {
                                return insert1(b.value0.value1)(b.value0.value2)(acc);
                            };
                            return acc;
                        };
                    })(localDicts)(expr.value1);
                    return new PureScript_Backend_Optimizer_CoreFn.ExprLet(expr.value0, map(monomorphizeBindLocal(modName)(instMap)(newLocalDicts))(expr.value1), monomorphizeExpr(modName)(instMap)(newLocalDicts)(expr.value2));
                };
                if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprCase) {
                    return new PureScript_Backend_Optimizer_CoreFn.ExprCase(expr.value0, map(monomorphizeExpr(modName)(instMap)(localDicts))(expr.value1), map(monomorphizeAlt(modName)(instMap)(localDicts))(expr.value2));
                };
                if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprConstructor) {
                    return new PureScript_Backend_Optimizer_CoreFn.ExprConstructor(expr.value0, expr.value1, expr.value2, expr.value3);
                };
                if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprAccessor) {
                    return new PureScript_Backend_Optimizer_CoreFn.ExprAccessor(expr.value0, monomorphizeExpr(modName)(instMap)(localDicts)(expr.value1), expr.value2);
                };
                if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprUpdate) {
                    return new PureScript_Backend_Optimizer_CoreFn.ExprUpdate(expr.value0, monomorphizeExpr(modName)(instMap)(localDicts)(expr.value1), map(monomorphizeProp(modName)(instMap)(localDicts))(expr.value2));
                };
                throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 462, column 52 - line 530, column 149): " + [ expr.constructor.name ]);
            };
        };
    };
};
var monomorphizeCaseGuard = function (v) {
    return function (v1) {
        return function (v2) {
            return function (v3) {
                if (v3 instanceof PureScript_Backend_Optimizer_CoreFn.Unconditional) {
                    return new PureScript_Backend_Optimizer_CoreFn.Unconditional(monomorphizeExpr(v)(v1)(v2)(v3.value0));
                };
                if (v3 instanceof PureScript_Backend_Optimizer_CoreFn.Guarded) {
                    return new PureScript_Backend_Optimizer_CoreFn.Guarded(map(monomorphizeGuard(v)(v1)(v2))(v3.value0));
                };
                throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 542, column 1 - line 542, column 110): " + [ v.constructor.name, v1.constructor.name, v2.constructor.name, v3.constructor.name ]);
            };
        };
    };
};
var monomorphizeBindingLocal = function (modName) {
    return function (instMap) {
        return function (localDicts) {
            return function (v) {
                return new PureScript_Backend_Optimizer_CoreFn.Binding(v.value0, v.value1, monomorphizeExpr(modName)(instMap)(localDicts)(v.value2));
            };
        };
    };
};
var monomorphizeBindLocal = function (v) {
    return function (v1) {
        return function (v2) {
            return function (v3) {
                if (v3 instanceof PureScript_Backend_Optimizer_CoreFn.NonRec) {
                    return new PureScript_Backend_Optimizer_CoreFn.NonRec(monomorphizeBindingLocal(v)(v1)(v2)(v3.value0));
                };
                if (v3 instanceof PureScript_Backend_Optimizer_CoreFn.Rec) {
                    return new PureScript_Backend_Optimizer_CoreFn.Rec(map(monomorphizeBindingLocal(v)(v1)(v2))(v3.value0));
                };
                throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 532, column 1 - line 532, column 100): " + [ v.constructor.name, v1.constructor.name, v2.constructor.name, v3.constructor.name ]);
            };
        };
    };
};
var monomorphizeAlt = function (modName) {
    return function (instMap) {
        return function (localDicts) {
            return function (v) {
                return new PureScript_Backend_Optimizer_CoreFn.CaseAlternative(v.value0, monomorphizeCaseGuard(modName)(instMap)(localDicts)(v.value1));
            };
        };
    };
};
var monomorphizeBinding = function (modName) {
    return function (instMap) {
        return function (localDicts) {
            return function (v) {
                return new PureScript_Backend_Optimizer_CoreFn.Binding(v.value0, v.value1, monomorphizeExpr(modName)(instMap)(localDicts)(v.value2));
            };
        };
    };
};
var monomorphizeBind = function (v) {
    return function (v1) {
        return function (v2) {
            return function (v3) {
                if (v3 instanceof PureScript_Backend_Optimizer_CoreFn.NonRec) {
                    return [ new PureScript_Backend_Optimizer_CoreFn.NonRec(monomorphizeBinding(v)(v1)(v2)(v3.value0)) ];
                };
                if (v3 instanceof PureScript_Backend_Optimizer_CoreFn.Rec) {
                    return [ new PureScript_Backend_Optimizer_CoreFn.Rec(map(monomorphizeBinding(v)(v1)(v2))(v3.value0)) ];
                };
                throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 420, column 1 - line 420, column 103): " + [ v.constructor.name, v1.constructor.name, v2.constructor.name, v3.constructor.name ]);
            };
        };
    };
};
var collectProp = function (modName) {
    return function (acc) {
        return function (v) {
            return collectExpr(modName)(acc)(v.value1);
        };
    };
};
var collectGuard = function (modName) {
    return function (acc) {
        return function (v) {
            return collectExpr(modName)(collectExpr(modName)(acc)(v.value0))(v.value1);
        };
    };
};
var collectExpr = function (modName) {
    return function (acc) {
        return function (expr) {
            if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprVar) {
                if (expr.value0.type instanceof Data_Maybe.Just) {
                    var qualName = (function () {
                        if (expr.value1.value0 instanceof Data_Maybe.Just) {
                            return unwrap(expr.value1.value0.value0) + ("." + expr.value1.value1);
                        };
                        if (expr.value1.value0 instanceof Data_Maybe.Nothing) {
                            return modName + ("." + expr.value1.value1);
                        };
                        throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 155, column 24 - line 157, column 48): " + [ expr.value1.value0.constructor.name ]);
                    })();
                    return insertWith(function ($$new) {
                        return function (old) {
                            return unionWith(function (a) {
                                return function (b) {
                                    return {
                                        dictArgs: a.dictArgs,
                                        callers: union(a.callers)(b.callers)
                                    };
                                };
                            })($$new)(old);
                        };
                    })(qualName)(Data_Map_Internal.singleton(defaultToAny(expr.value0.type.value0))({
                        dictArgs: [  ],
                        callers: Data_Set.singleton(modName)
                    }))(acc);
                };
                if (expr.value0.type instanceof Data_Maybe.Nothing) {
                    return acc;
                };
                throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 153, column 5 - line 159, column 21): " + [ expr.value0.type.constructor.name ]);
            };
            if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprApp) {
                var v = collectAppSpine(expr);
                var acc1 = collectExpr(modName)(acc)(v.f);
                var acc2 = foldl1(collectExpr(modName))(acc1)(v.args);
                if (v.f instanceof PureScript_Backend_Optimizer_CoreFn.ExprVar) {
                    var v1 = bind(v.f.value0.type)(extractFuncType);
                    if (v1 instanceof Data_Maybe.Just) {
                        var genericType = Data_Maybe.fromMaybe(PureScript_Backend_Optimizer_CoreFn.Any.value)(v.f.value0.type);
                        var v2 = partitionArgs(genericType)(v.args);
                        var qualName = (function () {
                            if (v.f.value1.value0 instanceof Data_Maybe.Just) {
                                return unwrap(v.f.value1.value0.value0) + ("." + v.f.value1.value1);
                            };
                            if (v.f.value1.value0 instanceof Data_Maybe.Nothing) {
                                return modName + ("." + v.f.value1.value1);
                            };
                            throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 185, column 26 - line 187, column 50): " + [ v.f.value1.value0.constructor.name ]);
                        })();
                        var argTypes = Data_Array.mapMaybe(inferExprType)(v2.normalArgs);
                        var substArgs = Data_Array.foldl(function (substAcc) {
                            return function (v3) {
                                return PureScript_Backend_Optimizer_Substitute.unify(v3.value0)(v3.value1)(substAcc);
                            };
                        })(Data_Map_Internal.empty)(Data_Array.zip(v1.value0.fArgs)(argTypes));
                        var appType = (function () {
                            var v3 = getExprAnn(expr);
                            return v3.type;
                        })();
                        var subst = (function () {
                            if (appType instanceof Data_Maybe.Just) {
                                var remainingType = (function () {
                                    var $542 = Data_Array.length(v2.normalArgs) < Data_Array.length(v1.value0.fArgs);
                                    if ($542) {
                                        return new PureScript_Backend_Optimizer_CoreFn.Func(Data_Array.drop(Data_Array.length(v2.normalArgs))(v1.value0.fArgs), v1.value0.fRet);
                                    };
                                    return v1.value0.fRet;
                                })();
                                return PureScript_Backend_Optimizer_Substitute.unify(remainingType)(appType.value0)(substArgs);
                            };
                            if (appType instanceof Data_Maybe.Nothing) {
                                return substArgs;
                            };
                            throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 176, column 23 - line 182, column 37): " + [ appType.constructor.name ]);
                        })();
                        var instType = PureScript_Backend_Optimizer_Substitute.substituteExprType(subst)(genericType);
                        var $544 = qualName === "Data.Functor.map";
                        if ($544) {
                            return insertWith(function ($$new) {
                                return function (old) {
                                    return unionWith(function (a) {
                                        return function (b) {
                                            return {
                                                dictArgs: a.dictArgs,
                                                callers: union(a.callers)(b.callers)
                                            };
                                        };
                                    })($$new)(old);
                                };
                            })(qualName)(Data_Map_Internal.singleton(defaultToAny(instType))({
                                dictArgs: v2.dictArgs,
                                callers: Data_Set.singleton(modName)
                            }))(acc2);
                        };
                        var $545 = Data_Map_Internal.isEmpty(subst);
                        if ($545) {
                            return acc2;
                        };
                        return insertWith(function ($$new) {
                            return function (old) {
                                return unionWith(function (a) {
                                    return function (b) {
                                        return {
                                            dictArgs: a.dictArgs,
                                            callers: union(a.callers)(b.callers)
                                        };
                                    };
                                })($$new)(old);
                            };
                        })(qualName)(Data_Map_Internal.singleton(defaultToAny(instType))({
                            dictArgs: v2.dictArgs,
                            callers: Data_Set.singleton(modName)
                        }))(acc2);
                    };
                    return acc2;
                };
                return acc2;
            };
            if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprLit) {
                return foldl(collectExpr(modName))(acc)(expr.value1);
            };
            if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprConstructor) {
                return acc;
            };
            if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprAccessor) {
                return collectExpr(modName)(acc)(expr.value1);
            };
            if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprUpdate) {
                return foldl1(collectProp(modName))(collectExpr(modName)(acc)(expr.value1))(expr.value2);
            };
            if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprAbs) {
                return collectExpr(modName)(acc)(expr.value2);
            };
            if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprCase) {
                return foldl1(collectAlt(modName))(foldl1(collectExpr(modName))(acc)(expr.value1))(expr.value2);
            };
            if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprLet) {
                return foldl1(collectBind(modName))(collectExpr(modName)(acc)(expr.value2))(expr.value1);
            };
            throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 151, column 32 - line 202, column 85): " + [ expr.constructor.name ]);
        };
    };
};
var collectBinding = function (modName) {
    return function (acc) {
        return function (v) {
            return collectExpr(modName)(acc)(v.value2);
        };
    };
};
var collectBind = function (v) {
    return function (v1) {
        return function (v2) {
            if (v2 instanceof PureScript_Backend_Optimizer_CoreFn.NonRec) {
                return collectBinding(v)(v1)(v2.value0);
            };
            if (v2 instanceof PureScript_Backend_Optimizer_CoreFn.Rec) {
                return foldl1(collectBinding(v))(v1)(v2.value0);
            };
            throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 92, column 1 - line 92, column 74): " + [ v.constructor.name, v1.constructor.name, v2.constructor.name ]);
        };
    };
};
var collectAlt = function (modName) {
    return function (acc) {
        return function (v) {
            if (v.value1 instanceof PureScript_Backend_Optimizer_CoreFn.Unconditional) {
                return collectExpr(modName)(acc)(v.value1.value0);
            };
            if (v.value1 instanceof PureScript_Backend_Optimizer_CoreFn.Guarded) {
                return foldl1(collectGuard(modName))(acc)(v.value1.value0);
            };
            throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 208, column 49 - line 210, column 60): " + [ v.value1.constructor.name ]);
        };
    };
};
var collectInstantiations = function (acc) {
    return function (v) {
        var modNameStr = unwrap(v.name);
        return foldl1(collectBind(modNameStr))(acc)(v.decls);
    };
};
var collectAllTypes = function (v) {
    return foldl1(function (a) {
        return function (b) {
            return collectTypesFromBind(b)(a);
        };
    })(Data_Set.empty)(v.decls);
};
var binderIdents = function (v) {
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.BinderVar) {
        return Data_Set.singleton(v.value1);
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.BinderConstructor) {
        return foldl1(function (acc) {
            return function (b) {
                return union1(binderIdents(b))(acc);
            };
        })(Data_Set.empty)(v.value3);
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.BinderNamed) {
        return insert2(v.value1)(binderIdents(v.value2));
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.BinderLit) {
        return foldl(function (acc) {
            return function (b) {
                return union1(binderIdents(b))(acc);
            };
        })(Data_Set.empty)(v.value1);
    };
    return Data_Set.empty;
};
var collectFreeVarsAlt = function (v) {
    var used = (function () {
        if (v.value1 instanceof PureScript_Backend_Optimizer_CoreFn.Unconditional) {
            return collectFreeVars(v.value1.value0);
        };
        if (v.value1 instanceof PureScript_Backend_Optimizer_CoreFn.Guarded) {
            return foldl1(function (acc) {
                return function (v1) {
                    return union1(acc)(union1(collectFreeVars(v1.value0))(collectFreeVars(v1.value1)));
                };
            })(Data_Set.empty)(v.value1.value0);
        };
        throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 456, column 12 - line 458, column 135): " + [ v.value1.constructor.name ]);
    })();
    var bound = foldl1(function (acc) {
        return function (binder) {
            return union1(acc)(binderIdents(binder));
        };
    })(Data_Set.empty)(v.value0);
    return difference(used)(bound);
};
var collectFreeVars = function (v) {
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprVar && v.value1.value0 instanceof Data_Maybe.Nothing) {
        return Data_Set.singleton(v.value1.value1);
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprVar) {
        return Data_Set.empty;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprLit) {
        return foldl(function (acc) {
            return function (e) {
                return union1(acc)(collectFreeVars(e));
            };
        })(Data_Set.empty)(v.value1);
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprApp) {
        return union1(collectFreeVars(v.value1))(collectFreeVars(v.value2));
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprAbs) {
        return $$delete(v.value1)(collectFreeVars(v.value2));
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprLet) {
        var used = foldl1(function (acc) {
            return function (b) {
                if (b instanceof PureScript_Backend_Optimizer_CoreFn.NonRec) {
                    return union1(acc)(collectFreeVars(b.value0.value2));
                };
                if (b instanceof PureScript_Backend_Optimizer_CoreFn.Rec) {
                    return foldl1(function (a) {
                        return function (v1) {
                            return union1(a)(collectFreeVars(v1.value2));
                        };
                    })(acc)(b.value0);
                };
                throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 442, column 31 - line 444, column 91): " + [ b.constructor.name ]);
            };
        })(collectFreeVars(v.value2))(v.value1);
        var bound = foldl1(function (acc) {
            return function (b) {
                if (b instanceof PureScript_Backend_Optimizer_CoreFn.NonRec) {
                    return insert2(b.value0.value1)(acc);
                };
                if (b instanceof PureScript_Backend_Optimizer_CoreFn.Rec) {
                    return foldl1(function (a) {
                        return function (v1) {
                            return insert2(v1.value1)(a);
                        };
                    })(acc)(b.value0);
                };
                throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 439, column 32 - line 441, column 78): " + [ b.constructor.name ]);
            };
        })(Data_Set.empty)(v.value1);
        return difference(used)(bound);
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprCase) {
        return foldl1(function (acc) {
            return function (alt) {
                return union1(acc)(collectFreeVarsAlt(alt));
            };
        })(foldl1(function (acc) {
            return function (e) {
                return union1(acc)(collectFreeVars(e));
            };
        })(Data_Set.empty)(v.value1))(v.value2);
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprConstructor) {
        return Data_Set.empty;
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprAccessor) {
        return collectFreeVars(v.value1);
    };
    if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprUpdate) {
        return foldl1(function (acc) {
            return function (v1) {
                return union1(acc)(collectFreeVars(v1.value1));
            };
        })(collectFreeVars(v.value1))(v.value2);
    };
    throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 431, column 19 - line 450, column 117): " + [ v.constructor.name ]);
};
var rewriteExpr = function (globalAstMap) {
    var goLocals = function (locals) {
        return function (f) {
            var resolveDict = function ($copy_e) {
                var $tco_done = false;
                var $tco_result;
                function $tco_loop(e) {
                    if (e instanceof PureScript_Backend_Optimizer_CoreFn.ExprLit && e.value1 instanceof PureScript_Backend_Optimizer_CoreFn.LitRecord) {
                        $tco_done = true;
                        return new Data_Maybe.Just(e.value1);
                    };
                    if (e instanceof PureScript_Backend_Optimizer_CoreFn.ExprApp && e.value1 instanceof PureScript_Backend_Optimizer_CoreFn.ExprConstructor) {
                        $copy_e = e.value2;
                        return;
                    };
                    if (e instanceof PureScript_Backend_Optimizer_CoreFn.ExprVar) {
                        if (e.value1.value0 instanceof Data_Maybe.Nothing) {
                            var v = lookup(e.value1.value1)(locals);
                            if (v instanceof Data_Maybe.Just) {
                                $copy_e = v.value0;
                                return;
                            };
                            if (v instanceof Data_Maybe.Nothing) {
                                $tco_done = true;
                                return Data_Maybe.Nothing.value;
                            };
                            throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 306, column 22 - line 308, column 31): " + [ v.constructor.name ]);
                        };
                        if (e.value1.value0 instanceof Data_Maybe.Just) {
                            var fullName = e.value1.value0.value0 + ("." + (function (v) {
                                return v;
                            })(e.value1.value1));
                            var v = lookup1(fullName)(globalAstMap);
                            if (v instanceof Data_Maybe.Just) {
                                $copy_e = v.value0.value2;
                                return;
                            };
                            if (v instanceof Data_Maybe.Nothing) {
                                $tco_done = true;
                                return Data_Maybe.Nothing.value;
                            };
                            throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 311, column 16 - line 313, column 33): " + [ v.constructor.name ]);
                        };
                        throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 305, column 9 - line 313, column 33): " + [ e.value1.value0.constructor.name ]);
                    };
                    if (e instanceof PureScript_Backend_Optimizer_CoreFn.ExprApp && (e.value1 instanceof PureScript_Backend_Optimizer_CoreFn.ExprVar && Data_String_CodeUnits.contains("$Dict")(e.value1.value1.value1))) {
                        $copy_e = e.value2;
                        return;
                    };
                    $tco_done = true;
                    return Data_Maybe.Nothing.value;
                };
                while (!$tco_done) {
                    $tco_result = $tco_loop($copy_e);
                };
                return $tco_result;
            };
            var goBinder = function (binder) {
                return map3(mapAnn(f))(binder);
            };
            var goProp = function (v) {
                return new PureScript_Backend_Optimizer_CoreFn.Prop(v.value0, go(v.value1));
            };
            var goGuard = function (v) {
                return new PureScript_Backend_Optimizer_CoreFn.Guard(go(v.value0), go(v.value1));
            };
            var goCaseGuard = function (v) {
                if (v instanceof PureScript_Backend_Optimizer_CoreFn.Unconditional) {
                    return new PureScript_Backend_Optimizer_CoreFn.Unconditional(go(v.value0));
                };
                if (v instanceof PureScript_Backend_Optimizer_CoreFn.Guarded) {
                    return new PureScript_Backend_Optimizer_CoreFn.Guarded(map(goGuard)(v.value0));
                };
                throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 326, column 5 - line 326, column 57): " + [ v.constructor.name ]);
            };
            var goBinding = function (v) {
                return new PureScript_Backend_Optimizer_CoreFn.Binding(mapAnn(f)(v.value0), v.value1, go(v.value2));
            };
            var goBind = function (v) {
                if (v instanceof PureScript_Backend_Optimizer_CoreFn.NonRec) {
                    return new PureScript_Backend_Optimizer_CoreFn.NonRec(goBinding(v.value0));
                };
                if (v instanceof PureScript_Backend_Optimizer_CoreFn.Rec) {
                    return new PureScript_Backend_Optimizer_CoreFn.Rec(map(goBinding)(v.value0));
                };
                throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 317, column 5 - line 317, column 45): " + [ v.constructor.name ]);
            };
            var goAlt = function (v) {
                return new PureScript_Backend_Optimizer_CoreFn.CaseAlternative(map(goBinder)(v.value0), goCaseGuard(v.value1));
            };
            var go = function (expr) {
                if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprVar) {
                    return new PureScript_Backend_Optimizer_CoreFn.ExprVar(mapAnn(f)(expr.value0), expr.value1);
                };
                if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprLit) {
                    return new PureScript_Backend_Optimizer_CoreFn.ExprLit(mapAnn(f)(expr.value0), map1(go)(expr.value1));
                };
                if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprApp) {
                    return new PureScript_Backend_Optimizer_CoreFn.ExprApp(mapAnn(f)(expr.value0), go(expr.value1), go(expr.value2));
                };
                if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprAbs) {
                    return new PureScript_Backend_Optimizer_CoreFn.ExprAbs(mapAnn(f)(expr.value0), expr.value1, goLocals(delete1(expr.value1)(locals))(f)(expr.value2));
                };
                if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprLet) {
                    var foldFn = function (b) {
                        return function (acc) {
                            if (b instanceof PureScript_Backend_Optimizer_CoreFn.NonRec) {
                                var $741 = member(b.value0.value1)(acc.used);
                                if ($741) {
                                    return {
                                        used: union1($$delete(b.value0.value1)(acc.used))(collectFreeVars(b.value0.value2)),
                                        binds: Data_Array.cons(b)(acc.binds)
                                    };
                                };
                                return acc;
                            };
                            if (b instanceof PureScript_Backend_Optimizer_CoreFn.Rec) {
                                var isUsed = Data_Array.any(function (v) {
                                    return member(v.value1)(acc.used);
                                })(b.value0);
                                var bound = foldl1(function (a) {
                                    return function (v) {
                                        return insert2(v.value1)(a);
                                    };
                                })(Data_Set.empty)(b.value0);
                                if (isUsed) {
                                    var usedByRec = foldl1(function (a) {
                                        return function (v) {
                                            return union1(a)(collectFreeVars(v.value2));
                                        };
                                    })(acc.used)(b.value0);
                                    var newUsed = difference(usedByRec)(bound);
                                    return {
                                        used: newUsed,
                                        binds: Data_Array.cons(b)(acc.binds)
                                    };
                                };
                                return acc;
                            };
                            throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 259, column 26 - line 275, column 20): " + [ b.constructor.name ]);
                        };
                    };
                    var binds$prime = map(goBind)(expr.value1);
                    var newLocals = foldl1(function (acc) {
                        return function (b) {
                            if (b instanceof PureScript_Backend_Optimizer_CoreFn.NonRec) {
                                return insert1(b.value0.value1)(b.value0.value2)(acc);
                            };
                            return acc;
                        };
                    })(locals)(binds$prime);
                    var e$prime = goLocals(newLocals)(f)(expr.value2);
                    var filtered = Data_Array.foldr(foldFn)({
                        used: collectFreeVars(e$prime),
                        binds: [  ]
                    })(binds$prime);
                    var $765 = Data_Array.length(filtered.binds) === 0;
                    if ($765) {
                        return e$prime;
                    };
                    return new PureScript_Backend_Optimizer_CoreFn.ExprLet(mapAnn(f)(expr.value0), filtered.binds, e$prime);
                };
                if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprCase) {
                    var exprs$prime = map(go)(expr.value1);
                    if (exprs$prime.length === 1 && (expr.value2.length === 1 && (expr["value2"][0].value0.length === 1 && (expr["value2"][0]["value0"][0] instanceof PureScript_Backend_Optimizer_CoreFn.BinderConstructor && (expr["value2"][0]["value0"][0].value3.length === 1 && (expr["value2"][0]["value0"][0]["value3"][0] instanceof PureScript_Backend_Optimizer_CoreFn.BinderVar && expr["value2"][0].value1 instanceof PureScript_Backend_Optimizer_CoreFn.Unconditional)))))) {
                        var v = resolveDict(exprs$prime[0]);
                        if (v instanceof Data_Maybe.Just) {
                            return goLocals(insert1(expr["value2"][0]["value0"][0]["value3"][0].value1)(new PureScript_Backend_Optimizer_CoreFn.ExprLit(getExprAnn(exprs$prime[0]), v.value0))(locals))(f)(expr["value2"][0].value1.value0);
                        };
                        if (v instanceof Data_Maybe.Nothing) {
                            return new PureScript_Backend_Optimizer_CoreFn.ExprCase(mapAnn(f)(expr.value0), exprs$prime, map(goAlt)(expr.value2));
                        };
                        throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 283, column 14 - line 285, column 74): " + [ v.constructor.name ]);
                    };
                    return new PureScript_Backend_Optimizer_CoreFn.ExprCase(mapAnn(f)(expr.value0), exprs$prime, map(goAlt)(expr.value2));
                };
                if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprConstructor) {
                    return new PureScript_Backend_Optimizer_CoreFn.ExprConstructor(mapAnn(f)(expr.value0), expr.value1, expr.value2, expr.value3);
                };
                if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprAccessor) {
                    var e$prime = go(expr.value1);
                    var v = resolveDict(e$prime);
                    if (v instanceof Data_Maybe.Just && v.value0 instanceof PureScript_Backend_Optimizer_CoreFn.LitRecord) {
                        var v1 = Data_Array.find(function (v2) {
                            return v2.value0 === expr.value2;
                        })(v.value0.value0);
                        if (v1 instanceof Data_Maybe.Just) {
                            return go(v1.value0.value1);
                        };
                        if (v1 instanceof Data_Maybe.Nothing) {
                            return new PureScript_Backend_Optimizer_CoreFn.ExprAccessor(mapAnn(f)(expr.value0), e$prime, expr.value2);
                        };
                        throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 292, column 13 - line 294, column 61): " + [ v1.constructor.name ]);
                    };
                    if (v instanceof Data_Maybe.Just && v.value0 instanceof PureScript_Backend_Optimizer_CoreFn.LitArray) {
                        return new PureScript_Backend_Optimizer_CoreFn.ExprAccessor(mapAnn(f)(expr.value0), e$prime, expr.value2);
                    };
                    return new PureScript_Backend_Optimizer_CoreFn.ExprAccessor(mapAnn(f)(expr.value0), e$prime, expr.value2);
                };
                if (expr instanceof PureScript_Backend_Optimizer_CoreFn.ExprUpdate) {
                    return new PureScript_Backend_Optimizer_CoreFn.ExprUpdate(mapAnn(f)(expr.value0), go(expr.value1), map(goProp)(expr.value2));
                };
                throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 246, column 15 - line 298, column 84): " + [ expr.constructor.name ]);
            };
            return go;
        };
    };
    return goLocals;
};
var resolveGlobals = function (definerMod) {
    var go = function (bound) {
        return function (v) {
            if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprVar && v.value1.value0 instanceof Data_Maybe.Nothing) {
                var $812 = member(v.value1.value1)(bound);
                if ($812) {
                    return new PureScript_Backend_Optimizer_CoreFn.ExprVar(v.value0, new PureScript_Backend_Optimizer_CoreFn.Qualified(Data_Maybe.Nothing.value, v.value1.value1));
                };
                return new PureScript_Backend_Optimizer_CoreFn.ExprVar(v.value0, new PureScript_Backend_Optimizer_CoreFn.Qualified(new Data_Maybe.Just(definerMod), v.value1.value1));
            };
            if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprVar) {
                return new PureScript_Backend_Optimizer_CoreFn.ExprVar(v.value0, v.value1);
            };
            if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprAbs) {
                return new PureScript_Backend_Optimizer_CoreFn.ExprAbs(v.value0, v.value1, go(insert2(v.value1)(bound))(v.value2));
            };
            if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprApp) {
                return new PureScript_Backend_Optimizer_CoreFn.ExprApp(v.value0, go(bound)(v.value1), go(bound)(v.value2));
            };
            if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprLet) {
                var bound$prime = foldl1(function (acc) {
                    return function (v1) {
                        if (v1 instanceof PureScript_Backend_Optimizer_CoreFn.NonRec) {
                            return insert2(v1.value0.value1)(acc);
                        };
                        if (v1 instanceof PureScript_Backend_Optimizer_CoreFn.Rec) {
                            return foldl1(function (acc2) {
                                return function (v2) {
                                    return insert2(v2.value1)(acc2);
                                };
                            })(acc)(v1.value0);
                        };
                        throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 605, column 33 - line 607, column 86): " + [ v1.constructor.name ]);
                    };
                })(bound)(v.value1);
                var binds$prime = map(function (b) {
                    if (b instanceof PureScript_Backend_Optimizer_CoreFn.NonRec) {
                        return new PureScript_Backend_Optimizer_CoreFn.NonRec(new PureScript_Backend_Optimizer_CoreFn.Binding(b.value0.value0, b.value0.value1, go(bound$prime)(b.value0.value2)));
                    };
                    if (b instanceof PureScript_Backend_Optimizer_CoreFn.Rec) {
                        return new PureScript_Backend_Optimizer_CoreFn.Rec(map(function (v1) {
                            return new PureScript_Backend_Optimizer_CoreFn.Binding(v1.value0, v1.value1, go(bound$prime)(v1.value2));
                        })(b.value0));
                    };
                    throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 609, column 29 - line 611, column 101): " + [ b.constructor.name ]);
                })(v.value1);
                return new PureScript_Backend_Optimizer_CoreFn.ExprLet(v.value0, binds$prime, go(bound$prime)(v.value2));
            };
            if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprConstructor) {
                return new PureScript_Backend_Optimizer_CoreFn.ExprConstructor(v.value0, v.value1, v.value2, v.value3);
            };
            if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprCase) {
                return new PureScript_Backend_Optimizer_CoreFn.ExprCase(v.value0, map(go(bound))(v.value1), map(function (v1) {
                    var binders$prime = map(resolveGlobalsBinder(definerMod))(v1.value0);
                    var bound$prime = foldl1(function (acc) {
                        return function (binder) {
                            return union1(binderIdents(binder))(acc);
                        };
                    })(bound)(binders$prime);
                    var goGuard = function (cgGuard) {
                        if (cgGuard instanceof PureScript_Backend_Optimizer_CoreFn.Unconditional) {
                            return new PureScript_Backend_Optimizer_CoreFn.Unconditional(go(bound$prime)(cgGuard.value0));
                        };
                        if (cgGuard instanceof PureScript_Backend_Optimizer_CoreFn.Guarded) {
                            return new PureScript_Backend_Optimizer_CoreFn.Guarded(map(function (v2) {
                                return new PureScript_Backend_Optimizer_CoreFn.Guard(go(bound$prime)(v2.value0), go(bound$prime)(v2.value1));
                            })(cgGuard.value0));
                        };
                        throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 622, column 29 - line 624, column 103): " + [ cgGuard.constructor.name ]);
                    };
                    return new PureScript_Backend_Optimizer_CoreFn.CaseAlternative(binders$prime, goGuard(v1.value1));
                })(v.value2));
            };
            if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprAccessor) {
                return new PureScript_Backend_Optimizer_CoreFn.ExprAccessor(v.value0, go(bound)(v.value1), v.value2);
            };
            if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprUpdate) {
                return new PureScript_Backend_Optimizer_CoreFn.ExprUpdate(v.value0, go(bound)(v.value1), map(function (v1) {
                    return new PureScript_Backend_Optimizer_CoreFn.Prop(v1.value0, go(bound)(v1.value1));
                })(v.value2));
            };
            if (v instanceof PureScript_Backend_Optimizer_CoreFn.ExprLit) {
                return new PureScript_Backend_Optimizer_CoreFn.ExprLit(v.value0, map1(go(bound))(v.value1));
            };
            throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 592, column 14 - line 630, column 56): " + [ v.constructor.name ]);
        };
    };
    return go;
};
var applyDicts = function (args) {
    return function (body) {
        var go = function (dicts) {
            return function (e) {
                var v = Data_Array.uncons(dicts);
                if (v instanceof Data_Maybe.Nothing) {
                    return e;
                };
                if (v instanceof Data_Maybe.Just) {
                    var $876 = isStatic(v.value0.head);
                    if ($876) {
                        if (e instanceof PureScript_Backend_Optimizer_CoreFn.ExprAbs) {
                            var body$prime = go(v.value0.tail)(e.value2);
                            return new PureScript_Backend_Optimizer_CoreFn.ExprLet(getExprAnn(body$prime), [ new PureScript_Backend_Optimizer_CoreFn.NonRec(new PureScript_Backend_Optimizer_CoreFn.Binding(getExprAnn(v.value0.head), e.value1, v.value0.head)) ], body$prime);
                        };
                        return go(v.value0.tail)(new PureScript_Backend_Optimizer_CoreFn.ExprApp(getExprAnn(e), e, v.value0.head));
                    };
                    if (e instanceof PureScript_Backend_Optimizer_CoreFn.ExprAbs) {
                        return new PureScript_Backend_Optimizer_CoreFn.ExprAbs(e.value0, e.value1, go(v.value0.tail)(e.value2));
                    };
                    return go(v.value0.tail)(e);
                };
                throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 336, column 16 - line 348, column 24): " + [ v.constructor.name ]);
            };
        };
        return go(args)(body);
    };
};
var monomorphize = function (globalAstMap) {
    return function (instMap) {
        return function (v) {
            var v1 = trace("monomorphize module: " + unwrap(v.name))(function (v2) {
                return Data_Unit.unit;
            });
            var modNameStr = unwrap(v.name);
            var injectedBinds = Data_Array.concatMap(function (v2) {
                var processBinding = (function () {
                    var v3 = lookup1(v2.value0)(globalAstMap);
                    if (v3 instanceof Data_Maybe.Just) {
                        return Data_Array.mapMaybe(function (v4) {
                            var $894 = hasTypeVariables(v4.value0);
                            if ($894) {
                                return Data_Maybe.Nothing.value;
                            };
                            var definerMod = (function () {
                                var v5 = Data_String_Common.split(".")(v2.value0);
                                return Data_String_Common.joinWith(".")(Data_Maybe.fromMaybe([  ])(Data_Array.init(v5)));
                            })();
                            var $896 = modNameStr === definerMod;
                            if ($896) {
                                var newName = v3.value0.value1 + ("__" + PureScript_Backend_Optimizer_FfiSupport.hashString(mangleType(v4.value0)));
                                var genericType = (function () {
                                    var v5 = getExprAnn(v3.value0.value2);
                                    return Data_Maybe.fromMaybe(PureScript_Backend_Optimizer_CoreFn.Any.value)(v5.type);
                                })();
                                var subst = PureScript_Backend_Optimizer_Substitute.unify(genericType)(v4.value0)(Data_Map_Internal.empty);
                                var substFn = function (t) {
                                    return stripStaticConstraints(v4.value1.dictArgs)(PureScript_Backend_Optimizer_Substitute.substituteExprType(subst)(t));
                                };
                                var exprWithDicts = applyDicts(v4.value1.dictArgs)(v3.value0.value2);
                                var resolvedExpr = resolveGlobals(definerMod)(Data_Set.empty)(exprWithDicts);
                                var specializedExpr = rewriteExpr(globalAstMap)(Data_Map_Internal.empty)(substFn)(monomorphizeExpr(modNameStr)(instMap)(Data_Map_Internal.empty)(resolvedExpr));
                                var isAbs = (function () {
                                    if (specializedExpr instanceof PureScript_Backend_Optimizer_CoreFn.ExprAbs) {
                                        return "ExprAbs";
                                    };
                                    if (specializedExpr instanceof PureScript_Backend_Optimizer_CoreFn.ExprCase) {
                                        return "ExprCase";
                                    };
                                    if (specializedExpr instanceof PureScript_Backend_Optimizer_CoreFn.ExprVar) {
                                        return "ExprVar";
                                    };
                                    if (specializedExpr instanceof PureScript_Backend_Optimizer_CoreFn.ExprApp) {
                                        return "ExprApp";
                                    };
                                    if (specializedExpr instanceof PureScript_Backend_Optimizer_CoreFn.ExprLet) {
                                        return "ExprLet";
                                    };
                                    if (specializedExpr instanceof PureScript_Backend_Optimizer_CoreFn.ExprAccessor) {
                                        return "ExprAccessor";
                                    };
                                    return "Other";
                                })();
                                var etaExpandedExpr = (function () {
                                    if (specializedExpr instanceof PureScript_Backend_Optimizer_CoreFn.ExprAbs) {
                                        return specializedExpr;
                                    };
                                    if (Data_Array.length(v4.value1.dictArgs) === 0) {
                                        return specializedExpr;
                                    };
                                    var finalTy = stripTypeVariables(substFn(v4.value0));
                                    var monomorphizedAnn = mapAnn(function (t) {
                                        return finalTy;
                                    })(v3.value0.value0);
                                    var v5 = extractFuncType(finalTy);
                                    if (v5 instanceof Data_Maybe.Just) {
                                        var idents = Data_Array.mapWithIndex(function (i) {
                                            return function (v6) {
                                                return "__eta" + show(i);
                                            };
                                        })(v5.value0.fArgs);
                                        var vars = map(function (id) {
                                            return new PureScript_Backend_Optimizer_CoreFn.ExprVar(monomorphizedAnn, new PureScript_Backend_Optimizer_CoreFn.Qualified(Data_Maybe.Nothing.value, id));
                                        })(idents);
                                        var app = foldl1(function (acc) {
                                            return function (v6) {
                                                return new PureScript_Backend_Optimizer_CoreFn.ExprApp(monomorphizedAnn, acc, v6);
                                            };
                                        })(specializedExpr)(vars);
                                        return Data_Array.foldr(function (id) {
                                            return function (acc) {
                                                return new PureScript_Backend_Optimizer_CoreFn.ExprAbs(monomorphizedAnn, id, acc);
                                            };
                                        })(app)(idents);
                                    };
                                    if (v5 instanceof Data_Maybe.Nothing) {
                                        return specializedExpr;
                                    };
                                    throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 398, column 32 - line 405, column 57): " + [ v5.constructor.name ]);
                                })();
                                var newBinding = new PureScript_Backend_Optimizer_CoreFn.NonRec(new PureScript_Backend_Optimizer_CoreFn.Binding(mapAnn(function (t) {
                                    return stripTypeVariables(substFn(t));
                                })(v3.value0.value0), newName, etaExpandedExpr));
                                return new Data_Maybe.Just(newBinding);
                            };
                            return Data_Maybe.Nothing.value;
                        })(toUnfoldable(v2.value1));
                    };
                    if (v3 instanceof Data_Maybe.Nothing) {
                        return [  ];
                    };
                    throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 364, column 30 - line 412, column 28): " + [ v3.constructor.name ]);
                })();
                return processBinding;
            })(toUnfoldable(instMap));
            var hasCompose = member1("Control.Semigroupoid.compose")(instMap);
            var decls$prime = Data_Array.concatMap(monomorphizeBind(modNameStr)(instMap)(Data_Map_Internal.empty))(v.decls);
            var finalDecls = append1(decls$prime)(injectedBinds);
            var newIdents = getBindIdents(finalDecls);
            return {
                name: v.name,
                path: v.path,
                span: v.span,
                imports: v.imports,
                reExports: v.reExports,
                dataDecls: v.dataDecls,
                classDecls: v.classDecls,
                foreign: v.foreign,
                comments: v.comments,
                decls: finalDecls,
                exports: newIdents
            };
        };
    };
};
var transitiveCollect = function (globalAstMap) {
    return function (initialMap) {
        var loop = function ($copy_currentMap) {
            var $tco_done = false;
            var $tco_result;
            function $tco_loop(currentMap) {
                var newMap = Data_Array.foldl(function (acc1) {
                    return function (v) {
                        return Data_Array.foldl(function (acc2) {
                            return function (v1) {
                                var genericExprOpt = lookup1(v.value0)(globalAstMap);
                                var definerMod = (function () {
                                    var v2 = Data_String_Common.split(".")(v.value0);
                                    return Data_String_Common.joinWith(".")(Data_Maybe.fromMaybe([  ])(Data_Array.init(v2)));
                                })();
                                if (genericExprOpt instanceof Data_Maybe.Just) {
                                    var $935 = hasTypeVariables(v1.value0);
                                    if ($935) {
                                        return acc2;
                                    };
                                    var genericType = (function () {
                                        var v2 = getExprAnn(genericExprOpt.value0.value2);
                                        return Data_Maybe.fromMaybe(PureScript_Backend_Optimizer_CoreFn.Any.value)(v2.type);
                                    })();
                                    var subst = PureScript_Backend_Optimizer_Substitute.unify(genericType)(v1.value0)(Data_Map_Internal.empty);
                                    var substFn = function (t) {
                                        return stripStaticConstraints(v1.value1.dictArgs)(PureScript_Backend_Optimizer_Substitute.substituteExprType(subst)(t));
                                    };
                                    var exprWithDicts = applyDicts(v1.value1.dictArgs)(genericExprOpt.value0.value2);
                                    var resolvedExpr = resolveGlobals(definerMod)(Data_Set.empty)(exprWithDicts);
                                    return foldl1(function (acc3) {
                                        return function (caller) {
                                            var substitutedExpr = rewriteExpr(globalAstMap)(Data_Map_Internal.empty)(substFn)(resolvedExpr);
                                            var specializedExpr = monomorphizeExpr(caller)(currentMap)(Data_Map_Internal.empty)(substitutedExpr);
                                            return collectExpr(caller)(acc3)(substitutedExpr);
                                        };
                                    })(acc2)(toUnfoldable1(v1.value1.callers));
                                };
                                if (genericExprOpt instanceof Data_Maybe.Nothing) {
                                    return acc2;
                                };
                                throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Monomorphize (line 667, column 14 - line 684, column 28): " + [ genericExprOpt.constructor.name ]);
                            };
                        })(acc1)(toUnfoldable(v.value1));
                    };
                })(currentMap)(toUnfoldable(currentMap));
                var countCallers = function (m) {
                    return Data_Array.foldl(function (acc) {
                        return function (v) {
                            return acc + Data_Array.foldl(function (a) {
                                return function (v1) {
                                    return a + Data_Set.size(v1.value1.callers) | 0;
                                };
                            })(0)(toUnfoldable(v.value1)) | 0;
                        };
                    })(0)(toUnfoldable(m));
                };
                var callers2 = countCallers(newMap);
                var callers1 = countCallers(currentMap);
                var $951 = callers1 === callers2;
                if ($951) {
                    $tco_done = true;
                    return currentMap;
                };
                $copy_currentMap = newMap;
                return;
            };
            while (!$tco_done) {
                $tco_result = $tco_loop($copy_currentMap);
            };
            return $tco_result;
        };
        return loop(initialMap);
    };
};
export {
    collectInstantiations,
    collectAllTypes,
    mangleType,
    defaultToAny,
    collectAppSpine,
    getExprAnn,
    inferExprType,
    monomorphize,
    extractFuncType,
    transitiveCollect,
    applyDicts
};
