// Code generated by bin/json-text/generate.py; DO NOT EDIT.
package PureScript_Backend_Optimizer_CoreFn_Json_Text

import (
	"gopurs/output/gopurs_runtime"
	"math"
	"sort"
	"strconv"
	"strings"
	"unicode/utf16"
	"unicode/utf8"
	"unsafe"
)

// Native Go implementation of the CoreFn type-table decode + resolve path. Same algorithm and same output representation as
// PureScript.Backend.Optimizer.CoreFn.TypeTable.decodeTypeTableST, but with
// direct control flow and native intermediate values instead of ST monad
// plumbing, Maybe/Either layers and per-step closures.
//
// Json.purs calls DecodeTypeTableImpl from the Go backend; the JavaScript
// backend keeps the validated PureScript implementation in TypeTable.purs.

// Value tags used by the constructors below. They mirror the generated
// accessors byte for byte.
const (
	tc_ntTagLeft  = 3711209382
	tc_ntTagRight = 2465973597
	tc_ntTagJust  = 930809136
	tc_ntTagAny   = 1114223517

	tc_ntTagTypeMismatch = 2887704423
	tc_ntTagAtKey        = 1896025177
	tc_ntTagMissingValue = 3199441748
)

// ExprType constructor tags.
const (
	tc_ntTagInt             = 2329251128
	tc_ntTagNumber          = 3913280584
	tc_ntTagString          = 3888012862
	tc_ntTagChar            = 988402323
	tc_ntTagBoolean         = 1622340175
	tc_ntTagUnit            = 1184101581
	tc_ntTagTypeLevelString = 1716839120
	tc_ntTagArrayType       = 3898516306
	tc_ntTagTypeVar         = 2740186550
	tc_ntTagADT             = 2722479098
	tc_ntTagTypeApp         = 463633618
	tc_ntTagFunc            = 4071879509
	tc_ntTagRow             = 2829620449
	tc_ntTagRecord          = 286668774
	tc_ntTagForAll          = 1096143921
	tc_ntTagConstrainedType = 3148489123
)

func tc_ntStaticValue(tag int64) gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: tag}
}

func tc_ntJust(value gopurs_runtime.Value) gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: tc_ntTagJust, UnsafePtr: unsafe.Pointer(&Constructor_Data_Maybe_Just[gopurs_runtime.Value]{1, value})}
}

func tc_ntLeft(err gopurs_runtime.Value) gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: tc_ntTagLeft, UnsafePtr: unsafe.Pointer(&Constructor_Data_Either_Left[gopurs_runtime.Value, gopurs_runtime.Value]{1, err})}
}

func tc_ntRight(value gopurs_runtime.Value) gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: tc_ntTagRight, UnsafePtr: unsafe.Pointer(&Constructor_Data_Either_Right[gopurs_runtime.Value, gopurs_runtime.Value]{1, value})}
}

func tc_ntTypeMismatch(msg string) gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: tc_ntTagTypeMismatch, UnsafePtr: unsafe.Pointer(&Constructor_Data_Argonaut_Decode_Error_TypeMismatch{1, msg})}
}

func tc_ntMissingValue() gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: tc_ntTagMissingValue}
}

func tc_ntAtKey(key string, err gopurs_runtime.Value) gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: tc_ntTagAtKey, UnsafePtr: unsafe.Pointer(&Constructor_Data_Argonaut_Decode_Error_AtKey{1, key, err})}
}

func tc_ntTypeVar(name string) gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: tc_ntTagTypeVar, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_TypeVar{1, name})}
}

func tc_ntTypeLevelString(value string) gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: tc_ntTagTypeLevelString, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_TypeLevelString{1, value})}
}

func tc_ntADT(name string, fqn []string, args []gopurs_runtime.Value) gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: tc_ntTagADT, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_ADT{1, name, fqn, args})}
}

func tc_ntTypeApp(base gopurs_runtime.Value, args []gopurs_runtime.Value) gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: tc_ntTagTypeApp, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_TypeApp{1, base, args})}
}

func tc_ntFunc(args []gopurs_runtime.Value, ret gopurs_runtime.Value) gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: tc_ntTagFunc, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_Func{1, args, ret})}
}

func tc_ntArrayType(element gopurs_runtime.Value) gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: tc_ntTagArrayType, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_Array{1, element})}
}

func tc_ntRecordType(row gopurs_runtime.Value) gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: tc_ntTagRecord, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_Record{1, row})}
}

func tc_ntRowType(fields []*Constructor_Data_Tuple_Tuple[string, gopurs_runtime.Value], tail *Constructor_Data_Maybe_Just[gopurs_runtime.Value]) gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: tc_ntTagRow, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_Row{1, fields, tail})}
}

func tc_ntForAll(vars []string, body gopurs_runtime.Value) gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: tc_ntTagForAll, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_ForAll{1, vars, body})}
}

func tc_ntConstrainedType(constraints []*Constructor_Data_Tuple_Tuple[[]string, []gopurs_runtime.Value], body gopurs_runtime.Value) gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: tc_ntTagConstrainedType, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_ConstrainedType{1, constraints, body})}
}

// tc_ntNative converts a parsed-JSON value into its native Go form. Parsed JSON
// lives as plain Go values behind TypeAny boxes, so the object and array cases
// usually return the existing map/slice without copying.
func tc_ntNative(input tcCursor) tcCursor { return input }

func tc_ntIsNull(input tcCursor) (bool, bool) { return input.kind() == 'n', true }

// Int.fromNumber: (n | 0) === n, i.e. an exact integer within Int range.
func tc_ntInt(input tcCursor) (int64, gopurs_runtime.Value, bool) {
	f, ok := input.number()
	if !ok {
		return 0, tc_ntTypeMismatch("Failed decode"), false
	}
	if f != float64(int64(f)) {
		return 0, tc_ntTypeMismatch("Int"), false
	}
	n := int64(f)
	if n < -2147483648 || n > 2147483647 {
		return 0, tc_ntTypeMismatch("Int"), false
	}
	return n, gopurs_runtime.Value{}, true
}

// Borrow compact parsed objects and ordinary Foreign.Object maps uniformly.
type tc_ntObject = tcCursor

func tc_ntObjectOf(raw tcCursor) (tc_ntObject, bool) { return raw, raw.kind() == '{' }

func tc_ntStringField(obj tc_ntObject, key string) (string, gopurs_runtime.Value, bool) {
	raw, ok := obj.Lookup(key)
	if !ok {
		return "", tc_ntAtKey(key, tc_ntMissingValue()), false
	}
	value, ok := raw.text()
	if !ok {
		return "", tc_ntAtKey(key, tc_ntTypeMismatch("Failed decode")), false
	}
	return value, gopurs_runtime.Value{}, true
}

func tc_ntIntField(obj tc_ntObject, key string) (int64, gopurs_runtime.Value, bool) {
	raw, ok := obj.Lookup(key)
	if !ok {
		return 0, tc_ntAtKey(key, tc_ntMissingValue()), false
	}
	value, err, ok := tc_ntInt(raw)
	if !ok {
		return 0, tc_ntAtKey(key, err), false
	}
	return value, gopurs_runtime.Value{}, true
}

func tc_ntStringArrayField(obj tc_ntObject, key string) ([]string, gopurs_runtime.Value, bool) {
	raw, ok := obj.Lookup(key)
	if !ok {
		return nil, tc_ntAtKey(key, tc_ntMissingValue()), false
	}
	arr, ok := raw.array()
	if !ok {
		return nil, tc_ntAtKey(key, tc_ntTypeMismatch("Failed decode")), false
	}
	out := make([]string, arr.count)
	for cursorLoop := arr.iter(); cursorLoop.more(); {
		i, element := cursorLoop.next()
		value, ok := element.text()
		if !ok {
			return nil, tc_ntAtKey(key, tc_ntTypeMismatch("Failed decode")), false
		}
		out[i] = value
	}
	return out, gopurs_runtime.Value{}, true
}

func tc_ntIntArrayField(obj tc_ntObject, key string) ([]int64, gopurs_runtime.Value, bool) {
	raw, ok := obj.Lookup(key)
	if !ok {
		return nil, tc_ntAtKey(key, tc_ntMissingValue()), false
	}
	arr, ok := raw.array()
	if !ok {
		return nil, tc_ntAtKey(key, tc_ntTypeMismatch("Failed decode")), false
	}
	out := make([]int64, arr.count)
	for cursorLoop := arr.iter(); cursorLoop.more(); {
		i, element := cursorLoop.next()
		value, err, ok := tc_ntInt(element)
		if !ok {
			return nil, tc_ntAtKey(key, err), false
		}
		out[i] = value
	}
	return out, gopurs_runtime.Value{}, true
}

type tc_ntFieldRef struct {
	label  string
	typeId int64
}

type tc_ntConstraintRef struct {
	fqn  []string
	args []int64
}

const (
	tc_ntRefStatic uint8 = iota
	tc_ntRefADT
	tc_ntRefTypeApp
	tc_ntRefFunc
	tc_ntRefArray
	tc_ntRefRecord
	tc_ntRefRow
	tc_ntRefForAll
	tc_ntRefConstrained
)

const (
	tc_ntTailNone uint8 = iota
	tc_ntTailJust
	tc_ntTailError
)

const (
	tc_ntBodyOK uint8 = iota
	tc_ntBodyError
)

type tc_ntRef struct {
	kind  uint8
	ok    bool
	err   gopurs_runtime.Value
	value gopurs_runtime.Value

	name  string
	fqn   []string
	args  []int64
	ctor  int64
	fargs []int64
	ret   int64
	el    int64
	row   int64

	fields   []tc_ntFieldRef
	tailKind uint8
	tail     int64
	tailErr  gopurs_runtime.Value

	vars []string
	body int64

	constraints []tc_ntConstraintRef
	bodyKind    uint8
	bodyErr     gopurs_runtime.Value

	argsErr gopurs_runtime.Value
	argsOK  bool
}

func (t *tc_ntTable) decodeRef(raw tcCursor) tc_ntRef {
	if s, ok := raw.borrowedText(); ok {
		switch s {
		case "Int":
			return tc_ntRef{ok: true, kind: tc_ntRefStatic, value: tc_ntStaticValue(tc_ntTagInt)}
		case "Number":
			return tc_ntRef{ok: true, kind: tc_ntRefStatic, value: tc_ntStaticValue(tc_ntTagNumber)}
		case "String":
			return tc_ntRef{ok: true, kind: tc_ntRefStatic, value: tc_ntStaticValue(tc_ntTagString)}
		case "Char":
			return tc_ntRef{ok: true, kind: tc_ntRefStatic, value: tc_ntStaticValue(tc_ntTagChar)}
		case "Boolean":
			return tc_ntRef{ok: true, kind: tc_ntRefStatic, value: tc_ntStaticValue(tc_ntTagBoolean)}
		case "Unit":
			return tc_ntRef{ok: true, kind: tc_ntRefStatic, value: tc_ntStaticValue(tc_ntTagUnit)}
		case "Any":
			return tc_ntRef{ok: true, kind: tc_ntRefStatic, value: tc_ntStaticValue(tc_ntTagAny)}
		default:
			return tc_ntRef{err: tc_ntTypeMismatch("ExprType")}
		}
	}
	obj, ok := tc_ntObjectOf(raw)
	if !ok {
		return tc_ntRef{err: tc_ntTypeMismatch("ExprType")}
	}
	typRaw, hasType := obj.Lookup("type")
	typ, typOK := typRaw.borrowedText()
	if !hasType || !typOK {
		if tvRaw, ok := obj.Lookup("TypeVar"); ok {
			if name, ok := tvRaw.text(); ok {
				return tc_ntRef{ok: true, kind: tc_ntRefStatic, value: tc_ntTypeVar(name)}
			}
		}
		return tc_ntRef{err: tc_ntAtKey("type", tc_ntMissingValue())}
	}
	switch typ {
	case "Adt":
		fqn, err, ok := tc_ntStringArrayField(obj, "fqn")
		if !ok {
			return tc_ntRef{err: err}
		}
		args, err, ok := tc_ntIntArrayField(obj, "args")
		if !ok {
			return tc_ntRef{err: err}
		}
		return tc_ntRef{ok: true, kind: tc_ntRefADT, name: strings.Join(fqn, "."), fqn: fqn, args: args}
	case "TypeApp":
		ctor, err, ok := tc_ntIntField(obj, "constructor")
		if !ok {
			return tc_ntRef{err: err}
		}
		args, argsErr, argsOK := tc_ntIntArrayField(obj, "args")
		return tc_ntRef{ok: true, kind: tc_ntRefTypeApp, ctor: ctor, args: args, argsOK: argsOK, argsErr: argsErr}
	case "Func":
		args, err, ok := tc_ntIntArrayField(obj, "args")
		if !ok {
			return tc_ntRef{err: err}
		}
		ret, err, ok := tc_ntIntField(obj, "ret")
		if !ok {
			return tc_ntRef{err: err}
		}
		return tc_ntRef{ok: true, kind: tc_ntRefFunc, fargs: args, ret: ret}
	case "Array":
		el, err, ok := tc_ntIntField(obj, "element")
		if !ok {
			return tc_ntRef{err: err}
		}
		return tc_ntRef{ok: true, kind: tc_ntRefArray, el: el}
	case "TypeVar":
		name, err, ok := tc_ntStringField(obj, "name")
		if !ok {
			return tc_ntRef{err: err}
		}
		return tc_ntRef{ok: true, kind: tc_ntRefStatic, value: tc_ntTypeVar(name)}
	case "Record":
		row, err, ok := tc_ntIntField(obj, "row")
		if !ok {
			return tc_ntRef{err: err}
		}
		return tc_ntRef{ok: true, kind: tc_ntRefRecord, row: row}
	case "Row":
		fields, err, ok := tc_ntDecodeFields(obj)
		if !ok {
			return tc_ntRef{err: err}
		}
		ref := tc_ntRef{ok: true, kind: tc_ntRefRow, fields: fields, tailKind: tc_ntTailNone}
		if tailRaw, present := obj.Lookup("tail"); present {
			if isNull, known := tc_ntIsNull(tailRaw); !known {
				return tc_ntRef{err: tc_ntAtKey("tail", tc_ntTypeMismatch("Failed decode"))}
			} else if !isNull {
				tail, tailErr, ok := tc_ntInt(tailRaw)
				if !ok {
					ref.tailKind = tc_ntTailError
					ref.tailErr = tailErr
				} else {
					ref.tailKind = tc_ntTailJust
					ref.tail = tail
				}
			}
		}
		return ref
	case "ForAll":
		vars, err, ok := tc_ntStringArrayField(obj, "vars")
		if !ok {
			return tc_ntRef{err: err}
		}
		body, err, ok := tc_ntIntField(obj, "body")
		if !ok {
			return tc_ntRef{err: err}
		}
		return tc_ntRef{ok: true, kind: tc_ntRefForAll, vars: vars, body: body}
	case "ConstrainedType":
		constraints, err, ok := tc_ntDecodeConstraints(obj)
		if !ok {
			return tc_ntRef{err: err}
		}
		ref := tc_ntRef{ok: true, kind: tc_ntRefConstrained, constraints: constraints}
		bodyRaw, present := obj.Lookup("body")
		if !present {
			ref.bodyKind = tc_ntBodyError
			ref.bodyErr = tc_ntAtKey("body", tc_ntMissingValue())
			return ref
		}
		body, bodyErr, ok := tc_ntInt(bodyRaw)
		if !ok {
			ref.bodyKind = tc_ntBodyError
			ref.bodyErr = tc_ntAtKey("body", bodyErr)
			return ref
		}
		ref.body = body
		return ref
	case "TypeLevelString":
		value, err, ok := tc_ntStringField(obj, "value")
		if !ok {
			return tc_ntRef{err: err}
		}
		return tc_ntRef{ok: true, kind: tc_ntRefStatic, value: tc_ntTypeLevelString(value)}
	case "Int":
		return tc_ntRef{ok: true, kind: tc_ntRefStatic, value: tc_ntStaticValue(tc_ntTagInt)}
	case "Number":
		return tc_ntRef{ok: true, kind: tc_ntRefStatic, value: tc_ntStaticValue(tc_ntTagNumber)}
	case "String":
		return tc_ntRef{ok: true, kind: tc_ntRefStatic, value: tc_ntStaticValue(tc_ntTagString)}
	case "Char":
		return tc_ntRef{ok: true, kind: tc_ntRefStatic, value: tc_ntStaticValue(tc_ntTagChar)}
	case "Boolean":
		return tc_ntRef{ok: true, kind: tc_ntRefStatic, value: tc_ntStaticValue(tc_ntTagBoolean)}
	case "Unit":
		return tc_ntRef{ok: true, kind: tc_ntRefStatic, value: tc_ntStaticValue(tc_ntTagUnit)}
	case "Any":
		return tc_ntRef{ok: true, kind: tc_ntRefStatic, value: tc_ntStaticValue(tc_ntTagAny)}
	default:
		return tc_ntRef{err: tc_ntTypeMismatch("ExprType")}
	}
}

func tc_ntDecodeFields(obj tc_ntObject) ([]tc_ntFieldRef, gopurs_runtime.Value, bool) {
	raw, ok := obj.Lookup("fields")
	if !ok {
		return nil, tc_ntAtKey("fields", tc_ntMissingValue()), false
	}
	arr, ok := raw.array()
	if !ok {
		return nil, tc_ntAtKey("fields", tc_ntTypeMismatch("Failed decode")), false
	}
	out := make([]tc_ntFieldRef, arr.count)
	for cursorLoop := arr.iter(); cursorLoop.more(); {
		i, element := cursorLoop.next()
		field, ok := tc_ntObjectOf(element)
		if !ok {
			return nil, tc_ntAtKey("fields", tc_ntTypeMismatch("Failed decode")), false
		}
		label, err, ok := tc_ntStringField(field, "label")
		if !ok {
			return nil, tc_ntAtKey("fields", err), false
		}
		typeId, err, ok := tc_ntIntField(field, "type")
		if !ok {
			return nil, tc_ntAtKey("fields", err), false
		}
		out[i] = tc_ntFieldRef{label: label, typeId: typeId}
	}
	return out, gopurs_runtime.Value{}, true
}

func tc_ntDecodeConstraints(obj tc_ntObject) ([]tc_ntConstraintRef, gopurs_runtime.Value, bool) {
	raw, ok := obj.Lookup("constraints")
	if !ok {
		return nil, tc_ntAtKey("constraints", tc_ntMissingValue()), false
	}
	arr, ok := raw.array()
	if !ok {
		return nil, tc_ntAtKey("constraints", tc_ntTypeMismatch("Failed decode")), false
	}
	out := make([]tc_ntConstraintRef, arr.count)
	for cursorLoop := arr.iter(); cursorLoop.more(); {
		i, element := cursorLoop.next()
		constraint, ok := tc_ntObjectOf(element)
		if !ok {
			return nil, tc_ntAtKey("constraints", tc_ntTypeMismatch("Failed decode")), false
		}
		fqn, err, ok := tc_ntStringArrayField(constraint, "fqn")
		if !ok {
			return nil, tc_ntAtKey("constraints", err), false
		}
		args, err, ok := tc_ntIntArrayField(constraint, "args")
		if !ok {
			return nil, tc_ntAtKey("constraints", err), false
		}
		out[i] = tc_ntConstraintRef{fqn: fqn, args: args}
	}
	return out, gopurs_runtime.Value{}, true
}

// tc_ntResult is the native shape of Maybe (Either err a). ok=false is Nothing.
type tc_ntResult struct {
	ok    bool
	right bool
	value gopurs_runtime.Value
	slice []gopurs_runtime.Value
}

type tc_ntTable struct {
	refs    []tc_ntRef
	pending []int64
	state   []uint8
	errs    []gopurs_runtime.Value
	types   []gopurs_runtime.Value
}

func (t *tc_ntTable) set(id int64, result tc_ntResult) {
	if result.right {
		t.state[id] = 2
		t.types[id] = result.value
	} else {
		t.state[id] = 1
		t.errs[id] = result.value
	}
}

func (t *tc_ntTable) resolveId(id int64, force bool) tc_ntResult {
	// Peek semantics: an out-of-range index reads as an unresolved entry.
	if id < 0 || id >= int64(len(t.state)) {
		if force {
			return tc_ntResult{ok: true, right: true, value: tc_ntStaticValue(tc_ntTagAny)}
		}
		return tc_ntResult{}
	}
	switch t.state[id] {
	case 2:
		return tc_ntResult{ok: true, right: true, value: t.types[id]}
	case 1:
		return tc_ntResult{ok: true, right: false, value: t.errs[id]}
	}
	if force {
		return tc_ntResult{ok: true, right: true, value: tc_ntStaticValue(tc_ntTagAny)}
	}
	return tc_ntResult{}
}

func (t *tc_ntTable) resolveArgs(args []int64, force bool) tc_ntResult {
	values := make([]gopurs_runtime.Value, 0, len(args))
	waiting := false
	firstErr := gopurs_runtime.Value{}
	hasErr := false
	for _, id := range args {
		resolved := t.resolveId(id, force)
		if !resolved.ok {
			waiting = true
			continue
		}
		if !resolved.right {
			if !hasErr {
				firstErr = resolved.value
				hasErr = true
			}
			continue
		}
		values = append(values, resolved.value)
	}
	if waiting {
		return tc_ntResult{}
	}
	if hasErr {
		return tc_ntResult{ok: true, right: false, value: firstErr}
	}
	return tc_ntResult{ok: true, right: true, value: gopurs_runtime.Array(values), slice: values}
}

func (t *tc_ntTable) resolveType(ref *tc_ntRef, force bool) tc_ntResult {
	if !ref.ok {
		return tc_ntResult{ok: true, right: false, value: ref.err}
	}
	switch ref.kind {
	case tc_ntRefStatic:
		return tc_ntResult{ok: true, right: true, value: ref.value}
	case tc_ntRefADT:
		args := t.resolveArgs(ref.args, force)
		if !args.ok {
			return tc_ntResult{}
		}
		if !args.right {
			return args
		}
		return tc_ntResult{ok: true, right: true, value: tc_ntADT(ref.name, ref.fqn, args.slice)}
	case tc_ntRefTypeApp:
		ctor := t.resolveId(ref.ctor, force)
		if !ctor.ok {
			return tc_ntResult{}
		}
		if !ctor.right {
			return ctor
		}
		if !ref.argsOK {
			return tc_ntResult{ok: true, right: false, value: ref.argsErr}
		}
		args := t.resolveArgs(ref.args, force)
		if !args.ok {
			return tc_ntResult{}
		}
		if !args.right {
			return args
		}
		return tc_ntResult{ok: true, right: true, value: tc_ntTypeApp(ctor.value, args.slice)}
	case tc_ntRefFunc:
		args := t.resolveArgs(ref.fargs, force)
		ret := t.resolveId(ref.ret, force)
		if args.ok && !args.right {
			return args
		}
		if ret.ok && !ret.right {
			return ret
		}
		if args.ok && ret.ok {
			return tc_ntResult{ok: true, right: true, value: tc_ntFunc(args.slice, ret.value)}
		}
		return tc_ntResult{}
	case tc_ntRefArray:
		element := t.resolveId(ref.el, force)
		if !element.ok {
			return tc_ntResult{}
		}
		if !element.right {
			return element
		}
		return tc_ntResult{ok: true, right: true, value: tc_ntArrayType(element.value)}
	case tc_ntRefRecord:
		row := t.resolveId(ref.row, force)
		if !row.ok {
			return tc_ntResult{}
		}
		if !row.right {
			return row
		}
		return tc_ntResult{ok: true, right: true, value: tc_ntRecordType(row.value)}
	case tc_ntRefRow:
		resolved := make([]tc_ntResult, len(ref.fields))
		for i := range ref.fields {
			field := t.resolveId(ref.fields[i].typeId, force)
			if !field.ok {
				return tc_ntResult{}
			}
			resolved[i] = field
		}
		for _, field := range resolved {
			if !field.right {
				return field
			}
		}
		fields := make([]*Constructor_Data_Tuple_Tuple[string, gopurs_runtime.Value], len(resolved))
		for i, field := range resolved {
			fields[i] = &Constructor_Data_Tuple_Tuple[string, gopurs_runtime.Value]{1, ref.fields[i].label, field.value}
		}
		switch ref.tailKind {
		case tc_ntTailError:
			return tc_ntResult{ok: true, right: false, value: ref.tailErr}
		case tc_ntTailNone:
			return tc_ntResult{ok: true, right: true, value: tc_ntRowType(fields, nil)}
		default:
			tail := t.resolveId(ref.tail, force)
			if !tail.ok {
				return tc_ntResult{}
			}
			if !tail.right {
				return tail
			}
			return tc_ntResult{ok: true, right: true, value: tc_ntRowType(fields, &Constructor_Data_Maybe_Just[gopurs_runtime.Value]{1, tail.value})}
		}
	case tc_ntRefForAll:
		body := t.resolveId(ref.body, force)
		if !body.ok {
			return tc_ntResult{}
		}
		if !body.right {
			return body
		}
		return tc_ntResult{ok: true, right: true, value: tc_ntForAll(ref.vars, body.value)}
	case tc_ntRefConstrained:
		resolved := make([]tc_ntResult, len(ref.constraints))
		for i := range ref.constraints {
			constraint := t.resolveArgs(ref.constraints[i].args, force)
			if !constraint.ok {
				return tc_ntResult{}
			}
			resolved[i] = constraint
		}
		for _, constraint := range resolved {
			if !constraint.right {
				return constraint
			}
		}
		if ref.bodyKind == tc_ntBodyError {
			return tc_ntResult{ok: true, right: false, value: ref.bodyErr}
		}
		body := t.resolveId(ref.body, force)
		if !body.ok {
			return tc_ntResult{}
		}
		if !body.right {
			return body
		}
		constraints := make([]*Constructor_Data_Tuple_Tuple[[]string, []gopurs_runtime.Value], len(resolved))
		for i, constraint := range resolved {
			constraints[i] = &Constructor_Data_Tuple_Tuple[[]string, []gopurs_runtime.Value]{1, ref.constraints[i].fqn, constraint.slice}
		}
		return tc_ntResult{ok: true, right: true, value: tc_ntConstrainedType(constraints, body.value)}
	}
	return tc_ntResult{}
}

func (t *tc_ntTable) settle() {
	for {
		indices := t.pending
		if len(indices) == 0 {
			return
		}
		next := make([]int64, 0, len(indices))
		for _, id := range indices {
			resolved := t.resolveType(&t.refs[id], false)
			if resolved.ok {
				t.set(id, resolved)
			} else {
				next = append(next, id)
			}
		}
		t.pending = next
		if len(next) >= len(indices) {
			return
		}
	}
}

// DecodeTypeTableImpl has the same observable behaviour as the generated
// CoreFn.Json.decodeTypeTable: a JsonDecode (Array ExprType) Either value.

// tc_decodeTypeTableNative resolves an already-unwrapped table: native JSON
// entries from the module decoder are used directly, without boxing them.
func tc_decodeTypeTableNative(raw tcCursor) gopurs_runtime.Value {
	entries, ok := raw.array()
	if !ok {
		return tc_ntLeft(tc_ntTypeMismatch("Array"))
	}
	count := entries.count
	table := &tc_ntTable{
		refs:    make([]tc_ntRef, count),
		pending: make([]int64, count),
		state:   make([]uint8, count),
		errs:    make([]gopurs_runtime.Value, count),
		types:   make([]gopurs_runtime.Value, count),
	}
	for cursorLoop := entries.iter(); cursorLoop.more(); {
		i, entry := cursorLoop.next()
		table.refs[i] = table.decodeRef(entry)
		table.pending[i] = int64(i)
	}
	table.settle()
	for len(table.pending) > 0 {
		id := table.pending[0]
		table.pending = table.pending[1:]
		resolved := table.resolveType(&table.refs[id], true)
		if !resolved.ok {
			resolved = tc_ntResult{ok: true, right: false, value: tc_ntTypeMismatch("Cycle")}
		}
		table.set(id, resolved)
		table.settle()
	}
	out := make([]gopurs_runtime.Value, count)
	for i := range out {
		switch table.state[i] {
		case 2:
			out[i] = table.types[i]
		case 1:
			return tc_ntLeft(table.errs[i])
		default:
			return tc_ntLeft(tc_ntTypeMismatch("Unresolved Type (Cycle Deadlock)"))
		}
	}
	return tc_ntRight(gopurs_runtime.Array(out))
}

// DecodeArrayImpl runs the element loop of decodeArray directly and builds the
// result array natively, preserving the first-error AtIndex behaviour. The
// PureScript fallback argument is only used by the JavaScript backend.

func tc_ntAtIndex(ix int64, inner gopurs_runtime.Value) gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: 1044667600, UnsafePtr: unsafe.Pointer(&Constructor_Data_Argonaut_Decode_Error_AtIndex{1, ix, inner})}
}

// ---------------------------------------------------------------------------
// Native annotation path (decodeAnnWithUsage and its helpers).
// ---------------------------------------------------------------------------

const (
	tc_ndTagMetaIsConstructor  = 1236880537
	tc_ndTagMetaIsNewtype      = 3161528437
	tc_ndTagMetaIsTypeClass    = 1540863599
	tc_ndTagMetaIsForeign      = 1924226543
	tc_ndTagMetaIsWhere        = 1433852540
	tc_ndTagMetaIsSyntheticApp = 1233478451
	tc_ndTagProductType        = 331491576
	tc_ndTagSumType            = 3677658296
)

type tc_ndFailure struct {
	err gopurs_runtime.Value
}

func tc_ndPublic(message string) *tc_ndFailure {
	return &tc_ndFailure{err: tc_ntTypeMismatch(message)}
}

func tc_ndAtKey(key string, failure *tc_ndFailure) *tc_ndFailure {
	return &tc_ndFailure{err: tc_ntAtKey(key, failure.err)}
}

func tc_ndNothing() gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: tc_ntTagJust}
}

func tc_ndNullable(raw tcCursor) bool { return raw.kind() == 'n' }

// tc_ndNumber mirrors decodeNumber.
func tc_ndNumber(raw tcCursor) (float64, *tc_ndFailure) {
	if n, ok := raw.number(); ok {
		return n, nil
	}
	return 0, tc_ndPublic("Number")
}

// tc_ndInt mirrors decodeInt: decodeNumber followed by Int.fromNumber.
func tc_ndInt(raw tcCursor) (int64, *tc_ndFailure) {
	number, failure := tc_ndNumber(raw)
	if failure != nil {
		return 0, failure
	}
	value := int64(number)
	if float64(value) != number || value < -2147483648 || value > 2147483647 {
		return 0, tc_ndPublic("Int")
	}
	return value, nil
}

// tc_ndNonNegativeBound mirrors isNonNegativeInteger.
func tc_ndNonNegativeBound(number float64) bool {
	return number == number && !math.IsInf(number, 0) && number >= 0 && math.Trunc(number) == number
}

func tc_ndString(raw tcCursor) (string, *tc_ndFailure) {
	if value, ok := raw.text(); ok {
		return value, nil
	}
	return "", tc_ndPublic("String")
}

func tc_ndBoolean(raw tcCursor) (bool, *tc_ndFailure) {
	if value, ok := raw.boolean(); ok {
		return value, nil
	}
	return false, tc_ndPublic("Boolean")
}

func tc_ndObject(raw tcCursor) (tc_ntObject, *tc_ndFailure) {
	if value, ok := tc_ntObjectOf(raw); ok {
		return value, nil
	}
	return tc_ntObject{}, tc_ndPublic("Object")
}

func tc_ndReify(value tcCursor) tcCursor {
	return value
}

// tc_ndElementDecoder decodes one JSON value.
type tc_ndElementDecoder func(raw tcCursor) (gopurs_runtime.Value, *tc_ndFailure)

// tc_ndArray mirrors decodeArray: first error wins and is wrapped in AtIndex.
func tc_ndArray(raw tcCursor) (tcArray, *tc_ndFailure) {
	if a, ok := raw.array(); ok {
		return a, nil
	}
	return tcArray{}, tc_ndPublic("Array")
}

func tc_ndArrayOf(raw tcCursor, decode tc_ndElementDecoder) ([]gopurs_runtime.Value, *tc_ndFailure) {
	elements, failure := tc_ndArray(raw)
	if failure != nil {
		return nil, failure
	}
	out := make([]gopurs_runtime.Value, 0, elements.count)
	for cursorLoop := elements.iter(); cursorLoop.more(); {
		index, element := cursorLoop.next()
		value, failure := decode(element)
		if failure != nil {
			return nil, &tc_ndFailure{err: tc_ntAtIndex(int64(index), failure.err)}
		}
		out = append(out, value)
	}
	return out, nil
}

// tc_ndField mirrors getField: an absent key is MissingValue, a failure is wrapped
// in AtKey.
func tc_ndField(obj tc_ntObject, key string, decode tc_ndElementDecoder) (gopurs_runtime.Value, *tc_ndFailure) {
	raw, present := obj.Lookup(key)
	if !present {
		return gopurs_runtime.Value{}, &tc_ndFailure{err: tc_ntAtKey(key, tc_ntMissingValue())}
	}
	value, failure := decode(raw)
	if failure != nil {
		return gopurs_runtime.Value{}, tc_ndAtKey(key, failure)
	}
	return value, nil
}

// tc_ndOptionalField mirrors getFieldOptional': absent or null is Nothing and
// decoding failures are not wrapped.
func tc_ndOptionalField(obj tc_ntObject, key string, decode tc_ndElementDecoder) (gopurs_runtime.Value, *tc_ndFailure) {
	raw, present := obj.Lookup(key)
	if !present || tc_ndNullable(tc_ndReify(raw)) {
		return tc_ndNothing(), nil
	}
	value, failure := decode(raw)
	if failure != nil {
		return gopurs_runtime.Value{}, tc_ndAtKey(key, failure)
	}
	return tc_ntJust(value), nil
}

// tc_ndConstructorType mirrors decodeConstructorType.
func tc_ndConstructorType(raw tcCursor) (gopurs_runtime.Value, *tc_ndFailure) {
	name, failure := tc_ndString(tc_ndReify(raw))
	if failure != nil {
		return gopurs_runtime.Value{}, failure
	}
	switch name {
	case "ProductType":
		return gopurs_runtime.Value{Type: 9, IntVal: tc_ndTagProductType}, nil
	case "SumType":
		return gopurs_runtime.Value{Type: 9, IntVal: tc_ndTagSumType}, nil
	}
	return gopurs_runtime.Value{}, tc_ndPublic("ConstructorType")
}

// tc_ndMeta mirrors decodeMeta.
func tc_ndMeta(raw tcCursor) (gopurs_runtime.Value, *tc_ndFailure) {
	obj, failure := tc_ndObject(tc_ndReify(raw))
	if failure != nil {
		return gopurs_runtime.Value{}, failure
	}
	kind, failure := tc_ndField(obj, "metaType", func(value tcCursor) (gopurs_runtime.Value, *tc_ndFailure) {
		name, failure := tc_ndString(tc_ndReify(value))
		if failure != nil {
			return gopurs_runtime.Value{}, failure
		}
		return gopurs_runtime.Str(name), nil
	})
	if failure != nil {
		return gopurs_runtime.Value{}, failure
	}
	switch kind.StrVal() {
	case "IsConstructor":
		constructorType, failure := tc_ndField(obj, "constructorType", tc_ndConstructorType)
		if failure != nil {
			return gopurs_runtime.Value{}, failure
		}
		rawIdentifiers, present := obj.Lookup("identifiers")
		if !present {
			return gopurs_runtime.Value{}, &tc_ndFailure{err: tc_ntAtKey("identifiers", tc_ntMissingValue())}
		}
		names, failure := tc_ndArrayOf(rawIdentifiers, func(element tcCursor) (gopurs_runtime.Value, *tc_ndFailure) {
			name, failure := tc_ndString(tc_ndReify(element))
			if failure != nil {
				return gopurs_runtime.Value{}, failure
			}
			return gopurs_runtime.Str(name), nil
		})
		if failure != nil {
			return gopurs_runtime.Value{}, tc_ndAtKey("identifiers", failure)
		}
		identifiers := make([]string, len(names))
		for i, name := range names {
			identifiers[i] = name.StrVal()
		}
		return gopurs_runtime.Value{Type: 9, IntVal: tc_ndTagMetaIsConstructor, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_IsConstructor{1, uint32(constructorType.IntVal), identifiers})}, nil
	case "IsNewtype":
		return gopurs_runtime.Value{Type: 9, IntVal: tc_ndTagMetaIsNewtype}, nil
	case "IsTypeClassConstructor":
		return gopurs_runtime.Value{Type: 9, IntVal: tc_ndTagMetaIsTypeClass}, nil
	case "IsForeign":
		return gopurs_runtime.Value{Type: 9, IntVal: tc_ndTagMetaIsForeign}, nil
	case "IsWhere":
		return gopurs_runtime.Value{Type: 9, IntVal: tc_ndTagMetaIsWhere}, nil
	case "IsSyntheticApp":
		return gopurs_runtime.Value{Type: 9, IntVal: tc_ndTagMetaIsSyntheticApp}, nil
	}
	return gopurs_runtime.Value{}, tc_ndPublic("Meta")
}

// tc_ndSourceBindingId mirrors decodeSourceBindingId.
func tc_ndSourceBindingId(moduleName string, raw tcCursor) (gopurs_runtime.Value, *tc_ndFailure) {
	number, failure := tc_ndNumber(tc_ndReify(raw))
	if failure != nil {
		return gopurs_runtime.Value{}, failure
	}
	bindingID := int64(number)
	if float64(bindingID) != number || bindingID < -2147483648 || bindingID > 2147483647 || bindingID < 0 {
		return gopurs_runtime.Value{}, tc_ndPublic("nonnegative source bindingId within Int range")
	}
	return gopurs_runtime.RecordDict2("bindingId", "moduleName", gopurs_runtime.Int(bindingID), gopurs_runtime.Str(moduleName)), nil
}

// tc_ndUsageBound mirrors decodeUsageBound: a non-negative integral number is
// accepted, Int.fromNumber may still yield Nothing.
func tc_ndUsageBound(raw tcCursor) (gopurs_runtime.Value, *tc_ndFailure) {
	number, failure := tc_ndNumber(tc_ndReify(raw))
	if failure != nil {
		return gopurs_runtime.Value{}, failure
	}
	if !tc_ndNonNegativeBound(number) {
		return gopurs_runtime.Value{}, tc_ndPublic("nonnegative integral maxUses")
	}
	value := int64(number)
	if float64(value) != number || value > 2147483647 {
		return tc_ndNothing(), nil
	}
	return tc_ntJust(gopurs_runtime.Int(value)), nil
}

// tc_ndBindingUsage mirrors decodeBindingUsage.
func tc_ndBindingUsage(moduleName string, raw tcCursor) (gopurs_runtime.Value, *tc_ndFailure) {
	obj, failure := tc_ndObject(tc_ndReify(raw))
	if failure != nil {
		return gopurs_runtime.Value{}, failure
	}
	binding, failure := tc_ndField(obj, "bindingId", func(value tcCursor) (gopurs_runtime.Value, *tc_ndFailure) {
		return tc_ndSourceBindingId(moduleName, value)
	})
	if failure != nil {
		return gopurs_runtime.Value{}, failure
	}
	nested, failure := tc_ndOptionalField(obj, "maxUses", tc_ndUsageBound)
	if failure != nil {
		return gopurs_runtime.Value{}, failure
	}
	// join: Maybe (Maybe Int) -> Maybe Int
	maxUses := nested
	if nested.Type == 9 && nested.IntVal == tc_ntTagJust && nested.UnsafePtr != nil {
		maxUses = (*Constructor_Data_Maybe_Just[gopurs_runtime.Value])(nested.UnsafePtr).V0
	} else {
		maxUses = tc_ndNothing()
	}
	escaping, failure := tc_ndOptionalField(obj, "hasEscapingUseContext", func(value tcCursor) (gopurs_runtime.Value, *tc_ndFailure) {
		flag, failure := tc_ndBoolean(tc_ndReify(value))
		if failure != nil {
			return gopurs_runtime.Value{}, failure
		}
		return gopurs_runtime.Bool(flag), nil
	})
	if failure != nil {
		return gopurs_runtime.Value{}, failure
	}
	return gopurs_runtime.RecordDict3("binding", "hasEscapingUseContext", "maxUses", binding, escaping, maxUses), nil
}

// tc_ndVariableUse mirrors decodeVariableUse.
func tc_ndVariableUse(moduleName string, raw tcCursor) (gopurs_runtime.Value, *tc_ndFailure) {
	obj, failure := tc_ndObject(tc_ndReify(raw))
	if failure != nil {
		return gopurs_runtime.Value{}, failure
	}
	binding, failure := tc_ndField(obj, "bindingId", func(value tcCursor) (gopurs_runtime.Value, *tc_ndFailure) {
		return tc_ndSourceBindingId(moduleName, value)
	})
	if failure != nil {
		return gopurs_runtime.Value{}, failure
	}
	lastLocalUse, failure := tc_ndOptionalField(obj, "lastLocalUse", func(value tcCursor) (gopurs_runtime.Value, *tc_ndFailure) {
		flag, failure := tc_ndBoolean(tc_ndReify(value))
		if failure != nil {
			return gopurs_runtime.Value{}, failure
		}
		if !flag {
			return gopurs_runtime.Value{}, tc_ndPublic("lastLocalUse true or null")
		}
		return gopurs_runtime.Bool(true), nil
	})
	if failure != nil {
		return gopurs_runtime.Value{}, failure
	}
	return gopurs_runtime.RecordDict2("binding", "lastLocalUse", binding, lastLocalUse), nil
}

// tc_ndSourceUsage mirrors decodeSourceUsage.
func tc_ndSourceUsage(moduleName string, obj tc_ntObject) (gopurs_runtime.Value, *tc_ndFailure) {
	bindingUsage, failure := tc_ndOptionalField(obj, "bindingUsage", func(value tcCursor) (gopurs_runtime.Value, *tc_ndFailure) {
		return tc_ndBindingUsage(moduleName, value)
	})
	if failure != nil {
		return gopurs_runtime.Value{}, failure
	}
	variableUse, failure := tc_ndOptionalField(obj, "variableUse", func(value tcCursor) (gopurs_runtime.Value, *tc_ndFailure) {
		return tc_ndVariableUse(moduleName, value)
	})
	if failure != nil {
		return gopurs_runtime.Value{}, failure
	}
	if bindingUsage.UnsafePtr == nil && variableUse.UnsafePtr == nil {
		return tc_ndNothing(), nil
	}
	return tc_ntJust(gopurs_runtime.RecordDict2("bindingUsage", "variableUse", bindingUsage, variableUse)), nil
}

// DecodeAnnWithUsageImpl mirrors decodeAnnWithUsage. The PureScript fallback
// argument is only used by the JavaScript backend.

// ---------------------------------------------------------------------------
// Native CoreFn module decoder (decodeModule and all its helpers).
//
// The PureScript decoder stays the JavaScript implementation (through the
// fallback argument) and the reference for the canonical representation. Cold
// helpers whose generated specialisation is intricate (source spans, the
// foreign Map) are called through their generated functions.
// ---------------------------------------------------------------------------

const (
	tc_cndTagJust              = 930809136
	tc_cndTagLeft              = 3711209382
	tc_cndTagRight             = 2465973597
	tc_cndTagTuple             = 2339352186
	tc_cndTagQualified         = 2183844549
	tc_cndTagReExport          = 243426072
	tc_cndTagNonRec            = 776125136
	tc_cndTagRec               = 2111926015
	tc_cndTagBinding           = 74370570
	tc_cndTagExprVar           = 2055675025
	tc_cndTagExprLit           = 232770309
	tc_cndTagExprConstructor   = 697214492
	tc_cndTagExprAccessor      = 3638357773
	tc_cndTagExprUpdate        = 2514985317
	tc_cndTagExprAbs           = 2721098116
	tc_cndTagExprApp           = 519619125
	tc_cndTagExprCase          = 2509734720
	tc_cndTagExprLet           = 2588226569
	tc_cndTagExprTypeApp       = 3654600589
	tc_cndTagCaseAlternative   = 4007425008
	tc_cndTagUnconditional     = 2417754510
	tc_cndTagGuarded           = 1315856655
	tc_cndTagGuard             = 1255105998
	tc_cndTagBinderNull        = 3395565766
	tc_cndTagBinderVar         = 1586641112
	tc_cndTagBinderNamed       = 1365461886
	tc_cndTagBinderConstructor = 1517657301
	tc_cndTagBinderLit         = 1587391820
	tc_cndTagLitInt            = 2360006889
	tc_cndTagLitNumber         = 2070212633
	tc_cndTagLitString         = 4269186735
	tc_cndTagLitChar           = 4076406626
	tc_cndTagLitBoolean        = 3580262718
	tc_cndTagLitArray          = 2075623491
	tc_cndTagLitRecord         = 3197411319
	tc_cndTagProp              = 1651896758
	tc_cndTagLineComment       = 3900658198
	tc_cndTagBlockComment      = 4163130993
	tc_cndTagTypeMismatch      = 2887704423
	tc_cndTagAtIndex           = 1044667600
)

type tc_cndFailure struct {
	err gopurs_runtime.Value
}

func tc_cndFail(message string) {
	panic(tc_cndFailure{err: tc_ntTypeMismatch(message)})
}

func tc_cndFailValue(err gopurs_runtime.Value) {
	panic(tc_cndFailure{err: err})
}

func tc_cndTry(run func() gopurs_runtime.Value) (result gopurs_runtime.Value, failure *tc_cndFailure) {
	defer func() {
		if recovered := recover(); recovered != nil {
			if captured, ok := recovered.(tc_cndFailure); ok {
				failure = &captured
				return
			}
			panic(recovered)
		}
	}()
	return run(), nil
}

func tc_cndTryString(run func() string) (result string, failure *tc_cndFailure) {
	if value, captured := tc_cndTry(func() gopurs_runtime.Value { return gopurs_runtime.Str(run()) }); captured != nil {
		return "", captured
	} else {
		return value.StrVal(), nil
	}
}

func tc_cndNothing() gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagJust}
}

func tc_cndJust(value gopurs_runtime.Value) gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagJust, UnsafePtr: unsafe.Pointer(&Constructor_Data_Maybe_Just[gopurs_runtime.Value]{1, value})}
}

func tc_cndIsJust(value gopurs_runtime.Value) bool {
	return value.Type == 9 && value.IntVal == tc_cndTagJust && value.UnsafePtr != nil
}

func tc_cndFromJust(value gopurs_runtime.Value) gopurs_runtime.Value {
	return (*Constructor_Data_Maybe_Just[gopurs_runtime.Value])(value.UnsafePtr).V0
}

func tc_cndLeftPayload(value gopurs_runtime.Value) gopurs_runtime.Value {
	return (*Constructor_Data_Either_Left[gopurs_runtime.Value, gopurs_runtime.Value])(value.UnsafePtr).V0
}

func tc_cndIsLeft(value gopurs_runtime.Value) bool {
	return value.Type == 9 && value.IntVal == tc_cndTagLeft && value.UnsafePtr != nil
}

func tc_cndLeft(err gopurs_runtime.Value) gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagLeft, UnsafePtr: unsafe.Pointer(&Constructor_Data_Either_Left[gopurs_runtime.Value, gopurs_runtime.Value]{1, err})}
}

func tc_cndRight(value gopurs_runtime.Value) gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagRight, UnsafePtr: unsafe.Pointer(&Constructor_Data_Either_Right[gopurs_runtime.Value, gopurs_runtime.Value]{1, value})}
}

func tc_cndArray(values []gopurs_runtime.Value) gopurs_runtime.Value {
	return gopurs_runtime.Array(values)
}

func tc_cndValues(value gopurs_runtime.Value) []gopurs_runtime.Value {
	if value.Type == gopurs_runtime.TypeArray && value.UnsafePtr != nil {
		return *(*[]gopurs_runtime.Value)(value.UnsafePtr)
	}
	return nil
}

func tc_cndTuple(first, second gopurs_runtime.Value) gopurs_runtime.Value {
	return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagTuple, UnsafePtr: unsafe.Pointer(&Constructor_Data_Tuple_Tuple[gopurs_runtime.Value, gopurs_runtime.Value]{1, first, second})}
}

func tc_cndStringArray(values []string) gopurs_runtime.Value {
	out := make([]gopurs_runtime.Value, len(values))
	for i, value := range values {
		out[i] = gopurs_runtime.Str(value)
	}
	return gopurs_runtime.Array(out)
}

func tc_cndStrings(value gopurs_runtime.Value) []string {
	items := tc_cndValues(value)
	out := make([]string, len(items))
	for i, item := range items {
		out[i] = item.StrVal()
	}
	return out
}

// ---- JSON accessors with the PureScript error messages ----

func tc_cndString(raw tcCursor) string {
	if value, ok := raw.text(); ok {
		return value
	}
	tc_cndFail("String")
	return ""
}

func tc_cndNumber(raw tcCursor) float64 {
	if n, ok := raw.number(); ok {
		return n
	}
	tc_cndFail("Number")
	return 0
}

func tc_cndBoolean(raw tcCursor) bool {
	if value, ok := raw.boolean(); ok {
		return value
	}
	tc_cndFail("Boolean")
	return false
}

func tc_cndInt(raw tcCursor) int64 {
	number := tc_cndNumber(raw)
	value := int64(number)
	if float64(value) != number || value < -2147483648 || value > 2147483647 {
		tc_cndFail("Int")
	}
	return value
}

func tc_cndObject(raw tcCursor) tc_ntObject {
	if value, ok := tc_ntObjectOf(raw); ok {
		return value
	}
	tc_cndFail("Object")
	return tc_ntObject{}
}

func tc_cndElements(raw tcCursor) tcArray {
	if a, ok := raw.array(); ok {
		return a
	}
	tc_cndFail("Array")
	return tcArray{}
}

func tc_cndIsNull(raw tcCursor) bool { return raw.kind() == 'n' }

// ---- getField / getFieldOptional' / decodeArray ----

func tc_cndFieldOf(obj tc_ntObject, key string, decode func(tcCursor) gopurs_runtime.Value) gopurs_runtime.Value {
	raw, present := obj.Lookup(key)
	if !present {
		tc_cndFailValue(tc_ntAtKey(key, tc_ntMissingValue()))
	}
	value, failure := tc_cndTry(func() gopurs_runtime.Value { return decode(raw) })
	if failure != nil {
		tc_cndFailValue(tc_ntAtKey(key, failure.err))
	}
	return value
}

func tc_cndOptionalFieldOf(obj tc_ntObject, key string, decode func(tcCursor) gopurs_runtime.Value) gopurs_runtime.Value {
	raw, present := obj.Lookup(key)
	if !present || tc_cndIsNull(raw) {
		return tc_cndNothing()
	}
	value, failure := tc_cndTry(func() gopurs_runtime.Value { return decode(raw) })
	if failure != nil {
		tc_cndFailValue(tc_ntAtKey(key, failure.err))
	}
	return tc_cndJust(value)
}

func tc_cndArrayOfField(obj tc_ntObject, key string, decode func(tcCursor) gopurs_runtime.Value) gopurs_runtime.Value {
	return tc_cndFieldOf(obj, key, func(raw tcCursor) gopurs_runtime.Value {
		return tc_cndArrayDecode(raw, decode)
	})
}

// tc_cndArrayDecode mirrors decodeArray: first error wins, wrapped in AtIndex.
func tc_cndArrayDecode(raw tcCursor, decode func(tcCursor) gopurs_runtime.Value) gopurs_runtime.Value {
	elements := tc_cndElements(raw)
	out := make([]gopurs_runtime.Value, 0, elements.count)
	for cursorLoop := elements.iter(); cursorLoop.more(); {
		index, element := cursorLoop.next()
		value, failure := tc_cndTry(func() gopurs_runtime.Value { return decode(element) })
		if failure != nil {
			tc_cndFailValue(gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagAtIndex, UnsafePtr: unsafe.Pointer(&Constructor_Data_Argonaut_Decode_Error_AtIndex{1, int64(index), failure.err})})
		}
		out = append(out, value)
	}
	return gopurs_runtime.Array(out)
}

// tc_cndAlt mirrors alt: try the first decoder, otherwise the second.
func tc_cndAlt(first func() gopurs_runtime.Value, second func() gopurs_runtime.Value) gopurs_runtime.Value {
	if value, failure := tc_cndTry(first); failure == nil {
		return value
	}
	return second()
}

// ---- leaf decoders ----

func tc_cndModuleName(raw tcCursor) string {
	values := tc_cndValues(tc_cndArrayDecode(raw, tc_cndStringValue))
	parts := make([]string, len(values))
	for i, value := range values {
		parts[i] = value.StrVal()
	}
	return strings.Join(parts, ".")
}

func tc_cndModuleNameValue(raw tcCursor) gopurs_runtime.Value {
	return gopurs_runtime.Str(tc_cndModuleName(raw))
}

func tc_cndIdent(raw tcCursor) gopurs_runtime.Value {
	return gopurs_runtime.Str(tc_cndString(raw))
}

func tc_cndQualified(raw tcCursor, nameDecode func(tcCursor) gopurs_runtime.Value) gopurs_runtime.Value {
	obj := tc_cndObject(raw)
	var maybe *Constructor_Data_Maybe_Just[string]
	if rawModule, present := obj.Lookup("moduleName"); present && !tc_cndIsNull(rawModule) {
		name, failure := tc_cndTryString(func() string { return tc_cndModuleName(rawModule) })
		if failure != nil {
			tc_cndFailValue(failure.err)
		}
		maybe = &Constructor_Data_Maybe_Just[string]{1, name}
	}
	rawIdentifier, present := obj.Lookup("identifier")
	if !present {
		tc_cndFailValue(tc_ntAtKey("identifier", tc_ntMissingValue()))
	}
	identifier, failure := tc_cndTryString(func() string { return nameDecode(rawIdentifier).StrVal() })
	if failure != nil {
		tc_cndFailValue(tc_ntAtKey("identifier", failure.err))
	}
	return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagQualified, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_Qualified[string]{1, maybe, identifier})}
}

func tc_cndStringLiteralValue(raw tcCursor) gopurs_runtime.Value {
	if value, ok := raw.text(); ok {
		return gopurs_runtime.Str(value)
	}
	// map fromCodePointArray (decodeCodePointArray json), otherwise StringLiteral.
	if value, failure := tc_cndTry(func() gopurs_runtime.Value {
		var builder strings.Builder
		for cursorLoop := tc_cndElements(raw).iter(); cursorLoop.more(); {
			index, element := cursorLoop.next()
			if _, failure := tc_cndTry(func() gopurs_runtime.Value {
				codePoint := tc_cndInt(element)
				if codePoint < 0 || codePoint > 0x10FFFF {
					tc_cndFail("CodePoint")
				}
				builder.WriteRune(rune(codePoint))
				return gopurs_runtime.Value{}
			}); failure != nil {
				tc_cndFailValue(gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagAtIndex, UnsafePtr: unsafe.Pointer(&Constructor_Data_Argonaut_Decode_Error_AtIndex{1, int64(index), failure.err})})
			}
		}
		return gopurs_runtime.Str(builder.String())
	}); failure == nil {
		return value
	}
	tc_cndFail("StringLiteral")
	return gopurs_runtime.Value{}
}

func tc_cndStringValue(raw tcCursor) gopurs_runtime.Value {
	return gopurs_runtime.Str(tc_cndString(raw))
}

func tc_cndCharValue(raw tcCursor) gopurs_runtime.Value {
	text := tc_cndString(raw)
	codeUnits := utf16.Encode([]rune(text))
	if len(codeUnits) != 1 {
		tc_cndFail("Char")
	}
	return gopurs_runtime.Str(text)
}

func tc_cndBooleanValue(raw tcCursor) gopurs_runtime.Value {
	return gopurs_runtime.Bool(tc_cndBoolean(raw))
}

func tc_cndNumberValue(raw tcCursor) gopurs_runtime.Value {
	return gopurs_runtime.Float(tc_cndNumber(raw))
}

func tc_cndIntValue(raw tcCursor) gopurs_runtime.Value {
	return gopurs_runtime.Int(tc_cndInt(raw))
}

// ---- annotations ----

func tc_cndEmptySpan() gopurs_runtime.Value {
	return Get_PureScript_Backend_Optimizer_CoreFn_emptySpan()
}

func tc_cndMetaValue(raw tcCursor) gopurs_runtime.Value {
	value, failure := tc_ndMeta(raw)
	if failure != nil {
		tc_cndFailValue(failure.err)
	}
	return value
}

func tc_cndTypeField(typeTable []gopurs_runtime.Value, obj tc_ntObject) gopurs_runtime.Value {
	rawType, present := obj.Lookup("type")
	if !present || tc_cndIsNull(rawType) {
		return tc_cndNothing()
	}
	typeID := tc_cndInt(rawType)
	if typeID >= 0 && typeID < int64(len(typeTable)) {
		return tc_cndJust(typeTable[typeID])
	}
	return tc_cndNothing()
}

func tc_cndAnn(typeTable []gopurs_runtime.Value, raw tcCursor) gopurs_runtime.Value {
	obj := tc_cndObject(raw)
	meta := tc_cndOptionalFieldOf(obj, "meta", tc_cndMetaValue)
	typeValue := tc_cndTypeField(typeTable, obj)
	return gopurs_runtime.RecordDict4("meta", "sourceUsage", "span", "type",
		meta, tc_cndNothing(), tc_cndEmptySpan(), typeValue)
}

func tc_cndAnnWithUsage(moduleName string, typeTable []gopurs_runtime.Value, raw tcCursor) gopurs_runtime.Value {
	obj := tc_cndObject(raw)
	meta := tc_cndOptionalFieldOf(obj, "meta", tc_cndMetaValue)
	typeValue := tc_cndTypeField(typeTable, obj)
	usage, failure := tc_ndSourceUsage(moduleName, obj)
	if failure != nil {
		tc_cndFailValue(failure.err)
	}
	return gopurs_runtime.RecordDict4("meta", "sourceUsage", "span", "type",
		meta, usage, tc_cndEmptySpan(), typeValue)
}

// Coupling: this calls the generated PureScript decodeSourceSpan and converts
// its specialised result into the canonical records. The source position JSON
// is decoded through the Argonaut DecodeJson (Tuple Int Int) instance, and
// reproducing that instance natively is possible but not worth the risk for a
// cold path (two positions per module). The generated name is stable for a
// given PBO version; a rename fails the build loudly, never silently.
func tc_cndSourceSpan(path string, raw tcCursor) gopurs_runtime.Value {
	jsonValue := gopurs_runtime.Box(directMaterialize(directCursor(raw)))
	result := Call_PureScript_Backend_Optimizer_CoreFn_Json_decodeSourceSpan(path, jsonValue)
	if !result.V2 {
		tc_cndFailValue(result.V0)
	}
	position := func(column, line int64) gopurs_runtime.Value {
		return gopurs_runtime.RecordDict2("column", "line", gopurs_runtime.Int(column), gopurs_runtime.Int(line))
	}
	return gopurs_runtime.RecordDict3("end", "path", "start",
		position(result.V1.end.column, result.V1.end.line),
		gopurs_runtime.Str(result.V1.path),
		position(result.V1.start.column, result.V1.start.line))
}

// ---- expressions ----

type tc_cndAnnDecoder func(tcCursor) gopurs_runtime.Value

func tc_cndExpr(typeTable []gopurs_runtime.Value, decAnn tc_cndAnnDecoder, raw tcCursor) gopurs_runtime.Value {
	obj := tc_cndObject(raw)
	ann := tc_cndFieldOf(obj, "annotation", decAnn)
	kind := tc_cndFieldOf(obj, "type", tcBorrowedTag).StrVal()
	expr := func() gopurs_runtime.Value {
		switch kind {
		case "Var":
			qualified := tc_cndFieldOf(obj, "value", func(value tcCursor) gopurs_runtime.Value {
				return tc_cndQualified(value, tc_cndIdent)
			})
			return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagExprVar, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_ExprVar[gopurs_runtime.Value]{1, ann, (*Constructor_PureScript_Backend_Optimizer_CoreFn_Qualified[string])(qualified.UnsafePtr)})}
		case "Literal":
			literal := tc_cndFieldOf(obj, "value", func(value tcCursor) gopurs_runtime.Value {
				return tc_cndLiteral(func(inner tcCursor) gopurs_runtime.Value { return tc_cndExpr(typeTable, decAnn, inner) }, value)
			})
			return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagExprLit, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_ExprLit[gopurs_runtime.Value]{1, ann, literal})}
		case "Constructor":
			tyn := tc_cndFieldOf(obj, "typeName", tc_cndStringValue)
			con := tc_cndAlt(func() gopurs_runtime.Value { return tc_cndFieldOf(obj, "name", tc_cndIdent) },
				func() gopurs_runtime.Value { return tc_cndFieldOf(obj, "constructorName", tc_cndIdent) })
			fields := tc_cndAlt(
				func() gopurs_runtime.Value { return tc_cndArrayOfField(obj, "fields", tc_cndStringLiteralValue) },
				func() gopurs_runtime.Value { return tc_cndArrayOfField(obj, "fieldNames", tc_cndStringLiteralValue) })
			return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagExprConstructor, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_ExprConstructor[gopurs_runtime.Value]{1, ann, tyn.StrVal(), con.StrVal(), tc_cndStrings(fields)})}
		case "Accessor":
			inner := tc_cndFieldOf(obj, "expression", func(value tcCursor) gopurs_runtime.Value { return tc_cndExpr(typeTable, decAnn, value) })
			field := tc_cndFieldOf(obj, "fieldName", tc_cndStringLiteralValue)
			return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagExprAccessor, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_ExprAccessor[gopurs_runtime.Value]{1, ann, inner, field.StrVal()})}
		case "ObjectUpdate":
			inner := tc_cndFieldOf(obj, "expression", func(value tcCursor) gopurs_runtime.Value { return tc_cndExpr(typeTable, decAnn, value) })
			updates := tc_cndFieldOf(obj, "updates", func(value tcCursor) gopurs_runtime.Value {
				return tc_cndRecord(value, func(inner tcCursor) gopurs_runtime.Value { return tc_cndExpr(typeTable, decAnn, inner) })
			})
			return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagExprUpdate, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_ExprUpdate[gopurs_runtime.Value]{1, ann, inner, tc_cndProps(updates)})}
		case "Abs":
			argument := tc_cndFieldOf(obj, "argument", tc_cndIdent)
			body := tc_cndFieldOf(obj, "body", func(value tcCursor) gopurs_runtime.Value { return tc_cndExpr(typeTable, decAnn, value) })
			return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagExprAbs, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_ExprAbs[gopurs_runtime.Value]{1, ann, argument.StrVal(), body})}
		case "App":
			fn := tc_cndFieldOf(obj, "abstraction", func(value tcCursor) gopurs_runtime.Value { return tc_cndExpr(typeTable, decAnn, value) })
			arg := tc_cndFieldOf(obj, "argument", func(value tcCursor) gopurs_runtime.Value { return tc_cndExpr(typeTable, decAnn, value) })
			return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagExprApp, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_ExprApp[gopurs_runtime.Value]{1, ann, fn, arg})}
		case "TypeApp":
			inner := tc_cndFieldOf(obj, "expression", func(value tcCursor) gopurs_runtime.Value { return tc_cndExpr(typeTable, decAnn, value) })
			argument := tc_cndFieldOf(obj, "typeArgument", tc_cndIntValue)
			id := argument.IntVal
			if id < 0 || id >= int64(len(typeTable)) {
				tc_cndFail("ExprTypeApp")
			}
			return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagExprTypeApp, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_ExprTypeApp[gopurs_runtime.Value]{1, ann, inner, typeTable[id]})}
		case "Case":
			values := tc_cndArrayOfField(obj, "caseExpressions", func(value tcCursor) gopurs_runtime.Value { return tc_cndExpr(typeTable, decAnn, value) })
			alternatives := tc_cndArrayOfField(obj, "caseAlternatives", func(value tcCursor) gopurs_runtime.Value { return tc_cndCaseAlternative(typeTable, decAnn, value) })
			return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagExprCase, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_ExprCase[gopurs_runtime.Value]{1, ann, tc_cndValues(values), tc_cndAlternatives(alternatives)})}
		case "Let":
			binds := tc_cndArrayOfField(obj, "binds", func(value tcCursor) gopurs_runtime.Value { return tc_cndBind(typeTable, decAnn, value) })
			body := tc_cndFieldOf(obj, "expression", func(value tcCursor) gopurs_runtime.Value { return tc_cndExpr(typeTable, decAnn, value) })
			return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagExprLet, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_ExprLet[gopurs_runtime.Value]{1, ann, tc_cndValues(binds), body})}
		}
		tc_cndFail("Expr")
		return gopurs_runtime.Value{}
	}()
	return expr
}

func tc_cndAlternatives(value gopurs_runtime.Value) []*Constructor_PureScript_Backend_Optimizer_CoreFn_CaseAlternative[gopurs_runtime.Value] {
	items := tc_cndValues(value)
	out := make([]*Constructor_PureScript_Backend_Optimizer_CoreFn_CaseAlternative[gopurs_runtime.Value], len(items))
	for i, item := range items {
		out[i] = (*Constructor_PureScript_Backend_Optimizer_CoreFn_CaseAlternative[gopurs_runtime.Value])(item.UnsafePtr)
	}
	return out
}

func tc_cndProps(value gopurs_runtime.Value) []*Constructor_PureScript_Backend_Optimizer_CoreFn_Prop[gopurs_runtime.Value] {
	items := tc_cndValues(value)
	out := make([]*Constructor_PureScript_Backend_Optimizer_CoreFn_Prop[gopurs_runtime.Value], len(items))
	for i, item := range items {
		out[i] = (*Constructor_PureScript_Backend_Optimizer_CoreFn_Prop[gopurs_runtime.Value])(item.UnsafePtr)
	}
	return out
}

func tc_cndCaseAlternative(typeTable []gopurs_runtime.Value, decAnn tc_cndAnnDecoder, raw tcCursor) gopurs_runtime.Value {
	obj := tc_cndObject(raw)
	binders := tc_cndArrayOfField(obj, "binders", func(value tcCursor) gopurs_runtime.Value { return tc_cndBinder(decAnn, value) })
	guarded := tc_cndFieldOf(obj, "isGuarded", func(value tcCursor) gopurs_runtime.Value { return tc_cndBooleanValue(value) })
	var result gopurs_runtime.Value
	if guarded.BoolVal() {
		expressions := tc_cndArrayOfField(obj, "expressions", func(value tcCursor) gopurs_runtime.Value { return tc_cndGuard(typeTable, decAnn, value) })
		guards := tc_cndValues(expressions)
		pointers := make([]*Constructor_PureScript_Backend_Optimizer_CoreFn_Guard[gopurs_runtime.Value], len(guards))
		for i, guard := range guards {
			pointers[i] = (*Constructor_PureScript_Backend_Optimizer_CoreFn_Guard[gopurs_runtime.Value])(guard.UnsafePtr)
		}
		result = gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagGuarded, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_Guarded[gopurs_runtime.Value]{1, pointers})}
	} else {
		expression := tc_cndFieldOf(obj, "expression", func(value tcCursor) gopurs_runtime.Value { return tc_cndExpr(typeTable, decAnn, value) })
		result = gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagUnconditional, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_Unconditional[gopurs_runtime.Value]{1, expression})}
	}
	return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagCaseAlternative, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_CaseAlternative[gopurs_runtime.Value]{1, tc_cndValues(binders), result})}
}

func tc_cndGuard(typeTable []gopurs_runtime.Value, decAnn tc_cndAnnDecoder, raw tcCursor) gopurs_runtime.Value {
	obj := tc_cndObject(raw)
	guard := tc_cndFieldOf(obj, "guard", func(value tcCursor) gopurs_runtime.Value { return tc_cndExpr(typeTable, decAnn, value) })
	expression := tc_cndFieldOf(obj, "expression", func(value tcCursor) gopurs_runtime.Value { return tc_cndExpr(typeTable, decAnn, value) })
	return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagGuard, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_Guard[gopurs_runtime.Value]{1, guard, expression})}
}

// ---- binders and literals ----

func tc_cndBinder(decAnn tc_cndAnnDecoder, raw tcCursor) gopurs_runtime.Value {
	obj := tc_cndObject(raw)
	ann := tc_cndFieldOf(obj, "annotation", decAnn)
	kind := tc_cndFieldOf(obj, "binderType", tcBorrowedTag).StrVal()
	switch kind {
	case "NullBinder":
		return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagBinderNull, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_BinderNull[gopurs_runtime.Value]{1, ann})}
	case "VarBinder":
		identifier := tc_cndFieldOf(obj, "identifier", tc_cndIdent)
		return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagBinderVar, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_BinderVar[gopurs_runtime.Value]{1, ann, identifier.StrVal()})}
	case "LiteralBinder":
		literal := tc_cndFieldOf(obj, "literal", func(value tcCursor) gopurs_runtime.Value {
			return tc_cndLiteral(func(inner tcCursor) gopurs_runtime.Value { return tc_cndBinder(decAnn, inner) }, value)
		})
		return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagBinderLit, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_BinderLit[gopurs_runtime.Value]{1, ann, literal})}
	case "ConstructorBinder":
		tyn := tc_cndFieldOf(obj, "typeName", func(value tcCursor) gopurs_runtime.Value {
			return tc_cndQualified(value, func(inner tcCursor) gopurs_runtime.Value { return gopurs_runtime.Str(tc_cndString(inner)) })
		})
		con := tc_cndAlt(
			func() gopurs_runtime.Value {
				return tc_cndFieldOf(obj, "name", func(value tcCursor) gopurs_runtime.Value {
					return tc_cndQualified(value, tc_cndIdent)
				})
			},
			func() gopurs_runtime.Value {
				return tc_cndFieldOf(obj, "constructorName", func(value tcCursor) gopurs_runtime.Value {
					return tc_cndQualified(value, tc_cndIdent)
				})
			})
		binders := tc_cndArrayOfField(obj, "binders", func(value tcCursor) gopurs_runtime.Value { return tc_cndBinder(decAnn, value) })
		return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagBinderConstructor, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_BinderConstructor[gopurs_runtime.Value]{1, ann, (*Constructor_PureScript_Backend_Optimizer_CoreFn_Qualified[string])(tyn.UnsafePtr), (*Constructor_PureScript_Backend_Optimizer_CoreFn_Qualified[string])(con.UnsafePtr), tc_cndValues(binders)})}
	case "NamedBinder":
		identifier := tc_cndFieldOf(obj, "identifier", tc_cndIdent)
		binder := tc_cndFieldOf(obj, "binder", func(value tcCursor) gopurs_runtime.Value { return tc_cndBinder(decAnn, value) })
		return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagBinderNamed, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_BinderNamed[gopurs_runtime.Value]{1, ann, identifier.StrVal(), binder})}
	}
	tc_cndFail("Binder")
	return gopurs_runtime.Value{}
}

func tc_cndLiteral(dec func(tcCursor) gopurs_runtime.Value, raw tcCursor) gopurs_runtime.Value {
	obj := tc_cndObject(raw)
	kind := tc_cndFieldOf(obj, "literalType", tcBorrowedTag).StrVal()
	switch kind {
	case "IntLiteral":
		value := tc_cndFieldOf(obj, "value", tc_cndIntValue)
		return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagLitInt, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_LitInt[gopurs_runtime.Value]{1, value.IntVal})}
	case "NumberLiteral":
		value := tc_cndFieldOf(obj, "value", tc_cndNumberValue)
		return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagLitNumber, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_LitNumber[gopurs_runtime.Value]{1, float64(value.FloatVal())})}
	case "StringLiteral":
		value := tc_cndFieldOf(obj, "value", tc_cndStringLiteralValue)
		return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagLitString, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_LitString[gopurs_runtime.Value]{1, value.StrVal()})}
	case "CharLiteral":
		value := tc_cndFieldOf(obj, "value", tc_cndCharValue)
		return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagLitChar, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_LitChar[gopurs_runtime.Value]{1, value.StrVal()})}
	case "BooleanLiteral":
		value := tc_cndFieldOf(obj, "value", tc_cndBooleanValue)
		return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagLitBoolean, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_LitBoolean[gopurs_runtime.Value]{1, value.BoolVal()})}
	case "ArrayLiteral":
		value := tc_cndFieldOf(obj, "value", func(inner tcCursor) gopurs_runtime.Value { return tc_cndArrayDecode(inner, dec) })
		return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagLitArray, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_LitArray[gopurs_runtime.Value]{1, tc_cndValues(value)})}
	case "ObjectLiteral":
		value := tc_cndFieldOf(obj, "value", func(inner tcCursor) gopurs_runtime.Value { return tc_cndRecord(inner, dec) })
		return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagLitRecord, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_LitRecord[gopurs_runtime.Value]{1, tc_cndProps(value)})}
	}
	tc_cndFail("Literal")
	return gopurs_runtime.Value{}
}

// tc_cndRecord mirrors decodeRecord = decodeArray <<< decodeProp.
func tc_cndRecord(raw tcCursor, dec func(tcCursor) gopurs_runtime.Value) gopurs_runtime.Value {
	return tc_cndArrayDecode(raw, func(element tcCursor) gopurs_runtime.Value {
		elements := tc_cndElements(element)
		if elements.count != 2 {
			tc_cndFail("Tuple")
		}
		key := tc_cndStringLiteralValue(elements.at(0))
		value := dec(elements.at(1))
		return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagProp, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_Prop[gopurs_runtime.Value]{1, key.StrVal(), value})}
	})
}

func tc_cndComment(raw tcCursor) gopurs_runtime.Value {
	obj := tc_cndObject(raw)
	if value, failure := tc_cndTry(func() gopurs_runtime.Value { return tc_cndFieldOf(obj, "LineComment", tc_cndStringValue) }); failure == nil {
		return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagLineComment, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_LineComment{1, value.StrVal()})}
	}
	value := tc_cndFieldOf(obj, "BlockComment", tc_cndStringValue)
	return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagBlockComment, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_BlockComment{1, value.StrVal()})}
}

// ---- binds and module parts ----

func tc_cndBind(typeTable []gopurs_runtime.Value, decAnn tc_cndAnnDecoder, raw tcCursor) gopurs_runtime.Value {
	obj := tc_cndObject(raw)
	kind := tc_cndFieldOf(obj, "bindType", tcBorrowedTag).StrVal()
	switch kind {
	case "NonRec":
		binding := tc_cndBinding(typeTable, decAnn, obj)
		return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagNonRec, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_NonRec[gopurs_runtime.Value]{1, tc_cndBindingPointer(binding)})}
	case "Rec":
		binds := tc_cndArrayOfField(obj, "binds", func(value tcCursor) gopurs_runtime.Value {
			return tc_cndBinding(typeTable, decAnn, tc_cndObject(value))
		})
		bindings := make([]*Constructor_PureScript_Backend_Optimizer_CoreFn_Binding[gopurs_runtime.Value], 0, len(tc_cndValues(binds)))
		for _, binding := range tc_cndValues(binds) {
			bindings = append(bindings, tc_cndBindingPointer(binding))
		}
		return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagRec, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_Rec[gopurs_runtime.Value]{1, bindings})}
	}
	tc_cndFail("Bind")
	return gopurs_runtime.Value{}
}

func tc_cndBindingPointer(value gopurs_runtime.Value) *Constructor_PureScript_Backend_Optimizer_CoreFn_Binding[gopurs_runtime.Value] {
	return (*Constructor_PureScript_Backend_Optimizer_CoreFn_Binding[gopurs_runtime.Value])(value.UnsafePtr)
}

func tc_cndBinding(typeTable []gopurs_runtime.Value, decAnn tc_cndAnnDecoder, obj tc_ntObject) gopurs_runtime.Value {
	ann := tc_cndFieldOf(obj, "annotation", decAnn)
	identifier := tc_cndFieldOf(obj, "identifier", tc_cndIdent)
	expression := tc_cndFieldOf(obj, "expression", func(value tcCursor) gopurs_runtime.Value { return tc_cndExpr(typeTable, decAnn, value) })
	return gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagBinding, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_Binding[gopurs_runtime.Value]{1, ann, identifier.StrVal(), expression})}
}

func tc_cndImport(decAnn tc_cndAnnDecoder, raw tcCursor) gopurs_runtime.Value {
	obj := tc_cndObject(raw)
	ann := tc_cndFieldOf(obj, "annotation", decAnn)
	name := tc_cndFieldOf(obj, "moduleName", tc_cndModuleNameValue)
	return gopurs_runtime.Value{Type: 9, IntVal: 2024897590, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_Import[gopurs_runtime.Value]{1, ann, name.StrVal()})}
}

func tc_cndReExports(raw tcCursor) gopurs_runtime.Value {
	obj := tc_cndObject(raw)
	keys := obj.Keys()
	sort.Strings(keys)
	out := make([]gopurs_runtime.Value, 0)
	for _, moduleName := range keys {
		// decodeReExports decodes each value directly with decodeArray; there is
		// no getField wrapper, so failures are not tagged with the key.
		rawIdents, _ := obj.Lookup(moduleName)
		idents := tc_cndArrayDecode(rawIdents, tc_cndIdent)
		for _, ident := range tc_cndValues(idents) {
			out = append(out, gopurs_runtime.Value{Type: 9, IntVal: tc_cndTagReExport, UnsafePtr: unsafe.Pointer(&Constructor_PureScript_Backend_Optimizer_CoreFn_ReExport{1, moduleName, ident.StrVal()})})
		}
	}
	return gopurs_runtime.Array(out)
}

func tc_cndDataConstructor(typeTable []gopurs_runtime.Value, raw tcCursor) gopurs_runtime.Value {
	obj := tc_cndObject(raw)
	name := tc_cndAlt(
		func() gopurs_runtime.Value { return tc_cndFieldOf(obj, "name", tc_cndStringValue) },
		func() gopurs_runtime.Value { return tc_cndFieldOf(obj, "constructorName", tc_cndStringValue) })
	fieldIDs := tc_cndAlt(
		func() gopurs_runtime.Value { return tc_cndArrayOfField(obj, "fields", tc_cndIntValue) },
		func() gopurs_runtime.Value { return tc_cndArrayOfField(obj, "fieldTypes", tc_cndIntValue) })
	fields := make([]gopurs_runtime.Value, 0, len(tc_cndValues(fieldIDs)))
	for _, fieldID := range tc_cndValues(fieldIDs) {
		id := fieldID.IntVal
		if id < 0 || id >= int64(len(typeTable)) {
			tc_cndFail("ConstructorField")
		}
		fields = append(fields, typeTable[id])
	}
	return gopurs_runtime.RecordDict2("fields", "name", gopurs_runtime.Array(fields), gopurs_runtime.Str(name.StrVal()))
}

func tc_cndDataDecl(typeTable []gopurs_runtime.Value, raw tcCursor) gopurs_runtime.Value {
	obj := tc_cndObject(raw)
	name := tc_cndAlt(
		func() gopurs_runtime.Value { return tc_cndFieldOf(obj, "name", tc_cndStringValue) },
		func() gopurs_runtime.Value { return tc_cndFieldOf(obj, "typeName", tc_cndStringValue) })
	mbVars := tc_cndAlt(
		func() gopurs_runtime.Value {
			return tc_cndOptionalFieldOf(obj, "vars", func(value tcCursor) gopurs_runtime.Value { return tc_cndArrayDecode(value, tc_cndStringValue) })
		},
		func() gopurs_runtime.Value {
			return tc_cndOptionalFieldOf(obj, "typeVars", func(value tcCursor) gopurs_runtime.Value { return tc_cndArrayDecode(value, tc_cndStringValue) })
		})
	constructors := tc_cndArrayOfField(obj, "constructors", func(value tcCursor) gopurs_runtime.Value { return tc_cndDataConstructor(typeTable, value) })
	vars := gopurs_runtime.Array(nil)
	if tc_cndIsJust(mbVars) {
		vars = tc_cndFromJust(mbVars)
	}
	return gopurs_runtime.RecordDict3("constructors", "name", "vars",
		constructors, gopurs_runtime.Str(name.StrVal()), vars)
}

func tc_cndClassDecl(typeTable []gopurs_runtime.Value, raw tcCursor) gopurs_runtime.Value {
	obj := tc_cndObject(raw)
	name := tc_cndFieldOf(obj, "name", tc_cndStringValue)
	mbVars := tc_cndOptionalFieldOf(obj, "vars", func(value tcCursor) gopurs_runtime.Value { return tc_cndArrayDecode(value, tc_cndStringValue) })
	var vars gopurs_runtime.Value
	if tc_cndIsJust(mbVars) {
		vars = tc_cndFromJust(mbVars)
	} else {
		vars = gopurs_runtime.Array(nil)
	}
	superclasses := tc_cndArrayOfField(obj, "superclasses", func(value tcCursor) gopurs_runtime.Value { return tc_cndConstraint(typeTable, value) })
	methods := tc_cndArrayOfField(obj, "methods", func(value tcCursor) gopurs_runtime.Value { return tc_cndMethod(typeTable, value) })
	return gopurs_runtime.RecordDict4("methods", "name", "superclasses", "vars",
		methods, gopurs_runtime.Str(name.StrVal()), superclasses, vars)
}

func tc_cndMethod(typeTable []gopurs_runtime.Value, raw tcCursor) gopurs_runtime.Value {
	obj := tc_cndObject(raw)
	name := tc_cndFieldOf(obj, "name", tc_cndStringValue)
	typeID := tc_cndFieldOf(obj, "type", tc_cndIntValue)
	id := typeID.IntVal
	if id < 0 || id >= int64(len(typeTable)) {
		tc_cndFail("MethodType")
	}
	return tc_cndTuple(name, typeTable[id])
}

func tc_cndConstraint(typeTable []gopurs_runtime.Value, raw tcCursor) gopurs_runtime.Value {
	obj := tc_cndObject(raw)
	fqn := tc_cndArrayOfField(obj, "fqn", tc_cndStringValue)
	argIDs := tc_cndArrayOfField(obj, "args", tc_cndIntValue)
	args := make([]gopurs_runtime.Value, 0, len(tc_cndValues(argIDs)))
	for _, argID := range tc_cndValues(argIDs) {
		id := argID.IntVal
		if id < 0 || id >= int64(len(typeTable)) {
			tc_cndFail("ConstraintArg")
		}
		args = append(args, typeTable[id])
	}
	return tc_cndTuple(fqn, gopurs_runtime.Array(args))
}

// ---- module ----

func tc_cndModulePrime(moduleName string, obj tc_ntObject, path string) gopurs_runtime.Value {
	typeTable := []gopurs_runtime.Value{}
	if rawTypeTable, present := obj.Lookup("typeTable"); present && !tc_cndIsNull(rawTypeTable) {
		decoded := tc_decodeTypeTableNative(rawTypeTable)
		if tc_cndIsLeft(decoded) {
			tc_cndFailValue(tc_ntAtKey("typeTable", tc_cndLeftPayload(decoded)))
		}
		typeTable = tc_cndValues((*Constructor_Data_Either_Right[gopurs_runtime.Value, gopurs_runtime.Value])(decoded.UnsafePtr).V0)
	}
	decAnn := func(raw tcCursor) gopurs_runtime.Value { return tc_cndAnnWithUsage(moduleName, typeTable, raw) }
	span := tc_cndFieldOf(obj, "sourceSpan", func(value tcCursor) gopurs_runtime.Value { return tc_cndSourceSpan(path, value) })
	imports := tc_cndArrayOfField(obj, "imports", func(value tcCursor) gopurs_runtime.Value { return tc_cndImport(decAnn, value) })
	exports := tc_cndArrayOfField(obj, "exports", tc_cndIdent)
	reExports := tc_cndFieldOf(obj, "reExports", tc_cndReExports)
	mbDataDecls := tc_cndOptionalFieldOf(obj, "dataDecls", func(value tcCursor) gopurs_runtime.Value {
		return tc_cndArrayDecode(value, func(inner tcCursor) gopurs_runtime.Value { return tc_cndDataDecl(typeTable, inner) })
	})
	var dataDecls []gopurs_runtime.Value
	if tc_cndIsJust(mbDataDecls) {
		dataDecls = tc_cndValues(tc_cndFromJust(mbDataDecls))
	}
	mbClassDecls := tc_cndOptionalFieldOf(obj, "classDecls", func(value tcCursor) gopurs_runtime.Value {
		return tc_cndArrayDecode(value, func(inner tcCursor) gopurs_runtime.Value { return tc_cndClassDecl(typeTable, inner) })
	})
	var classDecls []gopurs_runtime.Value
	if tc_cndIsJust(mbClassDecls) {
		classDecls = tc_cndValues(tc_cndFromJust(mbClassDecls))
	}
	decls := tc_cndArrayOfField(obj, "decls", func(value tcCursor) gopurs_runtime.Value { return tc_cndBind(typeTable, decAnn, value) })
	foreignArr := tc_cndArrayOfField(obj, "foreign", tc_cndIdent)
	var foreignAnnotations tc_ntObject
	if rawAnnotations, present := obj.Lookup("foreignAnnotations"); present && !tc_cndIsNull(rawAnnotations) {
		if _, failure := tc_cndTry(func() gopurs_runtime.Value {
			foreignAnnotations = tc_cndObject(rawAnnotations)
			return gopurs_runtime.Value{}
		}); failure != nil {
			tc_cndFailValue(tc_ntAtKey("foreignAnnotations", failure.err))
		}
	}
	foreignList := make([]gopurs_runtime.Value, 0, len(tc_cndValues(foreignArr)))
	for _, ident := range tc_cndValues(foreignArr) {
		typeValue := tc_cndNothing()
		if rawAnn, ok := foreignAnnotations.Lookup(ident.StrVal()); ok {
			ann := tc_cndAnn(typeTable, rawAnn)
			typeValue = gopurs_runtime.RecordGet(ann, "type")
		}
		foreignList = append(foreignList, tc_cndTuple(gopurs_runtime.Str(ident.StrVal()), typeValue))
	}
	// Coupling: the foreign annotations map is built by the generated
	// specialised Map.fromFoldable (the Map is an opaque native structure).
	// Calling the Map FFI insert path directly would require the Ord String
	// comparator as a Value; the generated helper is stable for a given PBO
	// version and a rename fails the build loudly.
	foreignMap := Call_Data_Map_Internal_fromFoldable__1911179134(gopurs_runtime.Array(foreignList))
	comments := tc_cndArrayOfField(obj, "comments", tc_cndComment)
	return gopurs_runtime.RecordDict(
		[]string{"classDecls", "comments", "dataDecls", "decls", "exports", "foreign", "imports", "name", "path", "reExports", "span"},
		[]gopurs_runtime.Value{
			gopurs_runtime.Array(classDecls),
			comments,
			gopurs_runtime.Array(dataDecls),
			decls,
			exports,
			foreignMap,
			imports,
			gopurs_runtime.Str(moduleName),
			gopurs_runtime.Str(path),
			reExports,
			span,
		})
}

// DecodeModuleImpl mirrors CoreFn.Json.decodeModule. The PureScript fallback
// argument is only used by the JavaScript backend.
func tcDecodeModule(fallback gopurs_runtime.Value, validate gopurs_runtime.Value, json tcCursor) (result gopurs_runtime.Value) {
	_ = fallback
	defer func() {
		if recovered := recover(); recovered != nil {
			if failure, ok := recovered.(tc_cndFailure); ok {
				result = tc_cndLeft(failure.err)
				return
			}
			panic(recovered)
		}
	}()
	obj := tc_cndObject(json)
	name := tc_cndFieldOf(obj, "moduleName", tc_cndModuleNameValue)
	path := tc_cndFieldOf(obj, "modulePath", tc_cndStringValue)
	module := tc_cndModulePrime(name.StrVal(), obj, path.StrVal())
	validation := gopurs_runtime.Apply(validate, module)
	if tc_cndIsLeft(validation) {
		tc_cndFailValue(tc_cndLeftPayload(validation))
	}
	return tc_cndRight(module)
}

// Validate syntax and build a call-local index together. Every value, including
// ignored members, is validated before schema decoding starts. Strings become
// owned only when they enter the final result; cursors never escape as Json.

// Scalars store their source end (plus a string-normalization flag), arrays
// their length, and objects the last key token. Key.next links to the preceding
// key in that object; value.next always skips the complete value subtree.
type directToken struct{ start, end, next uint32 }
type directDocument struct {
	text   string
	tokens []directToken
}
type directCursor struct {
	document *directDocument
	index    uint32
}
type directParser struct {
	document directDocument
	pos      int
}

const directNormalize uint32 = 1 << 31

func directIndex(text string) (directCursor, bool) {
	if uint64(len(text)) >= uint64(directNormalize) {
		return directCursor{}, false
	}
	p := directParser{document: directDocument{text: text, tokens: make([]directToken, 0, len(text)/6+8)}}
	if !p.value(0) {
		return directCursor{}, false
	}
	p.space()
	if p.pos != len(text) {
		return directCursor{}, false
	}
	return directCursor{&p.document, 0}, true
}
func (p *directParser) space() {
	for p.pos < len(p.document.text) {
		switch p.document.text[p.pos] {
		case ' ', '\t', '\n', '\r':
			p.pos++
		default:
			return
		}
	}
}
func (p *directParser) take(c byte) bool {
	if p.pos < len(p.document.text) && p.document.text[p.pos] == c {
		p.pos++
		return true
	}
	return false
}
func (p *directParser) value(depth int) bool {
	p.space()
	text := p.document.text
	if p.pos == len(text) {
		return false
	}
	index := len(p.document.tokens)
	start := p.pos
	switch text[start] {
	case '{', '[':
		if depth >= 10000 {
			return false
		}
		object := text[start] == '{'
		end := byte(']')
		if object {
			end = '}'
		}
		p.pos++
		p.document.tokens = append(p.document.tokens, directToken{start: uint32(start)})
		p.space()
		var count, lastKey uint32
		if !p.take(end) {
			for {
				if object {
					key := uint32(len(p.document.tokens))
					if !p.string() {
						return false
					}
					p.document.tokens[key].next = lastKey
					lastKey = key
					p.space()
					if !p.take(':') {
						return false
					}
				}
				if !p.value(depth + 1) {
					return false
				}
				count++
				p.space()
				if p.take(end) {
					break
				}
				if !p.take(',') {
					return false
				}
				p.space()
			}
		}
		if object {
			count = lastKey
		}
		p.document.tokens[index].end = count
		p.document.tokens[index].next = uint32(len(p.document.tokens))
		return true
	case '"':
		return p.string()
	case 't':
		if !strings.HasPrefix(text[start:], "true") {
			return false
		}
		p.pos += 4
	case 'f':
		if !strings.HasPrefix(text[start:], "false") {
			return false
		}
		p.pos += 5
	case 'n':
		if !strings.HasPrefix(text[start:], "null") {
			return false
		}
		p.pos += 4
	default:
		if !p.number() {
			return false
		}
	}
	p.document.tokens = append(p.document.tokens, directToken{uint32(start), uint32(p.pos), uint32(index + 1)})
	return true
}
func (p *directParser) string() bool {
	text := p.document.text
	start := p.pos
	if !p.take('"') {
		return false
	}
	escaped, nonASCII := false, false
	for p.pos < len(text) {
		c := text[p.pos]
		p.pos++
		if c == '"' {
			end := uint32(p.pos)
			if escaped || (nonASCII && !utf8.ValidString(text[start+1:p.pos-1])) {
				end |= directNormalize
			}
			p.document.tokens = append(p.document.tokens, directToken{uint32(start), end, uint32(len(p.document.tokens) + 1)})
			return true
		}
		if c < 0x20 {
			return false
		}
		if c >= utf8.RuneSelf {
			nonASCII = true
		}
		if c != '\\' {
			continue
		}
		escaped = true
		if p.pos == len(text) {
			return false
		}
		escape := text[p.pos]
		p.pos++
		switch escape {
		case '"', '\\', '/', 'b', 'f', 'n', 'r', 't':
		case 'u':
			if _, ok := argonautJSONHex4(text, p.pos); !ok {
				return false
			}
			p.pos += 4
		default:
			return false
		}
	}
	return false
}
func (p *directParser) number() bool {
	text := p.document.text
	start := p.pos
	p.take('-')
	if p.pos == len(text) {
		return false
	}
	if !p.take('0') {
		if text[p.pos] < '1' || text[p.pos] > '9' {
			return false
		}
		for p.pos < len(text) && text[p.pos] >= '0' && text[p.pos] <= '9' {
			p.pos++
		}
	}
	integer := true
	if p.take('.') {
		integer = false
		digits := p.pos
		for p.pos < len(text) && text[p.pos] >= '0' && text[p.pos] <= '9' {
			p.pos++
		}
		if digits == p.pos {
			return false
		}
	}
	if p.pos < len(text) && (text[p.pos] == 'e' || text[p.pos] == 'E') {
		integer = false
		p.pos++
		if !p.take('+') {
			p.take('-')
		}
		digits := p.pos
		for p.pos < len(text) && text[p.pos] >= '0' && text[p.pos] <= '9' {
			p.pos++
		}
		if digits == p.pos {
			return false
		}
	}
	// Short integers are finite by construction. Overflow in every other
	// number must fail even if the schema never reads that member.
	if !integer || p.pos-start > 15 {
		if _, err := strconv.ParseFloat(text[start:p.pos], 64); err != nil {
			return false
		}
	}
	return true
}
func (cursor directCursor) kind() byte {
	return cursor.document.text[cursor.document.tokens[cursor.index].start]
}
func (cursor directCursor) string(owned bool) string {
	token := cursor.document.tokens[cursor.index]
	text := cursor.document.text[token.start+1 : (token.end&^directNormalize)-1]
	if token.end&directNormalize != 0 {
		value, ok := argonautUnquoteJSON(text)
		if !ok {
			panic("validated string")
		}
		return value
	}
	if owned {
		return strings.Clone(text)
	}
	return text
}
func (cursor directCursor) native() any {
	token := cursor.document.tokens[cursor.index]
	switch cursor.kind() {
	case '{':
		return cursor
	case '[':
		items := make([]any, token.end)
		i := 0
		for at := cursor.index + 1; at < token.next; at = cursor.document.tokens[at].next {
			items[i] = directCursor{cursor.document, at}
			i++
		}
		return items
	case '"':
		return cursor.string(true)
	case 't':
		return true
	case 'f':
		return false
	case 'n':
		return nil
	default:
		value, err := strconv.ParseFloat(cursor.document.text[token.start:token.end], 64)
		if err != nil {
			panic(err)
		}
		return value
	}
}
func (cursor directCursor) JSONLookup(key string) (any, bool) {
	value, ok := tcCursor(cursor).Lookup(key)
	if !ok {
		return nil, false
	}
	return directCursor(value), true
}
func (cursor directCursor) keys() []string {
	keys := []string{}
	for at := cursor.index + 1; at < cursor.document.tokens[cursor.index].next; {
		name := (directCursor{cursor.document, at}).string(true)
		exists := false
		for _, key := range keys {
			if key == name {
				exists = true
				break
			}
		}
		if !exists {
			keys = append(keys, name)
		}
		at = cursor.document.tokens[at+1].next
	}
	return keys
}

// Only the existing cold source-span boundary materializes a public Json.
func directMaterialize(raw any) any {
	cursor, ok := raw.(directCursor)
	if !ok {
		return ntNative(raw)
	}
	if cursor.kind() == '{' {
		object := make(map[string]any)
		for _, key := range cursor.keys() {
			value, _ := cursor.JSONLookup(key)
			object[key] = directMaterialize(value)
		}
		return object
	}
	value := cursor.native()
	if array, ok := value.([]any); ok {
		for i, item := range array {
			array[i] = directMaterialize(item)
		}
	}
	return value
}

// Typed input template: no cursor is boxed into any or published as Json.
// Final strings are owned; the validated index and input die with this call.

type tcCursor directCursor
type tcArray struct {
	cursor tcCursor
	count  int
}

func (c tcCursor) kind() byte {
	if c.document == nil {
		return 0
	}
	return directCursor(c).kind()
}
func (c tcCursor) text() (string, bool) {
	if c.kind() != '"' {
		return "", false
	}
	return directCursor(c).string(true), true
}

// Only statically selected discriminator comparisons use this view. All names,
// literals, paths and other strings stored in the final AST still use text().
func (c tcCursor) borrowedText() (string, bool) {
	if c.kind() != '"' {
		return "", false
	}
	return directCursor(c).string(false), true
}

func tcBorrowedTag(c tcCursor) gopurs_runtime.Value {
	value, ok := c.borrowedText()
	if !ok {
		tc_cndFail("String")
	}
	return gopurs_runtime.Str(value)
}
func (c tcCursor) number() (float64, bool) {
	k := c.kind()
	if k != '-' && (k < '0' || k > '9') {
		return 0, false
	}
	t := c.document.tokens[c.index]
	text := c.document.text[t.start:t.end]
	// Short integer tokens are exactly representable. Validation has already
	// checked their grammar. Preserve negative zero and use ParseFloat for every
	// decimal, exponent and larger integer to retain rounding/range behavior.
	if len(text) <= 15 {
		at := 0
		negative := text[0] == '-'
		if negative {
			at++
		}
		var integer int64
		for at < len(text) && text[at] >= '0' && text[at] <= '9' {
			integer = integer*10 + int64(text[at]-'0')
			at++
		}
		if at == len(text) {
			value := float64(integer)
			if negative {
				value = -value
			}
			return value, true
		}
	}
	n, err := strconv.ParseFloat(text, 64)
	return n, err == nil
}
func (c tcCursor) boolean() (bool, bool) { return c.kind() == 't', c.kind() == 't' || c.kind() == 'f' }
func (c tcCursor) array() (tcArray, bool) {
	if c.kind() != '[' {
		return tcArray{}, false
	}
	return tcArray{c, int(c.document.tokens[c.index].end)}, true
}

type tcIterator struct {
	cursor       tcCursor
	index, count int
	token        uint32
}

func (a tcArray) iter() tcIterator { return tcIterator{a.cursor, 0, a.count, a.cursor.index + 1} }
func (it *tcIterator) more() bool  { return it.index < it.count }
func (it *tcIterator) next() (int, tcCursor) {
	i, token := it.index, it.token
	it.index++
	it.token = it.cursor.document.tokens[token].next
	return i, tcCursor{it.cursor.document, token}
}
func (a tcArray) at(index int) tcCursor {
	c := a.cursor
	at := c.index + 1
	for i := 0; i < index; i++ {
		at = c.document.tokens[at].next
	}
	return tcCursor{c.document, at}
}
func (c tcCursor) Lookup(key string) (tcCursor, bool) {
	if c.kind() != '{' {
		return tcCursor{}, false
	}
	for at := c.document.tokens[c.index].end; at != 0; at = c.document.tokens[at].next {
		if (directCursor{c.document, at}).string(false) == key {
			return tcCursor{c.document, at + 1}, true
		}
	}
	return tcCursor{}, false
}
func (c tcCursor) Keys() []string {
	if c.kind() != '{' {
		return nil
	}
	return directCursor(c).keys()
}

// Preserve the public parsing/error boundary while constructing owned values
// directly on the successful path. Validation completes before schema decoding.
func ParseModuleTextImpl(fallback, validate, printError gopurs_runtime.Value, text string) gopurs_runtime.Value {
	cursor, ok := directIndex(text)
	if !ok {
		return gopurs_runtime.Apply(fallback, gopurs_runtime.Str(text))
	}
	result := tcDecodeModule(gopurs_runtime.Value{}, validate, tcCursor(cursor))
	if tc_cndIsLeft(result) {
		return tc_cndLeft(gopurs_runtime.Apply(printError, tc_cndLeftPayload(result)))
	}
	return result
}
