// Generated by purs version 0.15.15
import * as Control_Bind from "../Control.Bind/index.js";
import * as Data_Array from "../Data.Array/index.js";
import * as Data_Eq from "../Data.Eq/index.js";
import * as Data_Maybe from "../Data.Maybe/index.js";
import * as Data_Show from "../Data.Show/index.js";
import * as Effect_Aff from "../Effect.Aff/index.js";
import * as Effect_Class from "../Effect.Class/index.js";
import * as Effect_Console from "../Effect.Console/index.js";
import * as Effect_Exception from "../Effect.Exception/index.js";
import * as PureScript_Backend_Optimizer_App from "../PureScript.Backend.Optimizer.App/index.js";
import * as Test_Spec_Assertions from "../Test.Spec.Assertions/index.js";
var discard = /* #__PURE__ */ Control_Bind.discard(Control_Bind.discardUnit)(Effect_Aff.bindAff);
var liftEffect = /* #__PURE__ */ Effect_Class.liftEffect(Effect_Aff.monadEffectAff);
var bind = /* #__PURE__ */ Control_Bind.bind(Effect_Aff.bindAff);
var shouldEqual = /* #__PURE__ */ Test_Spec_Assertions.shouldEqual(Effect_Aff.monadThrowAff);
var shouldEqual1 = /* #__PURE__ */ shouldEqual(Data_Show.showString)(Data_Eq.eqString);
var shouldEqual2 = /* #__PURE__ */ shouldEqual(Data_Show.showInt)(Data_Eq.eqInt);
var moduleNameString = function (v) {
    return v;
};
var identString = function (v) {
    return v;
};
var main = /* #__PURE__ */ Effect_Aff.launchAff_(/* #__PURE__ */ discard(/* #__PURE__ */ liftEffect(/* #__PURE__ */ Effect_Console.log("=== Starting tcorefn Parser Sandbox ===")))(function () {
    return bind(PureScript_Backend_Optimizer_App.readCoreFnModule("output/Data.Unit/corefn.json"))(function (mbMod) {
        if (mbMod instanceof Data_Maybe.Nothing) {
            return liftEffect(Effect_Exception["throw"]("\u274c Failed to read or parse output/Data.Unit/corefn.json"));
        };
        if (mbMod instanceof Data_Maybe.Just) {
            return discard(liftEffect(Effect_Console.log("\u2705 Module successfully read and parsed from JSON!")))(function () {
                return discard(shouldEqual1(moduleNameString(mbMod.value0.name))("Data.Unit"))(function () {
                    return discard(shouldEqual2(Data_Array.length(mbMod.value0.imports))(1))(function () {
                        return discard(shouldEqual2(Data_Array.length(mbMod.value0.exports))(1))(function () {
                            return discard(shouldEqual2(Data_Array.length(mbMod.value0.decls))(0))(function () {
                                return discard(shouldEqual1((function () {
                                    var v = Data_Array.head(mbMod.value0.exports);
                                    if (v instanceof Data_Maybe.Just) {
                                        return identString(v.value0);
                                    };
                                    if (v instanceof Data_Maybe.Nothing) {
                                        return "missing";
                                    };
                                    throw new Error("Failed pattern match at Test.App (line 39, column 8 - line 41, column 29): " + [ v.constructor.name ]);
                                })())("unit"))(function () {
                                    return liftEffect(Effect_Console.log("\ud83c\udf89 All assertions passed successfully!"));
                                });
                            });
                        });
                    });
                });
            });
        };
        throw new Error("Failed pattern match at Test.App (line 26, column 3 - line 43, column 71): " + [ mbMod.constructor.name ]);
    });
}));
export {
    moduleNameString,
    identString,
    main
};
